### ISSUE TITLE
BIG CONCERN  (Not a software issue)

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#102]
**BIG CONCERN  (Not a software issue)**
The Call Center sends out notification of new clients to conference members.  
Assign new intake to: (the person identified in the drop down window that lists all the Conference members).  Email notification goes directly to that person (in my case Tomo).  This completely bypasses Intake at the Conference level and assigns every single case to the person in the window.  Problem is the Call Center has no idea of when Conference members are available to take on a case – or if they are on vacation somewhere else.  Somehow the Conference is the one that needs to make the assignment for each individual case.

**Possible Solution**
Maybe another fake Conference member called INTAKE needs to be established and all assignments go to INTAKE.  Then, INTAKE assigns the cases to the Conference members that are available at the time.  Not sure how to make this work seamlessly as the person taking INTAKE often changes from day-to-day.  Perhaps the various intake people could share an email address linked to the INTAKE “member” listed on the Call Center drop down window.

Comments Please!

**Comment by josephr5000** [comment]
As discussed in our meeting today, feel free to add yourself a dummy user called INTAKE to OLG, and set its email address to whatever you want it to go to.

**Comment by TomOwens5000** [comment]
1 and 2 are just fine.
I would edit 3 to say:  If case IS already assigned to someone, then leave it assigned to them but COPY *BOTH*

**Comment by josephr5000** [comment]
What 1, 2 and 3 are you referring to here?

**Comment by TomOwens5000** [comment]
The 1,2,3 points you made.
The procedure to take at point 3 needs to be modified as I indicated.

**Comment by josephr5000** [comment]
I'm looking up this screen and see no mention of 1, 2 or 3.  I suspect you're talking about a completely different issue, in which case you should put your comment on that issue.

**Comment by josephr5000** [comment]
Going back to the question you posed at the top of THIS issue, you are correct that the call center has NO CLUE who is on/off duty.  That's the whole reason this "Assign Intake To" is under conference control.  You can set and reset it at will.

It sounds like you have a daily round-robin in terms of "who's on first".  Perhaps an ideal solution would be (a) for admins to always be able to change selection of intaker, and (b) for the currently assigned intaker to be able to pass the baton to the next person.  Item (a) is in the current spec.  Item (b) would be an enhancement request.

Another alternative could be to separate the concept of "Assign New Intake To" from a new setting "Notify This Person About New Intake".  You could then always have INTAKE as the assign-to, but change the notify-this-person setting from day to day.  This would also be an enhancement request.

The bigger picture here is that the DB Committee should really do some deeper research to evaluate the intake patterns in a broader range of conferences that will use this site, so there is a better understanding of the range of requirements.
