### ISSUE TITLE
Non-administrator cannot view other members' information

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#103]
ENVIRONMENT
Windows 10, Chrome
ISSUE
Cannot view the files of other members when logged on as a non-administrator
WHAT PAGE
Member Roster from Main Page 
WHAT STEPS WHERE TAKEN
Clicked one of the other members, Active or Associate
WHAT I EXPECTED
To be able to see the name, address, phone number, etc. on a screen with a “Close” button
WHAT HAPPENED
Received the error message: “The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.”
Screen Shots

**Comment by josephr5000** [comment]
FIXED.

I used the opportunity presented by changes in this project to reorganize the scripts related to members into a nice subdirectory, but what you found here is that there are some links I failed to properly update to account for the new location.

RELATED TESTING IDEAS:
In this bug you hit 1 of 4 scripts that were renamed.  The 4 scripts that were renamed are:
1. Members/Default.asp, the readonly member profile page that you found in this bug report.  It is shown to Users for all profiles except their own, and to ReadOnlys for all profiles including their own.
2. Members/AddEdit.asp, the editable member profile page, shown to Users viewing their own profile, and to Admins regardless whose profile they're looking at.
3. Members/Index.asp, the Member/Officer Directory (which is only available to admins).
4. Members/OfficerEdit.asp, an editable page allowing admins to change officer assignments, available as a button from the Member/Officer Directory (also admin-only).

For the possibility of easy bug finds, and to help make sure all is ship-shape, check all ways you can click to reach each of these 4 to be sure the links/buttons are still behaving.

**Comment by drodruck** [comment]
Checked 1,2,3 and 4 and they all work now.  Hopefully there isn't something we didn't think of.

**Comment by josephr5000** [comment]
FYI the trick is to catch all ways you can *arrive* at those pages as it's the *links* that are subject to break.  Once you successfully reach the page, viewing should not be an issue.  So...if you've found all links that point to these pages we're good to go!
