### ISSUE TITLE
Time is off by 7 hours for the date in the notes and the "Updated" date field

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#104]
ENVIRONMENT
Windows 10, Chrome
ISSUE
The date/time is off by 7 hours
WHAT PAGE
Client File 
WHAT STEPS WHERE TAKEN
I created a new assistance record for a client, added a note and changed the data in the client’s file at 4:24 PM.
WHAT I EXPECTED
The Client File page should show the date and time for the note.
WHAT HAPPENED
The Client File page showed the date of the note as 9/1/2016 23:24, seven hours off.  I first noticed this yesterday evening when I updated a client’s file and the “Updated” date showed 9/1/2016, not 8/31/2016, the date I made the changes.
Screen Shots
 ![image](https://cloud.githubusercontent.com/assets/20655031/18188017/474e5c34-7063-11e6-94cb-6f59bd874147.png)

**Comment by josephr5000** [comment]
FIXED both cases: client updated date/time and note date/time.  Should both be in local timezone.  Please check after 5pm PT (midnight UTC in summer) to make sure the client modified date remains "today' and isn't tomorrow.

**Comment by drodruck** [comment]
Changed some information in Julia Taylor's file just now at 17:45 9/2/2016 and the "Updated" field was changed to 12/31/1899
![image](https://cloud.githubusercontent.com/assets/20655031/18221617/577dd648-7135-11e6-8360-ee05fa2d0123.png)

**Comment by josephr5000** [comment]
What browser are you using?

If EDGE, see #109 where I found it is misbehaving.

If another, please specify and REOPEN this if you think it still needs attention.  Thanks!

**Comment by drodruck** [comment]
I am using Chrome.  Looking at the file in both Edge and IE the date shows the same, 12/30/1899.  I tried it in another person's file in Chrome and it did the same, 12/30/1899.  The original problem with comments is fixed.

I cannot find a button or way to REOPEN.  Where is it?

**Comment by josephr5000** [comment]
FYI here's what the button looks like.  Do you not see it?

![image](https://cloud.githubusercontent.com/assets/8585358/18221771/f8241258-7138-11e6-9c90-6c0397ad0fc2.png)

**Comment by drodruck** [comment]
No, it does not show on my screen.
![image](https://cloud.githubusercontent.com/assets/20655031/18221782/4156fc10-7139-11e6-8e68-970190f1d29c.png)

**Comment by josephr5000** [comment]
As you just said on the phone: "it's working now!"

Using this opportunity to close it again :-)

**Comment by drodruck** [comment]
Not to make your life more difficult, but I saw that the "Updated" field again displayed 12/30/1899 after editing Taylor above in Chrome.  I tried adding a new client and saw the same 12/30/1899 date in the new client's record (in Chrome).  I then went into Edge, edited the new client and today's date now shows.  I then went back into Chrome, edited the file and 12/30/1899 shows again so it appears Chrome is the culprit.

**Comment by drodruck** [comment]
Okay, the two date issues both work now in Chrome, Edge, Firefox, and IE.  If you didn't do anything, it might have been that I rebooted.

**Comment by drodruck** [comment]
When the "Received" button is clicked for a conference not using the confdb, the date of the received message is off by 7 hours:
![image](https://cloud.githubusercontent.com/assets/20655031/19028846/945b8740-88f5-11e6-8ee6-f3f428e1406c.png)

**Comment by josephr5000** [comment]
This isn't the same issue.  Would you please open a fresh bug?  It gets very confusing trying to apply labels and count bug stats if the same issue gets resurrected for a new topic.

Do, of course, reopen this in future if the original issue cited at the top resurfaces!
