### ISSUE TITLE
Typo(?) in message to CC about when client should expect call back

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#105]
ENVIRONMENT
Windows 10, Chrome
ISSUE
Typo(?) in message to CC about when client should expect call back
WHAT PAGE
Client File 
WHAT STEPS WHERE TAKEN
I changed our Conference status to Open with expected wait of 48 hours for call back.
WHAT I EXPECTED
The Client File page for Call Center should show the clients will receive a call back within 48 hours.
WHAT HAPPENED
The Client File page for CC said client should expect a call back within “48 False”.
Screen Shots
![image](https://cloud.githubusercontent.com/assets/20655031/18191229/8cef8618-707d-11e6-8f21-e165d4356116.png)

**Comment by josephr5000** [comment]
FIXED.

I cannot confirm 100% with your data as it seems you changed your conference settings for MQOP to "Takes Calls Directly" in which case no expected wait is displayed.  Perhaps you could re-create the settings you used above and confirm?  Reopen with comments if you find any issues.

**Comment by drodruck** [comment]
Re-created the settings and can confirm it is fixed.
