### ISSUE TITLE
Show Stopper - need to be able to delete a note

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#106]
In addition to being able to edit notes, we need the ability to delete a note than makes no sense or has nothing in the note field.  In Open Requests on the screen below, see the last note (9/2/2016 16:23).  It is empty and serves no valid purpose and just clutters up the screen with something to look at that has no useful information in it.

![xxx](https://cloud.githubusercontent.com/assets/20777996/18211114/d663fd2e-70f0-11e6-9192-da64abb34b8b.png)

**Comment by drodruck** [comment]
I agree, perhaps give the permission to administrators only.

**Comment by TomOwens5000** [comment]
I'd give it to users too - at least for their 2 weeks.  For my part I think they should have longer than 14 days for make edits.

**Comment by TomOwens5000** [comment]
These edit issues are a HUGE SHOW STOPPER FOR ME!

The way it should work is that ALL users (and of course Administrators) can edit, modify or delete a note.  It is common practice either of our 2 or 3 team members to get into a Client File to correct typos, delete notes they have put in prior to the home visit or "homework" comments they have written for their own benefit before making a phone call to the Client (for example, discussions they had with SCL or landlords). Or deleting notes that are empty but have a date and time stamp.  Having a time-frame beyond which they can do so is not acceptable to our conference members.

Also, just tested entering a client request and there is still a problem. The date now goes in correctly the time is still not correct.

**Comment by josephr5000** [comment]
FIXED
