### ISSUE TITLE
Open Request: in Client File - Edit notes inconsistent

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#107]
On the screen below, note that the line starting [Owes: has no close] and the word _Edit_ is missing so you can't edit that line.  Also, every time you do make an edit it generates another date/time stamp - sometimes with the _Edit_ and other times without it.

![screen-15 03 55 02 09 2016](https://cloud.githubusercontent.com/assets/20777996/18219538/3251caf2-711f-11e6-85aa-b04abeef52d0.png)

**Comment by josephr5000** [comment]
Looks like the note was left by TomO, and from the fact you have Edit next to KarieO I'm guessing you're currently logged in as her.  Is that correct?  If yes, then she cannot edit YOUR notes unless she's an admin.  I'm guessing she isn't.  Could you please confirm?

Remaining issue is the close brackets which I'll look into.

**Comment by josephr5000** [comment]
The closing bracket is after the "payee contact:206-000-0000. ]" so that solves that question.

Please see #217 on the more general question to rethink note editing permissions.
