### ISSUE TITLE
Design Issue: Should client file be assigned to Intaker even if already assigned to another member?

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#108]
SCENARIO
- Call Center takes new request or note for a client
- Call Center user presses DONE button
- System sends notification to the conference's designated intaker
- System assigns client file to that designated intaker

OBSERVATION
It seems valuable and uncontroversial to make the assignment if the client's file isn't already assigned to anyone.  It brings the case to the intaker's attention, serves as notice to other members to leave the file alone until the intaker has reviewed it, and won't upset anyone who was already working on the case because no-one was (it was unassigned, remember?!).

QUESTION
What if the case IS already assigned?  EXAMPLE: a client called a few days ago, for example, the case was assigned to Member "AmazingVincentian", and then the client calls again with an additional request while their initial request is still being worked on.

Because the Call Center made a change (added a fresh request) an email notification will be sent.

But should the case be UNASSIGNED from "AmazingVincentian" and assigned to the Intaker?

OR should the email notification in this case be sent to "AmazingVincentian" (perhaps with copy to Intaker) since they need to know?

PLEASE ADD COMMENTS BELOW WITH YOUR THOUGHTS.
@drodruck @tomowens5000 @davidsherwood @jln522

**Comment by josephr5000** [comment]
TENTATIVELY RESOLVED with fix to issue #86.  Here's the resolution.  Please comment whether you think this design choice is reasonable.

1. ALWAYS email the designated intaker a notification that fresh intake happened.
2. If case is NOT already assigned to anyone THEN assign to the designated intaker.
3. If case IS already assigned to someone, then leave it assigned to them but COPY THEM on the email notification so they know that fresh intake (request or note) happened.

**Comment by josephr5000** [comment]
Closing on assumption that lack of comment after almost 3 weeks indicates acceptance.

**Comment by TomOwens5000** [comment]
Thought I did respond before. I said that the 3 steps you listed above are fine with me.
