### ISSUE TITLE
Choosing “This Week” does not set the correct dates for "Assistance Given"

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#110]
ENVIRONMENT
Windows 10, Chrome
ISSUE
Choosing “This Week” does not set the correct dates
WHAT PAGE
Main Page: Assistance Given 
WHAT STEPS WHERE TAKEN
Clicked “Assistance Given”
WHAT I EXPECTED
On 9/3/16 expected date range of 8/28/16 to 9/3/16
WHAT HAPPENED
Got date range of 9/4/16 to 9/10/16. This is probably related to the date/time problems in #104
Screen Shots
![image](https://cloud.githubusercontent.com/assets/20655031/18229365/c8c2db5e-722b-11e6-9888-f62581a34cf0.png)

**Comment by drodruck** [comment]
This may also apply to "This Quarter", "Last Quarter", etc. but can't test it until the end of the month. (I tried changing my computer date and time to 9/30/16 7:58 PM but it had no effect, the dates from and to were the same.)

**Comment by josephr5000** [comment]
FIXED -- I think!  As you noted, this can be tricky to test.

Hint: all date ranges key off the same evaluation of what constitutes "today" so it is sufficient to test any ONE of the pre-fab ranges and assert that it operates correctly.

Note: custom literally takes what you type, so it should never have had this problem, but you could confirm that remains the case!

Of the canned date ranges, "This Week" is probably the least inconvenient to test, as you have an opportunity every week on Saturday from 5pm onwards.

**Comment by drodruck** [comment]
Tested the date ranges on all of the reports I could see for both conferences and CC at 9:30 PM plus on 9/30.  All ranges passed!
