### ISSUE TITLE
Call Center Login - Notices Screen at sign in - can't cancel it

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#113]
Logged into CC. Notices screen appears. Checked Don't show this notice again. Clicked Done. Logged off and logged on again. The Notices screen appears again. Appears the Don't show this notice again message is not functioning.

![screen-17 40 28 04 09 2016](https://cloud.githubusercontent.com/assets/20777996/18234906/16daa484-72c7-11e6-996e-ce5c34f62ae2.png)

**Comment by drodruck** [comment]
Not limited to CC,this happens to any user in the Conference side also.

**Comment by josephr5000** [comment]
Yes, annoying.  Duplicates #71, but I'll keep this one open as it has a nice screenshot.  It's on the to-fix list.

**Comment by josephr5000** [comment]
FIXED.
