### ISSUE TITLE
Blue Sky enhancement - sorting order when entering files in Document Library

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#114]
When adding newly created file folders the list of folders is automatically re-alphabetized as each new folder is entered.
 
When adding stand-alone files (not contained in a file folder) are not.  The listing of files is based on what went in first.  Thus, if you want the list in the same order as you have it you have to enter the last item first and work your way up the list in order to preserve the desired order of the list.

Once the entire list is entered it would be nice to have a way to alphabetize them – or, better yet,  have them automatically be re-alphabetized when entered as it works for file folders.

**Comment by TomOwens5000** [comment]
It would also be helpful to be able to push and one entry into whatever position in the list you would like to have it.

**Comment by josephr5000** [comment]
Got your initial comment, thanks, and will look into it.  Not quite following your follow-on comment...could you explain a bit more?

**Comment by TomOwens5000** [comment]
Following screen from Microsoft.  Allows placing any one of the listed items anywhere in the list. For example, moving item in row 10 to row 3 - or wherever.  That is the "push" comment. In addition to this ...

It would also be nice to be able to sort the list alphabetically at the push of a button.  Hope this clarifies what I would like to see. Not a big priority but would be nice to have at some point in time.

These features would be nice when adding things to the Document Library and being able to have the displayed in the order you desire.  As it is now, it is first in goes to the bottom of the listing.  To counter that, you have to enter everything from the bottom of the list if you want it to display at the top of the list.

![rrrrrrrrr](https://cloud.githubusercontent.com/assets/20777996/18257660/35946c74-737c-11e6-9c48-d09761677672.png)

**Comment by josephr5000** [comment]
FOR NOW:  look at sort order of files and folders and make sure it's reasonable (either by title or by date).

FOR LATER: enhance to allow the user to change the sort order.

**Comment by josephr5000** [comment]
Looked into it.  Files are indeed sorted, by date uploaded.

Postponed the enhancement request for the user to be able to re-sort.  I agree that would be a helpful feature.  Being able to search for files would also be nice!

Feel free to close once you've read this, unless you want to lobby for it to be fixed this round.

**Comment by josephr5000** [comment]
Closing since the POSTPONE recommendation has been uncontested for over a week.

**Comment by TomOwens5000** [comment]
Willing to leave closed for now.
However, I REALLY FEEL THIS SHOULD BE A MUST somewhere down the road.
