### ISSUE TITLE
CC Browse Client Files - no add new client button

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#115]
I like the Search button approach. Truly much faster on this simple test. Also, red circle now shows processing is working. Searching as you type not missed by me. Searched on John Doe - fast results. Searched on Ottto Olsone. Showing 0 to 0 of 0 entries looks fine. Where is the Add New Client button? I see no way to create a new client. Maybe I am missing something. Pressing Enter key initiates search as expected.

Searched Doe. Showing 1 to 20 of 20 entries. ID numbers are there along with the rest of the information.  I don't see ANY X buttons like used the the Treasurer Pages to delete transactions. Therefore, I can't test KEY CHANGES item 4.

Did not see any Delete buttons - and I did log in as Administrator.

![hhhhhhhhhhh](https://cloud.githubusercontent.com/assets/20777996/18257869/bda63978-737f-11e6-970c-f1d8ecf7b2e7.png)

**Comment by TomOwens5000** [comment]
Went in again as a user. Still no Add Client button.

**Comment by TomOwens5000** [comment]
Guess this precludes testing the talking back and forth between the CC and Conference.

**Comment by josephr5000** [comment]
Not sure this is a bug.  Please re-try.

1. As the text next to the search button says, *first* you must search, and only after making the effort to avoid duplicates are you rewarded with an Add New Client button.  From the screenshot I see you hadn't done a search yet, so no reward (button).

2. The screenshot shows you logged into the Call Center.  The CC isn't permitted to delete client files.  You wouldn't want them removing clients from OLG's list, would you?!  Please retry when logged in as a conference admin.  Also note, you must search first so you have something to delete.

If following these suggestions works, please close this.  If not, please attach fresh screenshots showing the issue.

**Comment by TomOwens5000** [comment]
I am logged in as Administrator.
Yes, I DID to a search. Type in Last name and the search found no one. 
Take a look at the screen capture again.
Just tried again. Same result. Only and empty table at the bottom of the 
screen showing 0 to 0 or 0 entries.

The search filter finds no one so there can't be any duplicates. I think 
something got broken because a week or so ago repeating the exact same 
procedure on my part DID get the Add New Client button.

I never got in far enough to test your number 2 below.

**Comment by josephr5000** [comment]
FIXED -- turns out I mistakenly prevented CC users from seeing Add New Client.  Now fixed.

Re my item 2 that has nothing to do with item 1.  You should be able to log in as **a Conference user** and test that regardless whether item 1 is or isn't fixed, right?

**Comment by TomOwens5000** [comment]
Yep. Both work!
 

    On Monday, September 5, 2016 6:43 PM, josephr5000 <notifications@github.com> wrote:
 

 FIXED -- turns out I mistakenly prevented CC users from seeing Add New Client. Now fixed.Re my item 2 that has nothing to do with item 1. You should be able to log in as a Conference user and test that regardless whether item 1 is or isn't fixed, right?—
