### ISSUE TITLE
Main Page Reports Detail - Hours & Miles Detail - inconsistencies

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#118]
Title on main page is Hours & Miles Detail. The report says Volunteer Hours & Miles Driven.  Same as before with other inconsistencies. Not big deal but I noticed the difference.

**Comment by josephr5000** [comment]
Not seeing this.  Screenshot?

**Comment by TomOwens5000** [comment]
Ok. Here are two screen shots that show what I was talking about.
![another screen shot](https://cloud.githubusercontent.com/assets/20777996/18259436/c45177c4-7398-11e6-849f-1aca92aad885.png)

**Comment by josephr5000** [comment]
DUPLICATE.  You mentioned "driven" above, and that's what I'm not seeing.

Your screenshots seem to show this is a duplicate of #117 that you just filed.  Please correct me if I'm mistaken on that!

**Comment by TomOwens5000** [comment]
The report says **Volunteer Hours & Miles Driven.**  Driven is the last word in the report title.

**Comment by josephr5000** [comment]
Oh, I see what you're looking at.  Those aren't connected.  The "Record Hours Volunteered and Miles Driven" is **not a report** but, as the description says, for **data entry**.  Clicking it doesn't get you to the screenshot you put in below, but gives you this:
![image](https://cloud.githubusercontent.com/assets/8585358/18260675/d822a564-73a4-11e6-9d58-8f9db7723ee5.png)

In this case the link and page title are also a little different.  I think it's completely understandable, and there's a space premium on the page title so abbreviating a bit is helpful.  I would suggest WON'T FIX at this point.
