### ISSUE TITLE
Enhancement: Encourage More Email Verifications

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#119]
THE NEED

New CC features entail significantly more need for users to be reachable by email so the system can keep them informed of changes that affect them in two major cateogries:
- INTAKER.  If a user is on intake duty the system will notify them of fresh intake from the CC.
- ASSIGNEE.  If a user has an open case assigned to them, the system will notify them of any changes or additions from the CC.

THE PROBLEM

There are 785 active and associate users in King County, of whom 677 have non-blank email addresses HOWEVER only 101 have verified emails.

677 of 785 or 86% of them have given us an email address.  This is some indication that the vast majority of our members ARE potentially reachable by email and ARE willing to provide their email address to this system.

The problem is that we can't deliver email to the 677.  We can ONLY deliver to the 101 who have VERIFIED their addresses.

IDEAS

_This section is NOT YET COMPLETE.  Need to fill it in with some concrete ideas of steps we can take to encourage verifications._

**Comment by TomOwens5000** [comment]
The person who is administrator of each Conference needs to do the following.
1. Go online and see who has and who has not verified their email address.
2. For those with email addresses that have NOT been verified, contact them and actually take the time to personally walk them through the process and make sure verification takes place.

The administrator needs to understand the process! It is essentially no different than when he or she creates an account for a new Conference member. Showing the unverified person the steps involved and then actually walking through them is the solution.

I get each unverified person on the phone and let them know I am sending them an email that has screens shots of the procedure to be followed. After they have the email and look at the illustrations, again on the phone, I personally walk them through the process and verify that it was successful. It take some time but it works!

The screen shot below is what I use when establishing a brand new account for a new member but the same approach should suffice here as well. Having them see the screens they will encounter has made the process work more easily for me. Please don't use my screen with everyone as it has my personal information in it. Ideally, the screen itself should have dummy information in it.

![screen](https://cloud.githubusercontent.com/assets/20777996/18280542/3a731064-740e-11e6-942b-e2e8c98f55c5.png)

**Comment by josephr5000** [comment]
FIXED.  Tagging @drodruck and @TomOwens5000 with request that you help test it.

Expected behavior is this:
1. Check should be done immediately after login but before the main page is shown.
2. Check should be done for all users, conf & call center
3. If user has verified email already, should proceed directly to main page
4. If user has blank email, or email that isn't verified, should present them with a screen requesting their cooperation.  Here's a screenshot.
![image](https://cloud.githubusercontent.com/assets/8585358/18819089/249b4664-833e-11e6-8fdb-53f5c177be0d.png)
5. If user presses the large turquoise button they should get a screen confirming that verification email has been sent.  They should then actually receive said email.  Clicking on the link in said email should (after logging them in if they aren't already logged in) tell them their email has been verified.
6. If they have sharp eyes and notice and click the "Skip" link they should go to the main screen.
7. Successfully completing this campaign (verification per step 5 above) should *prevent* this screen being shown on subsequent logins.
8. Failing to complete successfully, or skipping, should result in this screen coming up every single time you log in, in hopes that it will eventually wear you down and convince you to cooperate!

If you could help test all the "shoulds" in the list above, that would be super fantastic.

@drodruck FYI this looks like it might bolt onto the existing site quite easily, but that can await your thorough and hopefully successful testing.  Having something fail on login is particularly, ummmm, unhelpful.

Thanks!

**Comment by TomOwens5000** [comment]
Joseph,
Something about this is broken. Can no longer log in with my wife information. Get the following screen shot. also got the following message on another attempt: error no such member. Can't test further until this has been fixed.

![capture](https://cloud.githubusercontent.com/assets/20777996/18821669/13240f3c-835d-11e6-9bba-e10613b38e80.PNG)

**Comment by TomOwens5000** [comment]
Will test this more tomorrow. Will have questions first but am about to be busy with something else now.

**Comment by josephr5000** [comment]
@TomOwens5000 Your screenshot shows you typed "karie". Your member/officer directory shows "karieo".

**Comment by TomOwens5000** [comment]
Give me a call.

![capture](https://cloud.githubusercontent.com/assets/20777996/18840790/98b29774-83c4-11e6-9da1-bcf3c83bbaa7.PNG)

**Comment by drodruck** [comment]
Even though I have verified my email and the email of a dummy member, we still get the screen asking us to verify our emails again.  I know we can skip it for now but do you intend to remove the screen once the email is verified?

**Comment by josephr5000** [comment]
@drodruck can you give me more detail please?  username/conference?

**Comment by drodruck** [comment]
My user name, drodruck, and the dummy name, ldelay, both in Mary Queen of Peace.

**Comment by drodruck** [comment]
I have administrator privileges and ldelay is a user.

**Comment by TomOwens5000** [comment]
I concur with what Doug said above. Had the same response here when doing the test for me.
Please call me as I have some questions BEFORE proceeding with any further tests.

Since we SERIOUSLY do want EVERYONE to provide their email address and have it verified so they will receive notification of cases assigned to them I suggest a bit more forceful request from us. See an alternative below.

![capture](https://cloud.githubusercontent.com/assets/20777996/18845256/dc9217ce-83d5-11e6-8ae8-e2be38d22360.PNG)

**Comment by josephr5000** [comment]
@drodruck should now be FIXED and no longer annoy you once you HAVE verified as requested.  Please confirm.

**Comment by josephr5000** [comment]
@TomOwens5000 FYI if you have problems with appearance/styling please let me know what browser you're using so I can narrow it down.  Thanks.

**Comment by drodruck** [comment]
I can verify user ldelay is no longer bothered.  I can't verify drodruck because I now get the Login failed message using the ID and password from confdb.org.

**Comment by drodruck** [comment]
It works for my account now.  Removed email, logged back in, verified email, then logged back in and was not bothered.

**Comment by TomOwens5000** [comment]
I removed my email address and sent the *Send me a verification email now!* notice. I did NOT get the image you sent to us. Instead the following screen appeared.

![capture](https://cloud.githubusercontent.com/assets/20777996/18851341/5d7e0586-83f0-11e6-84a5-6525cfb0d91b.PNG)

Of course not email was sent to me as the program has no way of where to send it. So the *Email Sent* screen is NOT what have been displayed. If I understand correctly, it should have displayed the *Email Confirmation Campaign* screen. Right?

When I DO put in my email address everything works as expected.

Also, not sure exactly how to duplicate it but another time I got a single line error message that said:  error no such member. Still trying to figure what I did so I can duplicate it.

**Comment by josephr5000** [comment]
Should only display the Campaign screen WHEN YOU LOG IN.

If you explicitly click "Send me a verification" from your profile, there's no need for a campaign to convince you as you're already convinced.  It just fast-forwards to sending you the verification as you saw.

What's odd about this is how you got it to send verification to a blank address.  Can you please try to repro that and open a separate bug since it has nothing to do with the campaign?  Thanks.
