### ISSUE TITLE
No response when client search initiated in Chrome, Firefox, or IE but perfect response in Edge

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#120]
ENVIRONMENT
Windows 10 Pro, Chrome, Firefox, IE, Edge
ISSUE
No response when client search initiated in Chrome, Firefox, or IE but perfect response in Edge
WHAT PAGE
CC: Find or Create Client Files and Conference: Main Page: Browse/Find/Add Clients 
WHAT STEPS WHERE TAKEN
Entered a last name, first name, phone, and address to search and both hit Enter and clicked “Search”.
WHAT I EXPECTED
The “dial” indicator showing a search was under way and ultimately a search result.
WHAT HAPPENED
In all browsers except Edge nothing happened. In Edge, everything worked perfectly including showing how long the search took.

**Comment by josephr5000** [comment]
Need help as I'm not seeing this issue.   Can you do a screen share and show me?

**Comment by drodruck** [comment]
Not sure a screen shot will help since the issue is a keystroke one but here is a shot from Firefox:
![image](https://cloud.githubusercontent.com/assets/20655031/18320397/7b657f3c-74de-11e6-9441-2b5cec48fcc4.png)

I hit Enter after typing the name and also clicked Search.  Nothing happens, the cursor doesn't even move out of the last name field.

BWT this issue is now only in Firefox and IE

**Comment by josephr5000** [comment]
FIXED.  You were seeing an old version of the page.  F5/Refresh fixed the issue.
