### ISSUE TITLE
DOB should enforce a minimum age

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#121]
Edit Client Info

- **DOB** - Not sure if there should be a priority on this, but perhaps there should be a “minimum” age to enter. There should not be a need to enter any age in this area, as someone may enter a wrong year by accident, putting client at a very young age, too young to be living without parents, like 1 years old. Although I did notice this does not accept 0 age.

**Comment by josephr5000** [comment]
When you enter DOB it calculates and displays the age, so you get immediate feedback if it wasn't what you expected.  Does the current HL DB have any minimum age?  How significant a problem is erroneous DOB entry?

**Comment by lisabarrientes** [comment]
Not a big problem....not sure about the conference end....

**Comment by josephr5000** [comment]
Queueing this up for discussion as a WON'T FIX or at least a POSTPONE.

**Comment by josephr5000** [comment]
9/7/16 Meeting Decision: 
- Leave search as-is
- Nice possible enhancement to sanity-check DOB but not at all sure we should do this now.  Agreed to POSTPONE.
