### ISSUE TITLE
City, State & Zip should be pre-set

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#122]
•	**City** – This should be a pull down menu, or that if you enter “Se”, it auto goes to the city corresponding to the search, rather than it being a “free-for-all” listing. 
•	**State** – Perhaps this should auto default to “WA” only. 
•	**Zip** – Like the City menu, this should not be a “free-for-all” listing, as you can enter as many digits, including phone numbers which will fit in this space, using Zip Codes that do not exist

**Comment by josephr5000** [comment]
Postponing this for now, but marking as SHOULD-FIX priority so we're sure to return to this after launch.

I think we might be able to use the Google Places Autocomplete to have it look up an address as you're typing (like Google Maps does), and then fill in street/city/state/zip when you pick the match you wanted.  If we can do this right, it could be a huge time-saver!  I really hate having to enter Seattle WA 98xxx all the time.

**Comment by josephr5000** [comment]
Reopening to discuss with Lisa before finalizing this decision...

**Comment by josephr5000** [comment]
MEETING DECISION.  Great 2017 priority.  Postpone for now.
