### ISSUE TITLE
Remove Rent/mort from Call Center Intake menu

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#123]
•	**Rent/mort.** – Remove from the Call Center Intake menu – we do not ask unless it is an RFA.

**Comment by josephr5000** [comment]
What do you mean by "Call Center Intake Menu"?  Not following you....

**Comment by lisabarrientes** [comment]
![image](https://cloud.githubusercontent.com/assets/22033172/18315849/5145f2ba-74cd-11e6-9ae4-9872fe51045f.png)

**Comment by josephr5000** [comment]
Got it, thanks!

**Comment by josephr5000** [comment]
FIXED

**Comment by lisabarrientes** [comment]
Fixed!
