### ISSUE TITLE
Make phone numbers entered to look like real phone numbers

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#124]
•	**Phone 1 & Phone 2** – Could this be set to look like an actual telephone number with the possibility of adding and extension number?  I.e. (206) 767-9975 x1131 vs 2067679975 x1131, or (206) 767-6449 vs 2067676449. It is like this in the current database system, with the exception of the extension number...you cannot currently add one that fits.

**Comment by josephr5000** [comment]
Triage pass.  Am setting this to postpone.  With phone numbers combined with notes in a single field, it is not straightforward to offer formatting for the number part of it.  To change this would probably take breaking the field up into separate number and notes fields, which is out of scope for this project.
