### ISSUE TITLE
Notes - Could this be larger?

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#126]
•	**Notes (eg:other family in area)** – I like that this has a scroll option, but can the window be a larger view? Perhaps five rows instead of three?  Also, can there be an auto capital letter when starting a new sentence, like the current database? Just makes for faster typing.  Not URGENT.

**Comment by josephr5000** [comment]
There are lots of places where notes are displayed.  To help me understand, could you be precise about *exactly which* place you're referring to here?  Thanks!

**Comment by lisabarrientes** [comment]
![image](https://cloud.githubusercontent.com/assets/22033172/18316389/3c9f1844-74cf-11e6-8647-b890e4efdb8b.png)

**Comment by josephr5000** [comment]
Got it, thanks

**Comment by josephr5000** [comment]
FIXED @lisabarrientes
