### ISSUE TITLE
Can St. James-Blessed Rosalie put in a quota so Helpline can test?

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#127]
**•	Override** – Can you please put a limit on St. James – BRR, to test this?

**Comment by josephr5000** [comment]
FIXED.

I set you up with your very own conference (called LisaB Test) that you can play with and adjust settings and create clients and users and change quota settings and have all sorts of fun.

Log in with username LisaB password jwa3r.

**Comment by lisabarrientes** [comment]
Thank you!  :+1:
