### ISSUE TITLE
Conferences not listed in new DB

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#131]
List of Conferences not listed in new DB
1.	Assumption-St. Bridget- Should this go to Assumption or leave as separate?
2.	Case Management – Not sure if we will use this for sending out RFA’s or just referral source?
3.	Christ Our Hope
4.	Direct Assistance Program (DAP) Will we continue to use this as a referral? Will funds replenish?
5.	Divina Providencia – Referral Source
6.	Email Test Conference – Is there a need for this option in the new database?
7.	Holy Family Seattle – Currently use the title name with OLOG email address.
8.	Our Lady of Fatima
9.	Our Lady of Lourdes
10.	St. Anne
11.	St. Benedict
12.	St. Joseph Seattle
13.	St. Matthew
14.	St. Monica
15.	St. Patrick
16.	St. Paul
17.	St. Peter
18.	St. Theresa (FW)
19.	St. Vincent de Paul

**Comment by josephr5000** [comment]
I can add most of them.

I need more clarification what you mean on items 2 and 4.  Also need you to decide about item 1 (or have Tom/Stephanie decide) as I don't know the latest status re St Bridget.

I think 6 might be fixed with the new "LisaB Test" conference, perhaps?

**Comment by lisabarrientes** [comment]
I guess we do not need item 2, but item 4 depends on the Council and whether we still will be using this in the future?  Perhaps Stephanie, Tom W. or Steve can answer this?

And Item 6 will work.  Thanks! :+1:

**Comment by josephr5000** [comment]
Wondering if you had a chance to ask Stephanie, Tom or Steve about your question on item 4?  Not urgent.  Just curious.
