### ISSUE TITLE
Conference name change

### ISSUE THREAD

**Issue by jln522** [josephr5000/confdb-public#133]
Blessed Theresa of Calcutta is now St. Theresa of Calcutta.

**Comment by josephr5000** [comment]
Yes she is!  FIXED.

**Comment by jln522** [comment]
I hope you caught my misspelling of her name. S/B Teresa

**Comment by josephr5000** [comment]
That's a good question.  Did you check?

**Comment by jln522** [comment]
Yes

Sent from my iPhone

On Sep 8, 2016, at 10:22 AM, josephr5000 <notifications@github.com<mailto:notifications@github.com>> wrote:


That's a good question. Did you check?

-
