### ISSUE TITLE
Unable to edit Test conference

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#136]
![image](https://cloud.githubusercontent.com/assets/22033172/18363090/69a49c12-75bd-11e6-843d-8120910d2fc7.png)

**Comment by josephr5000** [comment]
BY DESIGN.

You're looking at it from the CC.  CC admins aren't allowed to EDIT conference settings, just to VIEW them.  To edit it, log into the "LisaB Test" conference, and change it from that end.  Make sense?

**Comment by lisabarrientes** [comment]
Yes, I get it now, but what is the username, password for that?

**Comment by lisabarrientes** [comment]
Nevermind, found it.

**Comment by lisabarrientes** [comment]
Sorry, but I tried logging in with the username and password you assigned for this account, but I am still unable to log into the LisaB Test conference.

**Comment by josephr5000** [comment]
Not sure what happened, but I reset the password.  Please try again.
