### ISSUE TITLE
Question about switching Add New Client Screen vs Edit Client Info Screen

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#137]
Is it possible to have the Call Center Intake screen, be just like the Add New Client Screen versus the Client File Screen: Edit Client Info ?  This will allow us to make changes to addresses and conferences like we do now with our current database. So once you open a client file, where the Edit Details are, and replace that screen with the Add New Client Screen instead? So, when you hit the "Edit Details" button it would look like the Add New Client Screen, but renamed Edit Client Details, rather than Add New Client.
![image](https://cloud.githubusercontent.com/assets/22033172/18397195/f5ab161e-767b-11e6-8935-d797e88d8c44.png)

**Comment by josephr5000** [comment]
Can we stay online after the meeting this morning and have you do screen share and show this to me?

**Comment by lisabarrientes** [comment]
Yes, please.

**Comment by josephr5000** [comment]
I think we resolved this in our meeting today so I'm going to close this.  But definitely please speak up if you have any further questions about this, okay?  Thanks.
