### ISSUE TITLE
Frequent Callers - Add Client Last Name to Selection Criteria List

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#142]
More often than not we know the last name of the person in our head that we want to check on. No problem knowing the year or how many occasions we want to check on. The address field is good too and should stay there but few of us will remember the address in our head and would have to go somewhere to find it. Being able to type in the last name would be a big time saver. 

![frequent flyer](https://cloud.githubusercontent.com/assets/20777996/18421999/088ef2da-784a-11e6-9dd8-a976f6879b89.png)

**Comment by josephr5000** [comment]
This report isn't designed to find a specific *individual* but rather to list frequent callers at a certain address.  For example, if you want to know who the frequent flyers are at 223 Yesler Way (the Frye).

If you're looking for a specific individual, I would recommend Browse/Find Clients as a far better approach.

Does that resolve your question?

**Comment by TomOwens5000** [comment]
Understand what you are saying. However, using that approach requires bringing up the Active File (if it is still active) and then reviewing all the entries in the Assistance History to individually look at all the entries and actually count them to determined how many times they have been helped.

If you added the Name search the answer would be there in one step. In our Conference there have been a number of times when a member wanted to know on how many occasions we helped a person. In many of these cases we actually remember the name of the person we want answers for but can't recall their address from memory. I am glad you are keeping this OPEN. Hopefully, someone else may have some input to add.

**Comment by josephr5000** [comment]
The request for some better summary of how frequently people have been helped is reasonable.

I'm not convinced it belongs in *this particular report*, but that's a design question.

Before we get there, this is clearly an enhancement request not in the scope of our current project, so I've tagged it as such so we can return to it after we go live, and revisit this and the various other things people would like worked on next.
