### ISSUE TITLE
Call Center - Entering address to find client - search no longer brings up the map

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#143]
This worked before. Not working now.

**Comment by josephr5000** [comment]
Tom, I think you might have to give more explicit step-by-step of how your reproduce this for me to be able to follow you.

I tried:
- Log into CC
- Click Find or Create Client Files
- In Address, enter "210 12th ave e, seattle" and press the lookup button

It worked fine.  I got a map correctly pinpointing the address I entered.

**Comment by TomOwens5000** [comment]
Stupid mistake on my part. Had just come back from a client visit and was showing a new member some of the software. We were talking and I got distracted and pressed Search by mistake. Should have clicked on Lookup. Yes, it does work correctly. Am closing the issue. Sorry for waiting your time.

**Comment by TomOwens5000** [comment]
My mistake. See closed issue on issue tracker.
