### ISSUE TITLE
Doc Library: upload fails for files >4MB

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#145]
Originally reported by @drodruck and @TomOwens5000.  See related #85.

ISSUE:
Current TEST site fails for files >4MB.
Current production site allows larger files, although I don't know the precise limit.

**Comment by josephr5000** [comment]
FYI see this analysis of file sizes ACTUALLY UPLOADED by conferences as of roughly 9/1/16:
[sizes.xlsx](https://github.com/josephr5000/confdb-public/files/477699/sizes.xlsx)

Looking at the profile, about 94% of files are 4MB or smaller and would do just fine with the current limit.

This suggests to me that while a higher limit would be nice to have, it is not necessarily a show-stopper, and could be fixed post-launch.

The more helpful thing would be -- whatever the limit -- if the limit were displayed on the upload screen and checked BEFORE upload rather than having upload fail after you've waited for all the data to be transferred.

The interesting design question is WHAT size limit is justified by the usage data.  Your thoughts @drodruck, @tomowens?

**Comment by josephr5000** [comment]
FIXED.  I found an easy way to raise the limit to 10MB which handles 98.5% of current files and is a nice round number.  As a BONUS, the upload screen now shows you your file size after you select a file, AND it disables the upload button and displays an error if your file exceeds the limit, so you don't waste time uploading only to have it fail at the end.

Feel free to argue for a limit higher than 10MB if you see the need, but I have my doubts whether that's justified.

**Comment by josephr5000** [comment]
Doug, Tom, feel free to unassign yourselves once you've tested it.

**Comment by TomOwens5000** [comment]
Our Conference Manual is 3,910 KB and crashes. Need to have it on our the web site!
(And it will be getting quite a bit larger when I add screen shots of the new software.)

ERROR MESSAGE
This XML file does not appear to have any style information associated with it. The document tree is shown below. (Sending your a separate email of my finding on our DocLib.)
ResourceNotFoundThe specified resource does not exist.
RequestId:8cf79759-0001-00c0-4864-10ba32000000
Time:2016-09-16T21:48:13.5239292Z

In response to you email regarding file sizes ... We have in our DocLib:

US Manual Chapter 1 Vincentian History 15,184 KB
US Manual Chapter 2 Vincentian Conferences 20,564 KB
US Manual Chapers 3 Vincentian Spirituality 28,323 KB

All 3 are PDF files. Work fine in LIVE version. All crash in BETA version with above error message.

If this the file size is not enlarged to accommodate these files we won't be able to have them on the site! Thus, I would argue for a limit of 30,000 KB.

**Comment by TomOwens5000** [comment]
Same error message for me:
![screen-18 14 54 16 09 2016](https://cloud.githubusercontent.com/assets/20777996/18604936/91c239a2-7c39-11e6-8774-d8d6e6a0c141.png)

**Comment by josephr5000** [comment]
Tom, I just tried and succeeded at uploading your file "Conference Manual dtd 5.27.16.pdf" into a "Joseph Test" folder that I created in your doc library.  You should be able to see it.  I then clicked on it and it downloaded beautifully.  Would you please retry it?  I did have some problems with my browser picking up the fixed version of the upload page -- you'll know you have the right version if it shows you the size of your file.  Here's what the upload page should look like:

![image](https://cloud.githubusercontent.com/assets/8585358/18605275/0d952cda-7c42-11e6-8009-d6f4bb17d0ce.png)

**Comment by TomOwens5000** [comment]
Works as you describe. I tried uploading a couple of files that are under the file size limit and they worked just find. I like that they now show the file extension. What is still missing, and very important to me, is the drop down box  



![screenxxxx](https://cloud.githubusercontent.com/assets/20777996/18605386/b618e09c-7c45-11e6-9def-f49a66fd6a55.png)

**Comment by josephr5000** [comment]
Rename, Move and Delete are an entirely separate issue so let's not discuss that here.  It gets too confusing.

Glad to hear this now works for you, so I'll call that FIXED.

Your three very portly files will be migrated over, so you won't need to upload them afresh.  This policy would prevent you uploading similarly-sized files in the future but wouldn't present an issue with these.

As to whether such large files are reasonable to permit moving forward, I haven't yet seen indication that there is demand for that.  As you can see from the spreadsheet, 94% of files are under 4MB.  98% of files are under 10MB limit that I provided in this fix.  The outliers are some very unusual cases that I'm not entirely sure would repeat.

I would suggest a policy should allow upload of **conference-specific** files of **reasonable** size.  It's not reasonable for every conference to upload 65MB (that's the combined size) of US Manual files.  That's why they're available on the SVDP Members' Website for download, and that's a much more appropriate location.  You could upload a document reminding your members how to get there and download the manual.

Please note there is no upper limit at the moment on the total amount of files you can upload.  If you encounter situations where you need to upload conference-specific single files (that can't be broken into chapters) larger than 10MB, please get in touch.

I'm not opposing a higher limit by any means.  I just don't see that this case -- 65MB of US Manual files -- is a reason to do that.

Your own conference's next largest file appears to be the conference manual, and that's under 4MB at the moment!  Again, if you find a good need that isn't this scanned US Manual, speak up.  This can be increased in the future.

**Comment by josephr5000** [comment]
PS: feel free to attach the DISCUSS label if you'd like to cover this policy question at next Thursday's meeting, and you can see if others share your need for really large files.

**Comment by josephr5000** [comment]
You're asking that this be queued up for discussion, so why would you need to unassign yourself yet?  You're still in the driver's seat....unless you no longer want to discuss it.  Let me know about that.

I didn't say you could upload such large files.  I did say migration would grandfather these three in.

**Comment by josephr5000** [comment]
DISCUSSED AT THURSDAY MEETING.  TOM AGREED 10MB IS FINE.
