### ISSUE TITLE
Browse/Find/Add Clients - clicking on Search for Voucher returns an error message

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#148]
Same result in both scenarios. One, nothing entered in any search field (all fields blank). Two, with something entered in at least of search field.

Result: The page cannot be displayed because an internal server error has occurred.

Scenario 1 - expected to see a message indicating no valid search data entered - or something to that effect.
Scenario 2 - if no voucher exist I expected to see a message to that effect.

**Comment by josephr5000** [comment]
Could you clarify: are you logged in as a call center user, call center admin, conf user or conf admin?  Thx.

**Comment by TomOwens5000** [comment]
Logged in as Conference Administrator.

**Comment by josephr5000** [comment]
FIXED.  Interesting issue.  There was an error in the path that would have tripped up ANYONE using this feature.  Interesting that it hadn't been caught before now.  Thanks for your thoroughness.
