### ISSUE TITLE
Call Center - Loging in as user - bring up Browse ... will not leave page

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#149]
Behaves differently than before. Is that by a new design?
When logging in as a user the screen below appears automatically (with no intervening screen first).  Before there was a main page screen first with a logout feature. Not so now! When I clicked on Main Page nothing happened (I had not entered any information so all fields were blank - not sure if that is the issue). The screen was simply frozen. I was able to click on Logoff and get out.

This issue is not present when logging in as Administrator.

![xxxscreen](https://cloud.githubusercontent.com/assets/20777996/18605610/fd27f8ce-7c4a-11e6-839b-87181cf709b4.png)

**Comment by josephr5000** [comment]
Good catch!  Lisa requested a design change to simplify things for her call center volunteers.  See #144.

FYI @drodruck
