### ISSUE TITLE
Show/Hide Memos box does not work

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#150]
ENVIRONMENT
Windows 10 Pro, Chrome and Firefox
ISSUE
Show/Hide Memo
WHAT PAGE
Client File 
WHAT STEPS WHERE TAKEN
Clicked the Show/Hide Memos box
WHAT I EXPECTED
Memos would disappear
WHAT HAPPENED
They are still there!
Screen Shots
![image](https://cloud.githubusercontent.com/assets/20655031/18605634/10c2c264-7c4c-11e6-9b68-781711a89900.png)

**Comment by josephr5000** [comment]
Thanks!  On the list to fix :-)
