### ISSUE TITLE
CC - Logged in as User (not Administrator) - Main Page link should be removed and replace with *Clear* or *Refresh*

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#153]
ENVIRONMENT
Windows 7 Home Edition and Firefox

ISSUE
Logged in as CC User (not Administrator).
Browse Client Files comes up by default.

WHAT PAGE
Browse Client Files.

WHAT STEPS WHERE TAKEN
Clicked Clicked on Main Page.

WHAT I EXPECTED
To go back to the main page, as it should.

WHAT HAPPENED
Nothing!
Since this now, in practice, is the Main Page it makes no sense to display     Main Page    Logoff.
Should ONLY display Logoff.

COMMENT
If logged in as Administrator, Main Page does, in fact, take you to the Main Page.

Screen Shot
![screen](https://cloud.githubusercontent.com/assets/20777996/18611354/1dab7832-7ceb-11e6-8a32-61b8df4745ed.png)

**Comment by TomOwens5000** [comment]
In looking at this again.  Instead of eliminating Main Page, replace that text with a Clear or Refresh button as pressing Main Page actually does clear everything in the Lookup Client's Address and Search Filter fields. It also clears everything displayed under "Showing x to x entries". I see why this is useful for the CC intake person if they want to clear everything out and start over from scratch for whatever reason - ready to enter another client or to start over with the existing client if that is faster than making any necessary corrections.

**Comment by josephr5000** [comment]
This doesn't strike me as a show-stopper, HOWEVER I'm keeping it open with low priority in case we have time to fix this.  It would be nice to get rid of "Main Page" as you suggest, AND also to add a Reset button (I think you mentioned that elsewhere) which would be more clear.

**Comment by TomOwens5000** [comment]
Suggest a SHOULD Prioritization.
