### ISSUE TITLE
Date and time 12/30/1899 for User making a comment

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#154]
ENVIRONMENT
Windows 10 Pro, Chrome
ISSUE
CC User adding note
WHAT PAGE
Record New Request screen 
WHAT STEPS WHERE TAKEN
Recorded new request with a comment logged in as CC User
WHAT I EXPECTED
Today’s date and now for time
WHAT HAPPENED
Got the date of the comment as 12/30/1899 00:00
Screen Shots
![image](https://cloud.githubusercontent.com/assets/20655031/18612534/8b1417be-7d11-11e6-98e1-fd8c370873ac.png)

**Comment by TomOwens5000** [comment]
I too have observed the same issue. On one place the date is shown correctly but the time is always bad.

**Comment by TomOwens5000** [comment]
I have encounter this other places as well but not sure now just where they were.

**Comment by josephr5000** [comment]
FIXED
