### ISSUE TITLE
Unnecessary blank note created on Add New Request

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#159]
TO REPRO
- Add New Request
- Enter header details but LEAVE NOTE BLANK
- Press Save & Done

NOTICE
- Client file shows request WITH BLANK NOTE

EXPECT
- No note, since I didn't add one.

COMMENT:
- The note header clutters the screen, and is puzzling since it's a header with no content, and puzzling since I didn't create any note.  Later a reader might wonder if something's wrong / missing since it's so odd to have a header with no content...undermines confidence.  Should fix this design!

**Comment by josephr5000** [comment]
FIXED.  @drodruck could you verify this?

Should check separately with:
- Add Request with blank note
- Add Note (to existing request) then leave note blank and press Save
- Help Without Request with blank note
- Close Request leaving note blank

In all 4 cases whatever other changes you make should be saved (eg: category, amount, etc) but no note should be added so long as you leave the note field blank.

Would recommend you repeat the 4 above *with* a note to be sure I didn't just never save notes :-)

**Comment by drodruck** [comment]
Trying all of the permutations above with and without notes, etc. all looks good (until someone thinks of another way to mess it up).
