### ISSUE TITLE
Questions about the ERROR sending Intake Notifications

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#160]
I am getting a lot of these errors, from different conferences.  I guess I should since I should be aware.  My question is: What is the proposed step, for the Call Center Admin?  How do we notify the conferences involved, or is it supposed to be that way? Is there a quick notification message I can send to conferences?

**Comment by josephr5000** [comment]
"Is it supposed to be that way?"  No.  The error message indicates that something is NOT working.  But it is true that if something doesn't work the system is designed to let you know :-)

"How do we notify the conferences involved?"  I would suggest you forward the email message to your contact there, together with a request that they fix the condition.  It's likely to be one of two things, and the error message will explain more precisely.  Either (a) the intaker, or (b) the assignee, have email problems that are preventing us sending them notification of call center activity.

"Is there a quick message I can send conferences?"  Yes.  Have their intaker or members (depending on the error) set and verify their email addresses.

HOWEVER PLEASE NOTE THIS--

Your questions touch on a bigger problem which will require more help to solve.  I think the system needs to be nagging users directly about providing and verifying their email addresses, to try to get in front of this.  When I last looked I found a high percentage of users had provided emails (this is good) but a low percentage had verified them (this is bad).

My goal will be to modify the system to help and encourage those users to complete the verification process.  This will reduce the number of these kinds of errors that you're seeing.
