### ISSUE TITLE
CC - GMT Issue when Add Turn-Away

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#161]
Created file for client. See first screenshot below.
Tested Add Turn-Away. See second screenshot below.
*Expected*: the date to be the same, as hardly any time elapsed between creating the Client File and attempting the turn-away.
*Result/Comment*: apparently the date being inserted for the turn-away is still based on GMT, as it is one day ahead of current time. (I tried this again with all the field completed and saved - same result).

![screenshot1](https://cloud.githubusercontent.com/assets/20777996/18694020/5c35f8c6-7f5b-11e6-894a-e83975b77dd8.png)

![screenshot2](https://cloud.githubusercontent.com/assets/20777996/18694034/79264b8e-7f5b-11e6-84b7-9da95b3212cb.png)

**Comment by josephr5000** [comment]
Cute file, Tom, very funny.  You can tell Daisy she can now be denied her duck food in local timezone, although you'll probably have to wait until after 5pm this evening to confirm that!
