### ISSUE TITLE
CC - Add New Client - * denotes required fields - state does not have *

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#162]
Not sure if the State is absolutely required or not. If so, it too should have a red *. If not required, no asterisk is fine.

![capture](https://cloud.githubusercontent.com/assets/20777996/18694417/9d689670-7f5e-11e6-82bc-847fd3af1e22.PNG)

**Comment by josephr5000** [comment]
Tom, you can find out for yourself whether it's required.  Please add a client without one and see if it complains.  If it does, then reopen this.

**Comment by TomOwens5000** [comment]
Ok. Just checked it. I see that your have REMOVED the required field from everything except the first and last name fields. Guess we can leave this one CLOSED>
