### ISSUE TITLE
Enhancement Suggestion: Use the Enter key instead of the mouse when logging in - faster/more efficient.

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#163]
When a CC Admin or CC User click on Search or hit the Enter key the search is invoked. Hitting Enter is faster than having reach the mouse and click on Search.

Hitting Enter after the Conference field is completed would also be faster for the same reason and is a suggested enhancement.

![conlogin](https://cloud.githubusercontent.com/assets/20777996/18694541/d7ea07b0-7f5f-11e6-9f43-e804a46745e6.png)

**Comment by josephr5000** [comment]
You can press TAB then Enter.  Pretty fast.  I do it all the time.  Try it!

**Comment by TomOwens5000** [comment]
Pretty slick. Almost the same as Enter in terms of efficiency, avoid having to reach for a mouse. Works for me.
