### ISSUE TITLE
Document Library - OLG Conference, Conference Manual issue

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#164]
Conference Manual is 3,910 KB – error message:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:76847ad0-0001-000e-1eef-14dc7d000000
Time:2016-09-22T16:35:53.5371900Z</Message></Error>

Just tried again and now it works. Why work now and not before? Did Joseph fix something?
In the past it worked, then did not - and now it is working again. Most curious.

**Comment by josephr5000** [comment]
I broke some links when I did the 0923 database refresh, which I think I have now fully resolved.  Please try again, and close if this question is answered.

**Comment by josephr5000** [comment]
Related #166

**Comment by TomOwens5000** [comment]
Conference Manual now works.
Closing this one.
