### ISSUE TITLE
Show/Hide Memos on Client File does nothing

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#165]
Neither of the buttons appear to be working. I know, the Show/Hide Memos issues has been reported before but you, Joseph, told me to report the Show/Hide Payment Buttons as a separate issue. So here it is before I forget to do it.

![capture](https://cloud.githubusercontent.com/assets/20777996/18764844/05fcaebe-80c8-11e6-8198-cc3f2d4ad883.PNG)

**Comment by josephr5000** [comment]
Repro'd.  Set priority = must-fix.

**Comment by josephr5000** [comment]
FIXED.  Trying a new system where I assign to you for verification and let YOU close it if you agree it's fixed or assign it back to me with comment if not.

**Comment by TomOwens5000** [comment]
Agreed, fixed.
