### ISSUE TITLE
Show/Hide Payment Buttons do nothing (same issue for the Show/Hide Memos which were reported earlier by someone else).

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#167]
Joseph, you asked me to report this as a separate issue. So here it is before I forget to do so.

![capture](https://cloud.githubusercontent.com/assets/20777996/18765089/0a476f44-80c9-11e6-97a6-52b0129b61f9.PNG)

**Comment by josephr5000** [comment]
Repro'd.  Prio: must-fix because it's a key shortcut for treasurers to use to record payments on pledges.

**Comment by josephr5000** [comment]
FIXED.  Trying a new system where I assign to you for verification and let YOU close it if you agree it's fixed or assign it back to me with comment if not.

**Comment by TomOwens5000** [comment]
Agreed, fixed.
