### ISSUE TITLE
Windows 10 Anniversary Update - problem, or some other issue

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#168]
Karieo on regular current site.

Went to Susan Hill. Tried to edit the closed record notes. Clicked on Save and it crashed the program. 

Error message:Microsoft JET Database Engine error ‘80040e21’
Update or CancelUpdate without AddNew or Edit.
/confdb/DoRecordSave.asp, line 100

Yesterday Windows 10 Anniversary Update was installed on her machine.
Never had this problem before the above update. Not sure if this is the issue or something else.
Precludes her from working on her computer. She is intake person.

Added new request for same client.  Clicked on Save and was kicked out to Log In Screen with nothing saved.  Got back in and it worked properly that time.  Norene said she had the same problem before and Karie thinks it's happened before to her also.

Subsequently tried to close this new request and the program crashed in the same manner as described above.

**Comment by TomOwens5000** [comment]
Joseph,

This may turn out to be an issue for anyone who has made the Windows 10 Anniversary Update --- and, accordingly, a BIG problem for us
.
When closing a client request (either after editing something or not editing something) the following message appears - after kicking you off the database site. CAN YOU SHED ANY LIGHT ON WHAT IS HAPPENING? IS THIS SOMETHING YOU NEED TO MAKE A PATCH FOR?

![capture](https://cloud.githubusercontent.com/assets/20777996/18844552/89c5fae0-83d2-11e6-8153-fdd0e3c17425.PNG)

**Comment by drodruck** [comment]
Turns out the problem was the Ad Blocker on Edge.  When it was turned off, confdb worked as before.

 

Doug
