### ISSUE TITLE
Request by Board Member Bob Rohrbach - new reports for grant application purposes

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#170]
Bob asked me if there is going to be two reports.
One, a report summarizing the number of children served.
Two, a report summarizing the number of adults 65 and older.

Suggest Joseph contact Bob to see what type of layout he has in mind and determine whether or not it will get implemented and, if so, when.

**Comment by josephr5000** [comment]
Related #177

**Comment by TomOwens5000** [comment]
Suggested to Bob that he contact you Joseph.
Ball is in his court.
Closing this one.
