### ISSUE TITLE
Use of the asterisk to denote required fields

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#171]
We have talked about this before.
Turns out required fields vary from one place to another.

Conference Site
*Originally,* the red asterisk indicating required fields on the Add New Client screen was on the First Name, Last Name, Address and City fields – but NOT on the State field. I see you have made a change. Now it is ONLY on the First Name and Last Name fields (NONE of the others anymore). See screen below.

![capture](https://cloud.githubusercontent.com/assets/20777996/18846129/59341478-83d9-11e6-8efc-d2b8d6a0a583.PNG)

Call Center Site
On the Add New Client screen on the Call Center site the asterisks are back to how they were originally – First and Last Names, Address and City. But again, NOT on the State. See screen below.

![capture1](https://cloud.githubusercontent.com/assets/20777996/18846243/d68b15d4-83d9-11e6-87a1-d1c22548e0ce.PNG)
  
Here is the issue on the Conference site.
If you fill in the name, address and city fields but do NOT put anything in the state field and press Locate Address button to get the map you invoke a message indicating that the state is also required. See screen shot below.

![capture2](https://cloud.githubusercontent.com/assets/20777996/18846308/20223ace-83da-11e6-9441-dcc8276ef631.PNG)

After providing the Assigned Conference and clicking on Save & Continue the program progresses as expected (without having entered a state).

*To me, this is inconsistent behavior.
I think the state field should be a required field at both the Conference and Call Center.*

**Comment by josephr5000** [comment]
Discussed with Tom.  Understood the looser arrangement in conferences is BY DESIGN.  Agreed it might be helpful to red-star the CC screen's State field.

**Comment by josephr5000** [comment]
Added red asterisk next to State for CC users/admins, as noted above.

Close if/when you're happy with the fix.

**Comment by TomOwens5000** [comment]
Works great. Thanks. Closing issues.
