### ISSUE TITLE
Active File comes up slowly after fresh data import

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#173]
You made improvements on how long processing takes. Appears it is now taking longer than after those adjustments. Not sure if anyone else is noticing the same. Noticed this when waiting for an Active File to be displayed on the Call Center site after adding a new client.

**Comment by josephr5000** [comment]
I did some work on indexes in the back-end database and it *appears* that the active file is now coming up reasonably quickly.  Would you please let me know how it's behaving on your end at the moment?

If you find it acceptably quick, then feel free to close this.  If it remains unacceptably slow, then I'll actually run some benchmarks to measure it so we have more hard data.  Let me know.  Thanks.

**Comment by josephr5000** [comment]
I'm being optimistic (hopeful!) with the FIXED label, but am not yet closing this pending your evaluation.

**Comment by TomOwens5000** [comment]
Much faster now, fixed.
However .... I am leaving this open because there is no error checking yet implemented (or a bug) if the now required State field is left blank. Yes, I noticed the red * for the State field now. Thanks for that. After the State missing error checking is done this one can be closed.
