### ISSUE TITLE
Suggested Enhancement for prior to release

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#174]
On drop down list of Conferences ... display ONLY KC County conferences.

Will make scrolling through the list more efficient and decrease the occasions of sin - i.e., clicking on the wrong conference.

**Comment by josephr5000** [comment]
Agreed, this would be nice.  Suggest this be revisited later as it's not a show-stopper and requires some design work to have it work well.  Clearly getting rid of everything outside KC would be unpopular with users outside KC!  Obviously that's not your intent, but my point is just that some details need to be thought through.
