### ISSUE TITLE
2.12 Notifications sent to Conference failed

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#176]
Tested: To avoid that new requests mysteriously appear in conference files and no-one in the conference notices, ConfDB will send notifications to conference users who enable them in their profiles. Existing Request Edited.
I added two different notes and got this message both times: No notification was sent since there was no news (no new requests, no new notes) since the last notification.
I had verified my email address as an administrator but not sure this was working since the Profile still says email not verified.

**Comment by DaveSherwood** [comment]
Also, 3.4 testing, I couldn't complete because I can't seem to get my email address to be verified.

**Comment by josephr5000** [comment]
@DaveSherwood re email verification, please open a separate issue and be more explicit about exactly what steps you tried, what happened vs what you expected.

Re adding two diff notes, I assume you were logged in at the Call Center?  Please clarify what username, and which client's file you were updating so I can try to reproduce it.  Thanks.
