### ISSUE TITLE
3.5 Admin Report - Age Groups Served

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#177]
Clicking on this report doesn't open a report.

**Comment by josephr5000** [comment]
I could go find the spec and cross-reference, but it's faster on this end if you give a little more detail.

Which conf were you logged in as, which user, and which report did you click.

When you say "doesn't open", what happened precisely?  Error?  Blank screen?  Other...?

**Comment by DaveSherwood** [comment]
Hi Joseph, when logged into the call center as ccdaves, the Report is not underlines like the other reports suggesting there isn't a link to it. So, you can't really click on the report and thus nothing happens. 

Dave 

----- Original Message -----

**Comment by josephr5000** [comment]
Set prio to SHOULD to resolve whether or not this will be done, and how.

**Comment by josephr5000** [comment]
Flagged DISCUSS to cover at next weekly meeting.

I am uncertain if there is really buy-in on having conference members record counts of people helped in three separate buckets (kids, adults, seniors) every time they record an item of help, which would be required for any report like this to generate reasonable statistics.

I would recommend this be POSTPONED to the 2017 round, and revisited then to more specifically identify WHAT reports we need and WHY so we can design and justify the data collection needed.

**Comment by josephr5000** [comment]
Closing as there's been no movement on this, and no-one is (yet) asking for this data.
