### ISSUE TITLE
SFH Report Part B

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#180]
I passed this report but have a comment:
There is a slight difference in that the old DB has the years in numerical order oldest to newest. The new DB has 2016 years first. I like the old DB better.

**Comment by josephr5000** [comment]
Repro'd.  New order is really out-of-order.

**Comment by josephr5000** [comment]
FIXED.

The MDB database coincidentally provided results in order.  SQL required an explicit ORDER BY clause to guarantee results in the desired Year/Month ordering.

Please close this if/when you confirm that it's fixed.  Thanks.

**Comment by josephr5000** [comment]
@DaveSherwood any progress on confirming this fix?

**Comment by DaveSherwood** [comment]
I have retested and confirmed that the order is correct now.
