### ISSUE TITLE
Intake: Quantity of Requests Accepted - minimal data validation

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#181]
Suggest testing the clients per month starting on day field to be <=31. It accepts 60.
Very little testing of valid data input.

**Comment by josephr5000** [comment]
Repro'd issue on line 1.  Not sure what the second line above means.

**Comment by DaveSherwood** [comment]
The second line was just a general observation. Nothing specific. 

----- Original Message -----

**Comment by josephr5000** [comment]
Set prio=should.  Quotas will not behave as expected with unreasonable numeric data input.

**Comment by josephr5000** [comment]
FIXED.  If you choose monthly quota it will ensure day number in range (1,31).  If you choose another quota type it doesn't worry about the day number since it doesn't apply.
