### ISSUE TITLE
Administrative Pages REPORTS Who has logged into the site recently

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#182]
This report is missing from the new DB App.

**Comment by josephr5000** [comment]
Related to #183, but this query is relatively cheaper to rebuild.  Can do pre-launch, however am setting low priority.  Comment if you would prefer it be bumped up in prio.  Thanks.

**Comment by josephr5000** [comment]
FIXED.  Finally bubbled up in the prio list :-)

Check it out on the LIVE site.

**Comment by DaveSherwood** [comment]
I have tested the report and it is working now. I can't remember if this is how it worked before. I now shows the last time each person in our Conference, even those who haven't been members for years, have logged in. Seems like you might want to show this report over a particular time span.
