### ISSUE TITLE
Administrative Pages REPORTS How has our response time been

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#183]
This report is missing from the new DB App.

**Comment by josephr5000** [comment]
The underlying SQL for this is not available from the MDB so the report will have to be rebuilt.

I'm operating on the assumption that it's very seldom used, and so this could be postponed to a post-launch task.

Is that a fair assumption?  Or not?  Please advise.

**Comment by josephr5000** [comment]
Set prio=like so this gets fixed before launch if time permits

**Comment by DaveSherwood** [comment]
I personally would not use this report unless we had an issue or someone was complaining about our response time. Perhaps Stephanie or Tom use it. As far as I am concerned, it could be postponed.
