### ISSUE TITLE
Call Center - Testing Login Restrictions - HELP NOW, they work.

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#187]
Joesph,
Wanted to test login restrictions. Set mine not to allow access on Monday. That works just great but now I can't get back on. Could you please reset for me. Won't make that mistake again.

**Comment by josephr5000** [comment]
At first I got a really good laugh from your note, so thanks for that!  :-)

However on going in to fix it I'm a bit confused.  I see this:

![image](https://cloud.githubusercontent.com/assets/8585358/18856810/17cd6dc4-8413-11e6-9eb1-79bdfd47fa8c.png)


That green selection says you should be able to log in ANY day ANY time.  Am I looking at the wrong account?  In your note above you weren't specific about username/conference so I had to guess.

**Comment by drodruck** [comment]
He had me change his restriction so he could log in.

**Comment by josephr5000** [comment]
Oh.  Someone could have closed this and saved me the time!

**Comment by drodruck** [comment]
But you got the laugh instead.
