### ISSUE TITLE
Trying to view documents in the document library produces XML error message.

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#189]
ENVIRONMENT
Windows 10 Pro, Chrome
ISSUE
Viewing documents
WHAT PAGE
Document Library 
WHAT STEPS WHERE TAKEN
Tried to view documents
WHAT I EXPECTED
The document clicked on
WHAT HAPPENED
Got the error message below.  Possibly the documents were not moved over?
Screen Shots
![image](https://cloud.githubusercontent.com/assets/20655031/18854241/e2b57fb4-83fe-11e6-9291-d0fc728012f1.png)

**Comment by josephr5000** [comment]
*Which* document did you click on?  Thanks.

**Comment by drodruck** [comment]
All of them.  PDF's and Doc's.

**Comment by josephr5000** [comment]
Repro'd. Added to Next Up and set priority.

**Comment by josephr5000** [comment]
It's because I didn't re-upload all your files after I refreshed the DB, so the index in the DB doesn't have the right ID for where files are actually located on Azure.  Currently chugging through a massive upload, struggling to digest OLG's excessively large SVDP Manual chapters.

**Comment by drodruck** [comment]
I can delete the largest one if you want.

**Comment by josephr5000** [comment]
Nah, it's fine, but thanks.  Will just take a while.  It's a good stress test.

**Comment by josephr5000** [comment]
FIXED

File upload complete.  I took files as they existed yesterday, 9/30/16.  If there are files in the DB index (dated 9/23/16) that you deleted before 9/30 then they will fail to download, but all others should be just fine.

Please also test file upload as well, just to be sure.

Close if/when you agree this is fixed.

**Comment by drodruck** [comment]
Everything there, except the one file in "MPQ SVDP Unapproved MEETING MINUTES" subdirectory.

**Comment by josephr5000** [comment]
Just looked at the live site to find what you meant.  Looks like the 9/11 draft?  If so, it's not here because it isn't on the live site either.  Click on the link and you get an error.  Not sure what happened when you uploaded it, but that step didn't succeed...  Could you please re-try uploading to both live and test sites and see if the error is reproducible or if it now works fine?

**Comment by josephr5000** [comment]
Okay, configuration adjusted, would you please try it again?  Thanks.

**Comment by drodruck** [comment]
I was able to upload the file successfully.  In trying to delete the old "entry" got the above Internal Server Error.  Not sure this absolutely essential but it would be nice to clean things up.

**Comment by josephr5000** [comment]
FIXED. 

The file was in the index but had never been successfully uploaded.  The delete operation panicked when it wasn't able to erase the file from Azure storage.  I modified the delete operation to no longer panic about that.  As long as the file can be removed from the index, it will be gone as far as the user is concerned, which counts as success.
