### ISSUE TITLE
Unable to open Call Center Helpline Settings

### ISSUE THREAD

**Issue by jln522** [josephr5000/confdb-public#190]
![image](https://cloud.githubusercontent.com/assets/15675689/18883485/3f9f162e-8498-11e6-9035-275db20a9a5b.png)

**Comment by josephr5000** [comment]
Repro'd.  Added to backlog.

**Comment by josephr5000** [comment]
FIXED

**Comment by josephr5000** [comment]
Trying out something new.  Would *you* please close this when you agree it's fixed?  Thanks.

**Comment by TomOwens5000** [comment]
This is Tom. Jim's issue was the same as mine.
Your answered my question so this no longer needs to be open so I am closing it.
