### ISSUE TITLE
Conference not notified when a note is added to a request by the Call Center

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#192]
I have re-re-retested this. When in the Call Center and I add a request to an existing open client record, a notification is sent to the Conference User who is receiving notifications.

When I add a new note to an existing request, no notification is created. Please reference bug #176 which was closed because it needed more clarity. This is still not working. NOPE, not working.

**Comment by josephr5000** [comment]
Does the screen you get after pressing DONE say it successfully sent notification, or that it failed?

**Comment by DaveSherwood** [comment]
The screen says: No notification was sent since there was no new (no new requests, no new notes) since the last notification. 

So it doesn't think anything has changed but in fact a new note was added. When I add a new request the notification worked correctly. 

----- Original Message -----

**Comment by josephr5000** [comment]
Repro'd. Added to Next Up, and set priority.

**Comment by josephr5000** [comment]
FIXED

Nice catch!  Due to the way I was setting the "high-water-mark" tracking the latest activity that *had* been communicated, there was a short approx 1min window where you could add fresh activity that wouldn't get noticed.

Please test it out and close if/when you agree it's fixed.  Thanks.

**Comment by josephr5000** [comment]
@DaveSherwood any progress on confirming this fix?

**Comment by DaveSherwood** [comment]
Joseph, I tested this and it worked correctly. I received two notifications about the change. Also the notice in the Call Center says "Notification was sent to at Holy Rosary". That is sort of bad wording.  But, the original bug issue appears to be fixed. Should I close it?

**Comment by josephr5000** [comment]
Not yet, what you're seeing begs for a little more investigation.  When you write "the Call Center says" I assume you're talking about the confirmation that appears on-screen after you (CC user) press the Done button?  If so, sounds like there should be something between "to" and "at" like a username.

Can you check the first/last name settings of the designated intaker in your conference?  Are these blank?

**Comment by josephr5000** [comment]
No news in over a year.  Closing.
