### ISSUE TITLE
Call Center - assigning staff member/volunteer an account accepts bogus characters

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#193]
The first and last name field and username field all accept invalid characters (numbers, symbols and decimals). There is NO ERROR CHECKING.

In checking this I created a new member whose name, etc. make no sense. How does one delete such an entry?

**Comment by josephr5000** [comment]
What error checking would you expect?

**Comment by TomOwens5000** [comment]
A pop up dialog box stating that numbers, symbols and decimals are not allowed - or something to that effect. Also, you did not answer my question (above) about how to delete new member entries that make no sense.

**Comment by TomOwens5000** [comment]
Retested today. Gave if a FAIL for lack of error testing mentioned above. However, this will NOT prevent us from going live.

**Comment by josephr5000** [comment]
Why limit characters people can use in usernames?  Freedom of choice, unless it causes problems, has been my motto...

Re deleting an entry, not sure how this would differ from deleting a client under any other circumstances so I guess I don't understand your question.

**Comment by TomOwens5000** [comment]
My desire to delete entries that are incorrect can be handled by hiding them. So closing this issue if fine with me.
