### ISSUE TITLE
Call Center - assigning staff member/volunteer an account accepts bogus email chacters

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#194]
The email field accepts invalid characters (numbers, symbols and decimals). There is NO ERROR CHECKING.

**Comment by josephr5000** [comment]
I agree.  Should be validated since the system later relies on what you enter here.  Added to backlog.

**Comment by josephr5000** [comment]
Prioritized.  As we depend increasingly on emails, this validation must be in place.

**Comment by josephr5000** [comment]
NOTE: also ensure emails are validated on the email campaign screen!

**Comment by josephr5000** [comment]
FIXED.  Over to you to verify, and close if you agree.

**Comment by TomOwens5000** [comment]
Error checking works fine!
But there is a problem. We talked about "Prevent this page from creating additional dialogs" coming up. You said it was the browser (Firefox for me) doing this, not the database program. See screen shot below.
![capture](https://cloud.githubusercontent.com/assets/20777996/19024403/c69d8e1c-88b7-11e6-9c2b-f24b25b18950.PNG)
You told me to click on the message and see what happens. When I click on it and say OK the current page no longer shows your error checking routine. Problem arises when going right back in and changing the email to another invalid entry - and NO pop-up error message appears as it should. Don't know what to do about this, if anything. If you can't prevent this from happening people need to know NOT to check that box.

**Comment by josephr5000** [comment]
Agree that would be nice to fix.  Opened #221 to focus on that, and free us up to close this one if the original issue is now fixed.

**Comment by TomOwens5000** [comment]
Original issue fixed.
Closing this with understanding the second issue above (The browser's offer to not show any more dialogs prevents display of any subsequent validation errors.) will be addressed as SHOULD classification in #221.
