### ISSUE TITLE
Call Center - new member account, what if leave Age and Ethnicity fields blank?

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#199]
I reported the Age issue before. That has been fixed. The Ethnicity issue has also been fixed. They both nowpop up appropriate boxes requesting the required information.

QUESTION. When the Ethnicity box appears it has a check box that says:
Prevent this page from creating additional dialogs?

Please explain what checking that box does!

**Comment by josephr5000** [comment]
That's your browser doing that, not me.  Try clicking it and see what happens.  It says it will prevent future dialogs, suggesting you could continue to fail to enter it but not get an error message.  Is that what happens?  Try it and find out.

**Comment by josephr5000** [comment]
Closing since you asked a question and I answered above.
