### ISSUE TITLE
Call Center - Age Groups Served ... no link present.

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#201]
Is this a report that is yet to be programmed (hence no link) or a bug?

**Comment by josephr5000** [comment]
Not yet implemented.  I'm uncertain we have agreement to make conferences enter three groups child/adult/senior in place of the current two child/adult, so I did not move forward on this.  I would propose we postpone this for now, but am open to discussion on the point.

**Comment by josephr5000** [comment]
PS: if we agree to postpone, I'd remove the link.  Obviously having a title that does nothing is bad!

**Comment by TomOwens5000** [comment]
This might be what Bob Rohrback was getting at when he asked if there would be a report showing clients ages 65 and above. Not sure if that is correct or not. He also wanted some other report.
Agree that if not link is to be present you should remove, at least for now, "Age Groups Served".

**Comment by TomOwens5000** [comment]
You can postpone and remove the link as far as I am concerned.
If that is what you do, please let me know and I will close this one.

**Comment by josephr5000** [comment]
DONE!  Link is gone.

**Comment by TomOwens5000** [comment]
Thanks. Closing this one.
