### ISSUE TITLE
Call Center - enter only numbers (or decimals and symbols) in Address field and click on Lookup

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#203]
Shows an invalid map in most cases.
Does NOT invoke a pop-up Failure Notice box.

**Comment by josephr5000** [comment]
You didn't mention which screen you did this from so I tried from Browse/Find Clients, the first place you see a map option.  I entered 123232333 as the address and clicked MAP.  I got a map and a popup saying ZERO_RESULTS.  Seems reasonable to me.  If you're seeing something different, can you give me more specifics like exactly what address you tried and what you mean when you say "invalid map"?  A screenshot might help.

**Comment by TomOwens5000** [comment]
By "invalid map" I simply meant that what was displayed was not what I expected.

I logged into the CC site as a User. Ergo, the "Browse Client Files" screen was invoked. Yes that is the first place you see a map option. I entered 123232333 as the address and clicked MAP. I got a map and popup saying ZERO_RESULTS. See screen shot immediately below. (What one sees depends on what number gets entered into the address field, as can be seen on the screen shot below the first one.)

I guess if none of the conferences were displayed and ONLY the Error: ZERO_RESULTS could be seen on the screen it would make more sense to me. Why? Because an inexperienced user would not wonder if one of the displayed conferences is actually the location of 123232333 and something is just not being mapped correctly. ZERO_RESULTS suggests to me that no conferences have been located. The screen DOES display conferences. it just doesn't identify a correct one (which makes sense when the address does not match an existing King County conference).

I logged into the CC site as a User. Ergo, the "Browse Client Files" screen was invoked. Yes that is the first place you see a map option. I entered 123232333 as the address and clicked MAP. I got a map and popup saying ZERO_RESULTS. See screen shot immediately below. (What one sees depends on what number gets entered into the address field, as can be seen on the screen shot below the first one.)

I guess if none of the conferences were displayed and ONLY the Error: ZERO_RESULTS could be seen on the screen it would make more sense to me. Why? Because an inexperienced user would not wonder if one of the displayed conferences is actually the location of 123232333 and something is just not being mapped correctly. ZERO_RESULTS suggests to me that no conferences have been located. The screen DOES display conferences. it just doesn't identify a correct one (which makes sense when the address does not match an existing King County conference).

Now try entering 6790 as the address. You will see the screen shot below. To me a message similar to that which says something like "6790 does not appear to be in any King County parish boundary" would be more useful. That is more like what I was expecting to see in all cases where a valid conference cannot be identified and displayed.
An even better solution would be to show a blank screen with "6790 does not appear to be in any King County parish boundary" or something to that effect for the address number in question.

![capture](https://cloud.githubusercontent.com/assets/20777996/19005608/59dca284-8710-11e6-9ee4-1b1692a22273.PNG)

An even better solution would be to show a blank screen with "6790 does not appear to be in any King County parish boundary" or something to that effect for the address number in question.

**Comment by josephr5000** [comment]
Considering that CC users are the ones using mapping, and this is the *identical* map they use today, I think we can go live with the current error behavior where it is pretty clear that it didn't find whatever address you were looking for.

I'm voting POSTPONE on this.

**Comment by TomOwens5000** [comment]
I would suggest a LIKE prioritization.

**Comment by TomOwens5000** [comment]
POSTPONED
