### ISSUE TITLE
Question - Call Center - misasigned conference name

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#204]
How does one correct the conference name in a client file if it has been misassigned to start with?

**Comment by josephr5000** [comment]
You create a new file in the conference you intended.

The current system doesn't allow *moving* files between conferences.

**Comment by TomOwens5000** [comment]
Talking ONLY about the Call Center. Since it CANNOT delete anything, how does one get rid of a Client File that inadvertently got created with the wrong conference?

From what you said, I understand that it is required to reenter everything from scratch and not make the same mistake of selecting the wrong conference. BUT ... now the Call Center has a Client File that is WRONG with no ability to delete it from their records. Is that what we want?

**Comment by josephr5000** [comment]
Easy way: add a comment saying to the conference "oops, assigned in error, please ignore or delete".

Harder way: please suggest what factors should distinguish client files we'd allow the CC to delete vs ones we'd not.  Sounds like a nice enhancement request to me, but not something we put in the spec for this round.

**Comment by TomOwens5000** [comment]
Suggest LIKE classification for this one.

**Comment by josephr5000** [comment]
This is basically the same as #205 which you already said "for next time", so this one joins it in POSTPONE.

**Comment by josephr5000** [comment]
Let's work with this one as it has more context.  Will close #205 as a duplicate.

**Comment by josephr5000** [comment]
I can live with LIKE.
