### ISSUE TITLE
Email Confirmation Campaign - Tom Owens at Call Center not working

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#206]
Try as I may "Send me a verification email now!" Does NOT do so! So EVERY TIME I log on I get the request all over again. Have no idea why this is happening. I did see a message at one time days ago the indicated I was not a member. WORKS FINE AT CONFERENCE SITE.

Any help to get this to work right would be appreciated.

**Comment by josephr5000** [comment]
What email address are you entering?  And can you let me know approx date/time you last tried this so I can check server email logs?  Thanks.

**Comment by TomOwens5000** [comment]
Tried again several times this morning (Friday 9/30/16) at around 8 am, plus or minus a few minutes. Here are the steps I took.
1.	Blanked out email address on CC site
2.	Logged off CC site
3.	Logged back on CC site
4.	Email Confirmation Campaign message appeared
5.	Clicked on Send me a verification now
6.	Email sent screen appeared
7.	Clicked on Continue
8.	Was immediately logged into CC site
9.	My email field on CC site was still blank

Tried to verify the email from the My Profile screen with the same result.

I never received the email send message or an email link
During one attempt at this I got “Error: no such member” message

**Comment by TomOwens5000** [comment]
CC Site
Tried several times again on 9/30/16 between 8 am and 8:30 am.
1.	Blanked out email address field (nothing in it now)
2.	Logged off CC site
3.	Logged back on CC site
4.	Email Confirmation Campaign message appeared
5.	Clicked on Send me a verification now message
6.	Email sent screen appeared
7.	Clicked on Continue
8.	Was immediately logged into CC site
9.	Never did receive the Email Sent message or an email with the link
10.	The email field was then had my email address in it (I did not put it there)
11.	Clicked on Verify Now 
12.	Email send message appeared
13.	Clicked on Continue
14.	Was immediately logged into CC site again
Was always able to get the Email sent box
Was never able to get the Email Verification Request with the link
Was never able to invoke the missing link
Was never able to receive the Email Verifications Succeeded screen
Number 10 above … why did my email address get put back into the email field? I had left it blank.
At one point I got the following message (not sure what I did to get it):
Error: no such member

**Comment by josephr5000** [comment]
The email log shows numerous (more than 10) emails delivered between 8am-9am today to exk7rsc@yahoo.com.  Assuming that's your correct email address (no typo) then I would suggest you look in your SPAM folder.  At any rate, verification messages are being *sent* just fine, so the problem appears to be on your receiving end.  If you have repeated emails sent to you from the same address within such a short span of time there's a good chance Yahoo will start to get suspicious and think it may be spam.  Please check.

FYI I'm not able to repro this myself using my email address.

**Comment by TomOwens5000** [comment]
I HAVE NO IDEA HOW TO GET THIS WORKING.
GO AHEAD AND CLOSE IT AGAIN.
I WILL NOT REOPEN IT!

NOR WILL I ATTEMPT FURTHER TESTING UNTIL THIS ISSUE SOMEHOW FIXES ITSELF.
THAT WILL NOT BECAUSE OF ANY FUTHER ATTEMPTS OR CHECKING ON MY PART.
SORRY I AM NOT SMART ENOUGH TO FIGURE IT OUT.  IT IS TOO FRUSTRATING.

FURTHERMORE ... THOUGHT OUR CHARGE WAS TO FIND EVERYTHING POSSIBLEUNDER THE SUN  A USER MIGHT STUMBLE ON. RANGING FROM SOMEONE TOTALLY UNFAMILIAR WITH THE SOFTWARE TO AN EXTREMELY COMPETENT USER AND EVERYONE INBETWEEN. MAYBE I MISUNDESTOOD. IN ANY CASE, THAT IS WHY I HAVE BEEN SO PICKEY, REPORTING ISSUES THAT APPEAR TO CREATE FRUSTRATION FOR OTHERS.

THAT BEING SAID, IF ANYONE IS INTERESTED THEY CAN LOOK AT THE TOM TAB ON THE TEST PLAN (BY DOUG). IT IS NOWHERE FINISHED AND IS LIKELY TO STAY THAT WAY.
