### ISSUE TITLE
Conference Site - Failiure message on confirm email

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#207]
Logged in to Conference site.
Got rid of email to test to see if still working.
Blank email field.
Clicked Save Change.
Logged Off.
Logged back in.
Did not receive email verification screen.
Checked my Profile. My email address was there and shown as verified.
Deleted email again.
Clicked Saved Change.
Got the following error message:

error '80020009'

Exception occurred.

/confdb/DoRecordSave.asp, line 188 

Note: *NEITHER* THE CALL CENTER OR CONFERENCE SITES WILL WORK PROPERLY FOR ME AS FAR AS THE EMAIL VERIFICATION IS CONCERNED.

**Comment by josephr5000** [comment]
Not able to repro.  Could you give me a few more details:
- What browser were you using?  Does it repro with other browsers?
- What conf/cc were you logging into?  Does it also repro with other conf/cc?

Thanks.

**Comment by TomOwens5000** [comment]
THIS FAILURE IS PRECLUDING ME FROM SERVERAL TESTS I NEED TO MAKE!
Using Mozilla Firefox.
Logging into OLG Conference. Also fails logging into King County Call Center.
Without legitimate passwords how could I log on to other conferences or call centers?

**Comment by TomOwens5000** [comment]
Got Conference site to now work properly for accepting email but Call Center still does NOT work!
I had renamed OL Guadalupe to _Guadalupe to make it be at the top of the Conference drop down list. Changed it back to OL Guadalupe and that appears to be the reason if failed. Working there now.

**Comment by josephr5000** [comment]
I see you just closed this an hour ago without comment.  FYI I'm still unable to reproduce this using Firefox on my conference or on the call center.

**Comment by TomOwens5000** [comment]
I think the only way we are going to get this fixed is to have you take 
control of my computer with ZOOM and see if you can figure out what is 
going on. That would be much appreciated as this is preventing me from 
making test I am responsible for making.

Tom

**Comment by josephr5000** [comment]
That would be fine by me.  Let me know when you'd like to proceed.

**Comment by TomOwens5000** [comment]
Closing.
