### ISSUE TITLE
Call Center - Help text for Age Group and Ethnicity not applicable for Call Center + "typo"

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#209]
Is this help screen even applicable to the Call Center? I think not, but could be wrong.
In any case, "Membership Summary" is NOT shown on the Main Page which leads me to believe this "Membership Summary" report is ONLY applicable for conferences (not our Call Center). If I am correct, the _help_ boxes should be eliminated for "Age group" and "Ethnicity" but remain operational for Birthday.  

![capture](https://cloud.githubusercontent.com/assets/20777996/18977846/cd807286-8672-11e6-8f14-863bc181d696.PNG)
For "typo" see comment below.
Paragraph two, line one ... "how we're doing on _get_ closer" ...
Suggest "get" be replaced with "getting".

**Comment by josephr5000** [comment]
Added to backlog.  Set low priority.
