### ISSUE TITLE
Call Center - Password and Confirm Password field issue

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#210]
What if leave "Password" and "Confirm Password" blank? Does it fail gracefully? Does not fail gracefully. No error checking. Need pop-up dialog box stating password and confirm password fields must be filled in correctly. Otherwise that person will NOT be able to log into the site.
This one should prevent us from going live.

**Comment by josephr5000** [comment]
The password field specifically instructs you to "leave blank to prevent login".  Leaving it blank is a legitimate option, and not necessarily an error.

Should the system advise you of the consequences of leaving it blank?  Perhaps, but in over 10 years not a single person has complained that this is a real problem.  Have you ever personally experienced this to be a problem?  I seriously doubt this should prevent us going live.  I'd go as far as to vote a clear POSTPONE on this.

Feel free to tag for discussion if you disagree and want the team to discuss it on Thursday.
