### ISSUE TITLE
Call Center - Member Status - contains several non-applicable choices

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#211]
*Choices are:*
active
associate
contributor
clergy
inquirer
staff
inactive
special
*Choices should be:*
active
inactive
*Do you want to determine*
staff member
volunteer

Leaving things the way they are does not preclude us from going live.
However, this is an observation I made. Maybe something to consider WAY down the road.

**Comment by josephr5000** [comment]
Thanks for the invitation to postpone.  Happy to oblige!
