### ISSUE TITLE
Call Center - Online Status - contains two non-applicable choices

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#212]
"Read only" and  "None" are not applicable.

Leaving things the way they are does not preclude us from going live.
However, this is an observation I made. Maybe something to consider WAY down the road.

**Comment by josephr5000** [comment]
ReadOnly is questionnable.  Not so sure None is inapplicable.

Regardless, I'm happy to accept your invitation to postpone, and we can have that discussion another day.
