### ISSUE TITLE
Call Center - at www.confdb.org/confdb - list of conferences does NOT include the King County Call Center

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#216]
The Call Center is missing from the list of conferences. That precludes logging in as either a User or Administrator.

**Comment by josephr5000** [comment]
Why should it show on the current product?  BY DESIGN.  The *new* site's key feature is to *add* the call center *precisely because* it isn't available on the current product.

Am I missing something here?

**Comment by TomOwens5000** [comment]
Here is the spec on the Tom tab per Doug: 
*Call center users log in at the usual www.confdb.org/confdb location*
Maybe we BOTH are missing something here.

*IF* CALL CENTER USERS/ADMINISTATORS ARE TO LOG IN PER THE ABOVE SPEC WHEN THE BETA SITE GOES LIVE, THEN I THINK THE KING COUNTY CALL CENTER *WILL* NEED TO BE ADDED AS A CONFERENCE ON THE DROP DOWN BOX THAT LISTS THE CONFERENCES (SINCE KKCC IS TO BECOME A "CONFERENCE". IS THIS NOT CORRECT?  I THINK THAT MAY BE WHY DOUG IS HAVING ME TEST IT AT THIS URL.

In any case, I wondered why there was a need to test it at this URL too. But I did what was asked of me and my original comment above is a result of that test. Maybe Doug typed in the wrong URL. Maybe not. I don't know.

LET ME KNOW WHAT YOU WANT ME TO DO WITH THIS! CLOSE IT AS BY DESIGN OR LEAVE IT OPEN. PLEASE PROVIDE ADDITIONAL CLARIFICATION DISCUSS IT FUTHER.

**Comment by josephr5000** [comment]
Oh, it will be at that URL when we go live.  Until then, please just confirm that it's working at the test site.  Thanks.

**Comment by TomOwens5000** [comment]
Yes, it working at the CC site.
