### ISSUE TITLE
Who can edit Notes and when?  Reconsider the design

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#217]
Various bugs that have been opened indicate that testers are finding it confusing and frustrating to know when notes are editable and why.

This is an issue to flag that we should reconsider this design and see if it can be made simpler and clearer.

No definite answers yet on _how_ the design should change.  That's why it needs more thought!

I'm tagging this reconsideration as must-do priority.

FYI @drodruck @TomOwens5000

**Comment by josephr5000** [comment]
Long phone discussion with Tom, and agreed on the following changes:

[ ] Make "Edit | Delete" links on notes blue so they're not so obscure. His initial usability testing with his confernce members suggested they misunderstood yellow to be greyed.
[ ] Make "Add Note | Close Request" links **bold** so they stand out as the more desirable links to use
[ ] Make conference notes on OPEN requests editable by ANY conference member, but NOT by CC users/admins
[ ] Make conference notes on CLOSED requests editable by the members tagged on the request plus administrators, with no time limit on making edits.
[ ] Call center users can ONLY edit notes left by other call center users, and then only on OPEN notes.
[ ] Call center users can NEVER edit notes on CLOSED requests and can NEVER edit notes left by conference members.

**Comment by TomOwens5000** [comment]
Closing this as acceptable to me.
Tom

**Comment by TomOwens5000** [comment]
Sorry about that.
I should be open until implemented and confirmed operational.
Tom

**Comment by josephr5000** [comment]
Forgot one case above that we discussed:
- [ ] Conf users can't edit CC notes. They should just add an add'l note if they need to correct erroneous info.
- [ ] Conf admins *can* edit CC notes because conf admins can do anything :-)

**Comment by josephr5000** [comment]
FIXED.

Here's what I implemented.  You can compare to the language above, and definitely please test to be sure it works as advertised!  Let me know if you find any holes.

OPEN CASES.  User may ONLY edit if they meet one of these criteria:
-- I'm a CC user/admin AND note was written by any CC user/admin 
-- I'm a conf user AND note was written by any conf user
-- I'm a conf admin, regardless who wrote the note, because conf admins can do anything.

CLOSED CASES.  User may ONLY edit if they meet one of these criteria:
-- I'm a conf user AND I'm tagged on the case AND note authored by someone in my conf.
-- I'm a conf admin, regardless who wrote the note, because conf admins can do anything.

CLOSED CASES.  User may NOT edit if:
-- I'm a CC user/admin because CC users/admins can't even SEE notes on closed cases
-- I'm a conf user but I'm NOT tagged on the case

When I say "tagged" I mean that whoever closed the case selected you as Member1, Member2 or Member3.

Enjoy!

**Comment by TomOwens5000** [comment]
Tested all the cases above. Agreed, FIXED.
**But I am NOT closing yet as the following have not yet been implemented.**

Make "Edit | Delete" links on notes blue so they're not so obscure. His initial usability testing with his confernce members suggested they misunderstood yellow to be greyed.

 Make "Add Note | Close Request" links bold so they stand out as the more desirable links to use

On another unrelated note ...

"Nice Catch!" on *your* part, Joseph.
I thought about this late last night and was going to post a case number for it today.
Happily surprised to see you must have already known about it - -- and have already fixed it.
Before, everything under the GOODS - BUS TICKETS was tabbed too far to the right, just beyond the S in TICKETS.

![capture](https://cloud.githubusercontent.com/assets/20777996/19398186/42ffb556-9200-11e6-8cf0-5ff08da2f621.PNG)

**Comment by josephr5000** [comment]
I opened #265 on the formatting issue (and fixed it, by the way), so you can close this and that one when you're ready :-)

**Comment by TomOwens5000** [comment]
Maybe I spoke too soon.
The screen version above shows the proper tab distance.
The print out of the Client File still is tabbed too far to the right.
Here is a screen shot of a scan of a printout I made for another Client File.
It is even further to the right. Guess code for the printing did not get fixed.

![capture](https://cloud.githubusercontent.com/assets/20777996/19398675/97b5bb8e-9202-11e6-9ea4-a6fa8df183ad.PNG)

**Comment by josephr5000** [comment]
Opened separate item #266 on the indenting which isn't related to who can EDIT notes which is the subject of this issue.
