### ISSUE TITLE
Enhancement Request - on logging on check to see if CAPS LOCK is invoked

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#219]
If Caps Lock is engaged, pop up a message to that effect.
Not a high priority but would be nice to let people know why the login failed due to Caps Lock turned on.

**Comment by josephr5000** [comment]
Most keyboards have a light indicating that CAPS LOCK is on.  Not worth investing time duplicating this in software, in my opinion.  Definitely not for this project round, and perhaps never.

**Comment by TomOwens5000** [comment]
I don't look at the keyboard. I look at the sign-on screen. Therefore, I do NOT see the Caps Lock light on the keyboard. Not sure what everyone else looks at but think it more likely the look at the screen.
In any case, I never felt it important to implement this of necessity. Have no problem postponing it until whatever we do in 2017 but prefer it be added when you are bored.
