### ISSUE TITLE
Validation error boxes shouldn't use browser alert() b/c user can say don't show any more

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#221]
Raised in #194 but opening a separate bug to focus on this.

![image](https://cloud.githubusercontent.com/assets/8585358/19026239/261bcb7c-88d8-11e6-967c-c2dc65994e2b.png)

The browser's offer to not show any more dialogs prevents display of any subsequent validation errors.  Not helpful.

Adding to the SHOULD FIX list.

**Comment by josephr5000** [comment]
FIXED

**Comment by drodruck** [comment]
Confirmed fixed.
