### ISSUE TITLE
Bug: Can't delete client file from Browse/Find Clients

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#222]
TO REPRO
- Log into St James/Bl Rosalie
- Browse/Find
- Look for Last, First. Find one match.
- Press red X to delete. Type in clientid as requested.  Press OK.

RESULT
![image](https://cloud.githubusercontent.com/assets/8585358/19027004/30841106-88e1-11e6-95e0-38039ba77487.png)

EXPECT
Success.

**Comment by josephr5000** [comment]
Repro'd on Chrome and Firefox.  Not repro on local PC against local SQL Server.  Consistently repro on Azure TEST and Azure SQL.

**Comment by josephr5000** [comment]
FIXED.

The issue here was that delete failed because the client had assistanceitems which would have been orphaned by deleting the client record.  We could delete those but if they've been paid, or if they conveyed important info (like an outstanding unpaid rent pledge) then automatically deleting them would be bad.

NEW BEHAVIOR: if client-to-be-deleted has any assistance items (whether open or historical) delete fails with an error message telling the user to delete those items first before deleting the client.

@drodruck Would you mind testing this fix for me to make sure it works as described?  Thanks!

**Comment by drodruck** [comment]
Confirm, it works.
