### ISSUE TITLE
Drill down on Clients Turned Away by Conf gives Internal Server Error

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#224]
TO REPRO
- Log into CC as admin
- Click "Clients Turned Away by Conf"
- Choose Last FY so you have some data
- Click number next to St James to drill down

RESULT
- Page couldn't be displayed because of internal server error

**Comment by josephr5000** [comment]
FIXED.  Over to you, Tom!

**Comment by TomOwens5000** [comment]
Now works as expected.
Closing file now.
