### ISSUE TITLE
Unable to see ID box and buttons in delete dialog box

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#225]
ENVIRONMENT
Windows 10 Pro, Chrome and Firefox
ISSUE
Cannot see all of dialog box
WHAT PAGE
Deleting from conference Browse/Find Clients 
WHAT STEPS WHERE TAKEN
Clicked the red “X” to delete the client
WHAT I EXPECTED
To be able to see all of dialog box
WHAT HAPPENED
When the zoom in Chrome and Firefox is set above +110, cannot see all of dialog box and cannot move the box up to see the ID field or the buttons.  This does not happen in Edge and IE (annoying).
Screen Shots
![image](https://cloud.githubusercontent.com/assets/20655031/19027651/302d8b32-88e7-11e6-971b-5a63b9e265cb.png)

**Comment by josephr5000** [comment]
Odd...I'm not able to repro on Firefox until I get to 200% which is pretty ridiculously large, and on Chrome I have to go to 250%.  I think there's another variable at play here.  What is your screen size (pixels)?  What device are you using (pc? tablet? phone?)

**Comment by drodruck** [comment]
My display setting (laptop) was set at 175% (not sure why). Reset it to 125% and do not have the problem.  I suppose this is something we should watch for when the "public" begins to use the program.
