### ISSUE TITLE
Test Plan Assignments For Tom Owens - 2.1 Configuration

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#226]
I am not sure how to test the following.

If someone can test these 2 cases for me it would be appreciated. If not, I need DETAILED step-by-step WRITTEN instructions on how to do so.

*The Call Center will have access to client profiles and assistance records for all conferences in the district, but not for conferences outside its district*

 The view would only be of seattle council clients, no california, tacoma or anyone else

*The Call Center will have no access to Conference members or financial records, uploaded files, or reports*	

Only thing you would see is the client file for the client in question and nothing else, no Conference financial records, uploaded files or reports

I've been responsible for and done 240 rows of  testing so I don't this is an unfair request.

**Comment by drodruck** [comment]
Now that the city is displayed in the client file I was able to review all of the Smiths and found no names outside of the King County area for the Call Center so I would say that passed.

In the Call Center screens none of the Conference financial records, uploaded files or reports show so I would say that passed, too.
