### ISSUE TITLE
Improve Email Verification message (changed title)

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#227]
3 tests cannot be performed:
1. Click on Done.
2. Click on Don't show this notice again.
3. Log off and log on again to confirm READ ME message does not reappear.

I think having the Email Confirmation Campaign come up when first logging on now precludes the READ ME message from appearing.

I would assign a MUST classification to this.

**Comment by josephr5000** [comment]
What READ ME message are you referring to?

If you're asking about the notifications you used to get on login, I suspended those for the duration of this campaign since I didn't have any pressing notifications queued up.

**Comment by TomOwens5000** [comment]
Yes. I suspected that you might has suspended those. That answers my question.
So I can eliminate 3 tests failed because they could not be completed.

HOWEVER, CAN YOU PLEASE SEND ME AN IMAGE OF THE READ ME SCREEN. I NEED IT FOR WORK ON OUR CONFERENCE MANUAL.

Thanks in advance. I look forward to receiving an image of the screen that I can put in our manual.

**Comment by TomOwens5000** [comment]
Oh, I forgot.
I assume the intent is to put it back in at some point.
Food for thought: have it appear 1st and then the Email Confirmation Campaign screen.

**Comment by TomOwens5000** [comment]
Reopening so that I don't forget to receive the READ ME image I requested.
Will close after I receive it.

**Comment by josephr5000** [comment]
You can make one yourself.  Go to the current live site, add a new conference member, and log in as them.  You'll get the initial message.  You can then set that user's status to inactive.  I don't have any shortcut to create this for you...those are exactly the steps I'd have to do.

**Comment by TomOwens5000** [comment]
Thought you were not going to close stuff, instead having the person you assign something to responsible for closing. Noticed this a number of times now. Has the policy changed?

Thanks for the instructions. Tested it at your request and found an error. See screen shot below.
![capture_new member notices screen](https://cloud.githubusercontent.com/assets/20777996/19059173/a5c1bdfe-8992-11e6-89a8-ad6613abe0d7.PNG)
Test in the box says: "You can press the CONTINUE or DONE button ..."
There is NO CONTINUE button, only a Done button.
Need to revise text and eliminate CONTINUE or put a CONTINUE button down near the Done button.
My suggestion is to rewrite the text and eliminate the "CONTINUE or".
Let me know when this has been fixed and I will retest it for you. Leaving Open.

**Comment by josephr5000** [comment]
Since this isn't being used now, and may be done a different way in the future, I'm voting for POSTPONE.  Time now needs to be focused on what will impact users in 2016.

Re closing, sorry, misread your note!  I missed the all-important NOT in your question!

Ummmmm. It's a great question. Best answer I can give is that I must have pressed the wrong button. It wasn't my intention to close it!  :-)

FYI since you wrote "leaving open" at the end of your last note but forgot to open it (I guess you pressed the wrong button too?) I'm now re-opening it for you.

**Comment by TomOwens5000** [comment]
Thanks for the reply.
Will close issue now.
HOWEVER, when you decide to visit this again let me know, as I have idea on how this process might best be implemented.

**Comment by josephr5000** [comment]
Why don't you mention that idea here so it's available whenever we do revisit this?

**Comment by TomOwens5000** [comment]
Ok. Here it is. Enjoy.
[#227 Login Sequence When We Go Live.docx](https://github.com/josephr5000/confdb-public/files/509677/227.Login.Sequence.When.We.Go.Live.docx)
Based on your previous suggestions to send stuff directly to the group via email to assure that they see an item I think everyone should see, I have done so.
HIGHLY RECOMMEND WE DISCUSS THIS AT NEXT THURSDAY'S ONLINE MEETING!

**Comment by josephr5000** [comment]
Thanks.  If you want it on the agenda, please ping Tom Wagner.

FYI perhaps I misunderstood your step #5, but it's not possible for me to interrupt login to display the user's inbox at that point in the sequence.  They need to go read and respond to their email, but that is outside my control.  Could you clarify what you're suggesting?  Thanks.

**Comment by TomOwens5000** [comment]
You got it (#5). I would like to see the Email Verification Request box BEFORE the Main Page is displayed. If that is not possible is there some other workaround? See the screenshot below.
![capture](https://cloud.githubusercontent.com/assets/20777996/19108187/9af5634a-8aa4-11e6-9424-aef9b6a59bbe.PNG)
Just food for thought at this point but to me that might suggest a greater sense of urgency.
