### ISSUE TITLE
Call Center - "Helpline Settings" - reported by Jim #190 (Closed) and Tom #202 (Closed)

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#230]
Both of us reported the following: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

Not sure where I was when I discovered this. There is no "Helpline Settings" title on the Main Page. I see it has been prioritized and added to NEXT UP list per Joseph. But I have no recollection of where I was when the message occurred.

Can you please let me know where so I can retest it?

**Comment by josephr5000** [comment]
See #202 and #190.  Closing this one as a duplicate.

**Comment by TomOwens5000** [comment]
There is no "Helpline Settings" title on the Main Page. I see it has been prioritized and added to NEXT UP list per Joseph. But I have no recollection of where I was when the message occurred.

**Can you please let me know where so I can retest it?**

After I get your answer I will close this.

**Comment by josephr5000** [comment]
There aren't any settings, so I removed the link.  That was the fix.

**Comment by TomOwens5000** [comment]
Closing this.
Tom
