### ISSUE TITLE
2.6 Create New Client File - does NOT show date for taking more calls 

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#231]
Spec Says - Conference Status Panel: If open, is there a quota, and what’s the quota status?  If the quota is full, when will it reopen for new calls?

Conference Status: Open and Quota status work as expected.
Does not show a date for taking more calls - is this not implemented yet?

**Comment by josephr5000** [comment]
Please give a more specific scenario where this fails.  Eg: if a conference has unlimited quota, no date is even expected.  Thanks.

**Comment by TomOwens5000** [comment]
Spec Says - Conference Status Panel: If open, is there a quota, and what’s the quota status? [That part works as expected.] **If the quota is full, when will it reopen for new calls?** [This part does NOT work as expected.]

![capture](https://cloud.githubusercontent.com/assets/20777996/19044919/230e8dac-894b-11e6-85df-77d466a30a45.PNG)
From the screen above it can be seen that there is a quota set and it is full.
Where is the message that tells when it will open for new calls?
On the 3 Intake sections on the Conference side there is no mention of when it will reopen for new calls once the quota has been reached. Yes, I know, the Override button can be used but that is not the point.

The Spec clearly says: **If the quota is full, when will it reopen for new calls?** 

One of two things going on here. One, a bug preventing the question from being asked on the Conference side. Or, two, that part of the Spec is wrong.
**Which one is the proper answer?**

**Comment by josephr5000** [comment]
Oh, that's the same message format as the current helpline database.

It's telling you the quota opens every day 1 of the month at 8:00am.  So if it's now full, it will reopen on the next day 1 of the month at 8:00am.  Today that would be Nov 1 at 8:00am (or the nearest helpline working day!).

**Comment by TomOwens5000** [comment]
"Oh, that's the same message format as the current helpline database." Fine, but I have never seen the current helpline database so that explanation is of no value to me.

The Spec clearly says: **If the quota is full, when will it reopen for new calls?**
*One of two things going on here.* One, a bug preventing the question from being asked on the Conference side. (Nothing in the 3 new Intake screens asks when it will reopen for new calls if the quota is full. That is a fact.) Or, two, that part of the Spec is wrong.
**Which one is the proper answer?** You did not answer my question.

You explanation above is fine for you because you know how things work. Call Center volunteers are not going to find it easy when talking to callers to look at the current date and figure out when the nearest helpline working day is going to be. If it is displayed on the Conference Status Panel that will be a much more satisfactory solution for them

**HIGHLY RECOMMEND YOU TALK TO LISA AND GET HER INTAKE ON THIS!**

Whatever the two of you decide is fine with me. I am just point out what I feel is a valid usability issue for users. And, if it is the spec, it should be implemented - or drop it from the spec.

**Comment by josephr5000** [comment]
A statement that something happens every Monday at 8am already tells you when it will happen again.  It's redundant to say "It happens every Monday at 8am, and the next occurrence will be next Monday at 8am".  So this does tell you when the next availability is, which is what the spec requires.

Add to that two additional factors:
* This behavior is IDENTICAL to current helpline DB behavior, and I chose it specifically to minimize changes for the main customers: helpline users.
* The Council is looking to de-emphasize (any hopefully cease) having the Call Center enforce quotas at all.

These all add up to me seeing no need to ask Lisa about it.  If you want to, please go ahead.
