### ISSUE TITLE
Allow leaving Special Program field blank

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#232]
Request by John Morford at today's demo.  Easy to do.

**Comment by josephr5000** [comment]
FIXED.

Doug, would you do me a favor and test this?  Close if/when you like it.  Thanks!

You should be able to do two things:
1) Help without Request, enter all the usual details, but leave Special Program BLANK.  Used to fail validation.  Should now accept a blank entry.
2) Same test, but pressing Close Request after having added a request.

**Comment by drodruck** [comment]
Tested #1, works as expected where leaving Special Program blank is accepted.
Not sure on #2, there is a Cancel button on the Request screen which clears out the data on the screen but doesn't return you to the prior screen.  You can only get back to the prior screen by hitting the back button on the mouse.

**Comment by josephr5000** [comment]
A bit puzzled.  Re item 2, are you talking about this screen:
![image](https://cloud.githubusercontent.com/assets/8585358/19062284/a1af6e6c-89ad-11e6-80a0-953ef7123ea8.png)

I tried pressing CANCEL on Edge, Firefox and Chrome (all on Windows 10) and in each case it returned to the Client File as expected.

**Comment by drodruck** [comment]
Yes, it works.
