### ISSUE TITLE
Types of Help: make it easier to select all

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#233]
From this morning's staff demo:

UI should make it easy for conferences to be generous.

To allow all requests you currently need to click EVERY item.  Very laborious.  Discourages generosity.

Should have a way to make this easy.

**Comment by josephr5000** [comment]
FIXED

A new "[ ] Select All" checkbox is in the list header.  Selecting it toggles between selecting all rows and none.

While I had this open I also made a change to exclude these non-request items from the list since the call center will be focusing on sending actionable requests to conferences.  Excluded are:
- Other
- Not Helped
- Admin - Intake/Assessment
- Intake - Received

@TomOwens5000 could you do me a favor and check/confirm this and close if it works right?

**Comment by TomOwens5000** [comment]
Do NOT display "[ ] Select All". See screen shot below - taken 10/3/16 at ~5:36 pm.
![capture](https://cloud.githubusercontent.com/assets/20777996/19058923/4bc81962-8990-11e6-8462-7a29deef943f.PNG)

**Comment by josephr5000** [comment]
Not following you, Tom.  You can't be saying [ ] Select All doesn't appear, because it's right there in your screenshot at the top of the list.  Are you saying when you click it, it does nothing?  Or...?  Thanks.

**Comment by TomOwens5000** [comment]
I'm not following me either. Must be blinder than I thought. Yes. It is there and it works as expected.
You're going to hate this. Once all have been selected can the "Select All" be changed to "Deselect All"?
Just a suggestion. Living Open until I hear your answer than I will close it.

**Comment by josephr5000** [comment]
I don't hate it.  But I'm not convinced it's significantly clearer than the current text, or sufficiently clearer to justify the (albeit minor) additional complexity.

**Comment by TomOwens5000** [comment]
Disagree. "Deselect all" IS significantly clear than "Select All" when the goal is to deselect all checked items. In any case, I have no problem postponing it (preferably a LIKE classification).
You need to understand that all the "picky" things I bring up are to make the interface with users as seamless as possible.
Closing this item.
