### ISSUE TITLE
Client search results: show DOB

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#234]
From today's staff demo:

Discussion of ways to be more sure that person A is (or is not) the same as person B.

Observation that DOB (along with SSN) can be essential information.

Request that DOB be added to the search results so users can use that information.

**Comment by josephr5000** [comment]
Doug, wondering if you could please confirm and close this?  See description above for what (should have!) changed.  Thanks.

**Comment by drodruck** [comment]
Works in both user and admin.  Did they want the format with the year first as you made it?  I'm not used to the European format.

**Comment by josephr5000** [comment]
Oops, fixed.  Should now show m/d/yyyy format.  Yell if you see yyyy-mm-dd format anywhere else.

**Comment by drodruck** [comment]
Done
