### ISSUE TITLE
Call Center - Types of Help Requested - 2 issues

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#236]
Part 1.
Clicking on "#Requests for a Category displays all Clients served for the Category" selected.
This is what happened. #Requests does not respond.  There is no link. However, typing a number in the search box will bring you to the corresponding category(ries).
Part 2.
Clicking on the Client's name invokes the Client File for the selected Client. Cannot be tested until the above failure is fixed.

Leaving Open until you let me know it has been fixed. Will then test again and close if working as expected.

**Comment by josephr5000** [comment]
Tom, I'm sure this makes sense to you because you've just been thinking about it, but your comment above reads like it starts in the middle of something, and I'm not at all following what you're talking about.

Can you please just give a simple step-by-step on how I would reproduce the problem you see?

**Comment by TomOwens5000** [comment]
**Call Center site**
Click on "Types of Help Requested".
Invokes "Report: Requests by Category" screen.
Set Date range to Last Week and click Refresh.
Numbers in middle of screen not underlined (not links). So clicking on the numbers does nothing.
Typing a number in the search box will bring you to the corresponding category(ries).
But since the numbers are not links it is NOT possible to click on a Client’s name to invoke a Client File.
See Screen below.
![capture](https://cloud.githubusercontent.com/assets/20777996/19068012/92ff4900-89d5-11e6-898b-61483e98d2c8.PNG)
This is essentially the same 2 types of issues discussed in #235.
Let me know when this is fixed and I will retest the 2 issues.
If they pass, I will close this one.

**Comment by josephr5000** [comment]
Thank you.  Would be great if you'd do as a general rule since it makes your reports so much easier to digest.  Applying QUESTION label for me to look into whether I'd intended there to be any drill-down here.

**Comment by TomOwens5000** [comment]
Retested again.  
Same result.  It appears you haven't done anything with it yet.
I am leaving open until I hear more from you.

**Comment by josephr5000** [comment]
Checked spec 3.5, where I'm reminded this was planned to just be a summary report, no detail available if you click through.  For that reason this is currently BY DESIGN.  It might be a nice enhancement, so I tagged this as ENHANCEMENT and recommend POSTPONE.
