### ISSUE TITLE
Call Center - "Browse Client Files" results not sortable

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#237]
Results are not able to be sorted!
Missing up and down arrows for all but Client Name field. Arrow there for that field but it does not work.
Will leave open until you let me know it is fixed. Then I will retest and close if it works as expected.

**Comment by josephr5000** [comment]
Have investigated, and was reminded about why I did not implement this.

To improve query performance you now get paged results so loose criteria that return many results don't take ages to appear.

Paged results make sorting more expensive and complex.  It would be nice to do this sometime, but as the current product has survived a long time without this being sortable I question whether *sorting* (as compared to paging results) is sufficient priority on this round to invest the time/cost.

I would suggest postponing to 2017.   Have labelled DISCUSS so we can address at our weekly chat.

**Comment by TomOwens5000** [comment]
My question for us to discuss is whether we're okay with postponing this to the 2017 project round?
Okay by me.
Tom Owens

**Comment by josephr5000** [comment]
MEETING DECISION: postpone.
