### ISSUE TITLE
Time off by 7 hours

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#239]
When the "Received" button is clicked for a conference not using the confdb, the time of the received message as seen by the CC is off by 7 hours.  The "Received" button was clicked at 2:50 PM:
image
![image](https://cloud.githubusercontent.com/assets/20655031/19094807/0d0f57f0-8a47-11e6-9225-c5106efd956c.png)

**Comment by josephr5000** [comment]
FIXED.  TZ issue...

**Comment by josephr5000** [comment]
FYI see #255 that I filed while working on this.  You can see the same issue in your screenshot above in the Category column...

**Comment by drodruck** [comment]
Tested: confirmed fixed
