### ISSUE TITLE
Date format is YYYY-MM-DD

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#241]
The Reopen date in the CC's "Conference Summary" is using the yyyy-mm-dd format:
![image](https://cloud.githubusercontent.com/assets/20655031/19095130/fd077aa2-8a48-11e6-9e7f-1ef83e12006d.png)

**Comment by drodruck** [comment]
It also on the conference side:
![image](https://cloud.githubusercontent.com/assets/20655031/19095193/5c95be98-8a49-11e6-9834-24d5074fc831.png)

This might be the source for the format?

**Comment by josephr5000** [comment]
No, it's the default format that SQL Server provides, which I need to reformat.  MDB provided m/d/yy so failure to reformat wasn't noticeable.

**Comment by josephr5000** [comment]
FIXED

**Comment by drodruck** [comment]
Confirm is fixed.
