### ISSUE TITLE
Conference Site - Adding a New Request - STEP 1 RECORD NEW REQUEST DETAILS HERE has been removed and STEP 2 appears

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#244]
When selecting "Add New Request", Step 1 no longer appears. Instead Step 2 screen is displayed. I know you did this for Lisa at the Call Center. Not sure I agree with eliminating Step 1  (Record Assistance screen, STEP 1 UPDATE CLIENT RECORD for Conferences.

There are times when we may want to change or modify something on that screen. In order to do so now one has to click on "Edit Details" button to invoke the "Edit Client Info" screen, make the changes and click "Save Changes" to return to the Client File. Then click on "Add New Request" again to invoke Step 2 RECORD NEW REQUEST DETAILS HERE.

_Much less efficient that having Step 1 appear first and then simply moving to Step 2._

_Is this your intent, a result of the process going through the same programming loop as the Call Center, or is it just a bug?_

**If it IS your intent, please have the "Record New Request" screen simply read "RECORD NEW REQUEST DETAILS HERE". Having it say Step 2 will create confusion. People will wonder why there is no STEP 1.**

Sorry about the long explanation. See screen shot below.

![capture](https://cloud.githubusercontent.com/assets/20777996/19131178/4470fbba-8b03-11e6-9dab-1bbc827348ee.PNG)

**Comment by josephr5000** [comment]
Could you clarify something? 

It should NOT be true that you are FORCED to press Edit Clients EVERY time you want to make changes.

If you arrive here NOT having seen the page in the past 24 hours you WILL be shown step 1.  Can you confirm this works for you?

**Comment by TomOwens5000** [comment]
I think this is going to create confusion and problems when someone sees Step1 without first seeing Step 1. They are NOT going to know you have put a 24 hour clock on when it is and is not displayed. My guess is that during our "LIVE" testing (your conference and OLG) someone will need to add a new request and encounter Step 2 with seeing Step 1. If they do and wonder where Step 1 is then this will become an issue. In my opinion, I would fix it before we do our "one week" testing.
Just my opinion.

**Comment by josephr5000** [comment]
FIXED.  

The simplest fix seemed to be to just get ride of the "STEP 2" banner altogether.

In cases where step 1 is skipped, there's no confusing "Step 2" message.

In cases where step 1 is displayed, you need to know that is step 1, but you probably don't need a reminder that this is step 2.  This is the screen you intended to get, and my assumption is that you (the user) will be very happy proceeding to enter the request which is what you intended in the first place before step 1 interrupted things.

**Comment by TomOwens5000** [comment]
Great! I like that solution a lot.
Lets do the same with Step 1. (If I see something that says step 1, it begs the questions of where is step 2.)
Simply remove the Step 1 line and move the explanatory text up so it is just below the line under Record Assistance.
![capture](https://cloud.githubusercontent.com/assets/20777996/19422323/8d4a84d8-93c7-11e6-896d-a970926972db.PNG)

**Comment by TomOwens5000** [comment]
Checking to see if the suggestion above ever got implemented.  It did NOT. Accordingly I am leaving this open.
