### ISSUE TITLE
Intake: Status: No error check if "Assign new intake to:" is blank

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#246]
When user clicks "Save" there is no error check to see if there is a name in "Assign new intake to:" field.

**Comment by josephr5000** [comment]
FIXED, but read on for details.

Firstly, blank is a fine choice for all status settings except OPEN, in which case blank is allowed without comment.

Secondly, for OPEN conferences I'm not convinced blank is INVALID as a choice, however it is probably INADVISABLE.  For this reason if you leave "Assign Intake To" blank you won't get a hard warning insisting that you make a choice, but you will get a soft warning advising against the choice, and requiring you to press YES if you really want it.  The default answer if you just press enter is NO, which returns you to the screen to make a choice.

I'm explaining this (a) so you can test to be sure it works as claimed, and (b) so you can speak up if you think the design should be different.  If you do, please explain why.

**Comment by drodruck** [comment]
I agree with your design.  We can let the conferences run things the way they want.
It works as claimed.
