### ISSUE TITLE
Active File Statistics call counts don't make sense

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#249]
The numbers in the call counts fields are negative (-1) in "Weeks old" and (-7--1) in "Days old".  The call was just added today and the numbers don't make sense (to me at least).
![image](https://cloud.githubusercontent.com/assets/20655031/19174908/325c88b0-8be7-11e6-8f4e-cd10567ff749.png)

**Comment by drodruck** [comment]
The calls for this week display as above in the "Weeks Old" and "Days Old" columns but the calls for last week display okay:
![image](https://cloud.githubusercontent.com/assets/20655031/19253484/3793ea8c-8f00-11e6-8280-7e5c7e79f14b.png)

**Comment by josephr5000** [comment]
FIXED

It was a timezone issue.  Fixed by having clients be assumed to all be in GMT-8 timezone, which should only leave a small 1hr window around midnight where you'd get unexpected results.

**Comment by drodruck** [comment]
Tested: confirmed fixed
