### ISSUE TITLE
CC - Report: Clients With Requests Detail - 2 entires for one client but does not show all requests

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#253]
See Client File below. 2 open requests (bus tickets and food); one closed request (clothes).
Two questons. One, why does the CC report show her twice identically? Two, it shows her both times for bus tickets and clothes. Why is the request for food not shown?

I am missing something here or is there a bug?

![capture](https://cloud.githubusercontent.com/assets/20777996/19221596/5e5ec9bc-8dfb-11e6-89b4-45382c329e65.PNG)
sgssdg
![capture1](https://cloud.githubusercontent.com/assets/20777996/19221600/715fda60-8dfb-11e6-9a0e-212f51594b67.PNG)

**Comment by josephr5000** [comment]
Duplicate of #223.  Please see that issue for follow-up.  Let's close this one.

**Comment by TomOwens5000** [comment]
Sorry about duplicate.
Closing this one.
