### ISSUE TITLE
SFH Report (Part B) - Custom dates set at 1/1/15 to 10/10/16 crashes

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#254]
Was trying to see what Dave was taking about in his #180 - wanted to see more than one year displayed as I am not sure what he is talking about since I can only get 2016 to be displayed.
See screen below.
![capture](https://cloud.githubusercontent.com/assets/20777996/19243008/a5dbf434-8eca-11e6-9761-3165d1cb666b.PNG)
Clicked on Refresh and got: The page cannot be displayed because an internal server error has occurred.

**Comment by josephr5000** [comment]
Repro'd.  Set SHOULD prio (not must) b/c multi-year date ranges are not the most common scenario.

**Comment by josephr5000** [comment]
FIXED.

Nice catch.  SQL Server didn't tolerate SQL query that the former MDB back-end consumed just fine.  The SQL was generated in cases where you choose multi-year or custom date ranges in this report.

**Comment by TomOwens5000** [comment]
Took very long time processing but did finally come up as expected.
Closing this one. Tom
