### ISSUE TITLE
Intake-Only indistinguishable category rendition in Assistance History

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#255]
With Intake-Only conferences, pressing RECEIVED marks all of them with Category=Intake-Received.

This results in assistance history looking like this:

![image](https://cloud.githubusercontent.com/assets/8585358/19258417/90fde6aa-8f2c-11e6-959e-693f759ef9a0.png)

COMPLAINT:
Unhelpful to see all of them as Intake-Received with zero information about what the underlying request was actually for.

EXPECT:
Something like the Not Helped resolution where it prints as "Not Helped (Rent)" so you know *what* wasn't helped with.

**Comment by josephr5000** [comment]
Marked as MUST FIX since this makes the historical record pretty useless.

**Comment by josephr5000** [comment]
FIXED.  Now shows INTAKE-RECEIVED (REQ: RENT) or whatever the request was.

@drodruck, you've been paying attention to intake-only conferences recently.  Would you like to confirm this fix?

**Comment by drodruck** [comment]
Confirmed fixed.
