### ISSUE TITLE
Joseph - Please go in to the OLG site on the beata version and reset me to Admin

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#259]
Was testing some stuff and set myself as User and unfortunately saved the setting.
Can no longer get in as Admin and conduction tests on Intake settings, etc.
Left a couple of phone message but apparently you have not listened to them.
Thanks.
Tom

**Comment by josephr5000** [comment]
I have, but have been up to my ears in other SVDP stuff (conf-related).

Will get to this soon.

**Comment by josephr5000** [comment]
FIXED

**Comment by josephr5000** [comment]
PS: I would suggest you create an ADMIN account in OLG whose password you remember, and which you can use to fix TomO if/when needed.  This is an easy mistake to make, and it's great to have a solution at hand :-)

**Comment by TomOwens5000** [comment]
Thanks again.
I did create a backup account.
Closed.
