### ISSUE TITLE
Question by one of our Conference members regarding when we go LIVE

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#264]
Will all our previous clients and their assistance histories be included on the new site before we go LIVE the after your conference does?

**Comment by josephr5000** [comment]
That's definitely the intention.  I would need your folks to stop entering any fresh data for a brief period while I migrate your information to the new site.  When I do this for my conference I'll get a better idea how long it will take, but I hope about 4 hours should do it.  To avoid confusion I'll probably just disable logins for that period lest anyone get in by accident and be confused.

**Comment by TomOwens5000** [comment]
Thanks for the prompt reply.
Will pass along to people who asked about it.
Tom
Closing Now
