### ISSUE TITLE
Notes indented too much when printed

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#266]
From TomO in #217:

The screen version above shows the proper tab distance.
The print out of the Client File still is tabbed too far to the right.
Here is a screen shot of a scan of a printout I made for another Client File.
It is even further to the right. Guess code for the printing did not get fixed.

![image](https://cloud.githubusercontent.com/assets/8585358/19398750/fe484c0e-9202-11e6-9b85-22886620b83a.png)

**Comment by TomOwens5000** [comment]
Retested this one again.
It too is not fixed.

**Comment by josephr5000** [comment]
Who said it was fixed?  I just opened a separate item to track the issue while I worked on it.

It is now FIXED so test away.

**Comment by TomOwens5000** [comment]
YEP! Now FIXED.
Closing.
Tom
