### ISSUE TITLE
CC - the Add New Request button no longer seems to work

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#268]
Not possible now to add a new request to either an existing client file or a brand new one.
Is the site being worked on now and, as a result, precluding this button to function?

**Comment by josephr5000** [comment]
Oops, perhaps one of my formatting fixes broke it.  Let me investigate.

**Comment by josephr5000** [comment]
FIXED.  Simple typo, oops!

**Comment by TomOwens5000** [comment]
Thanks. FIXED.
Closing.
Tom
