### ISSUE TITLE
Either at CC site or Conference site - entering DOB as 4/1/41 shows age - 25

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#270]
I think someone may have reported this earlier but I am not sure. Sorry if it is a duplicate.
Also tried a DOB of 4/1/30 and got - 14.
Not likely we will have many clients 86 years old but it could happen.
So this SHOULD be fixed.

**Comment by josephr5000** [comment]
Duplicate of #240 which I just fixed.

**Comment by TomOwens5000** [comment]
Just rechecked.
FIXED.
Closing.
Tom
