### ISSUE TITLE
Treasury Page issue - unauthorized ability to delete information

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#272]
[Treasury Page Issue.docx](https://github.com/josephr5000/confdb-public/files/531365/Treasury.Page.Issue.docx)

**Comment by josephr5000** [comment]
FIXED

Changes affect officers (who have read-only access to treasury features) who are NOT treasurer/asst treasurer (who have read-write access).

From the ledger page that lists all transactions I made these changes:
- Removed Add Payment and Add Deposit buttons
- Removed red X button to delete transactions

Please verify for both non-treasurer officers and treasurers (who should still have these buttons!).

**Comment by TomOwens5000** [comment]
Logged in as a non-treasurer officer ... works as expected - New Payment and New Deposit buttons and red X are NOT present.
Logged in as treasurer ... works as expected - New Payment and New Deposit buttons and red X ARE present.






If logged in as NOT an officer or Administrator, the Treasury Pages link is not there - works as expected.
If logged in as Administrator but not an officer or Treasurer, the link is there but the New Payment and New Deposit button are NOT there (nor is the red X) - works as expected.
If logged in as a user who is not an officer
