### ISSUE TITLE
Record Assistance screen insists on an entry in Pledged/Prepaid field even when not helped.

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#273]
ENVIRONMENT
Windows 10 Pro, Firefox
ISSUE
Record Assistance screen insists on an entry in Pledged/Prepaid field even when not helped.
WHAT PAGE
Record Assistance for Conference 
WHAT STEPS WHERE TAKEN
Entered a “Not helped” call (referred to another conference) and left the Pledged/Prepaid/In-Kind field blank. 
WHAT I EXPECTED
To be able to click the “Saved” button and move on.
WHAT HAPPENED
Got an error message: “The first "In Kind" option is not a valid selection. Please choose one of the other options.” 
I was required to complete the field when nothing was pledged, prepaid or in-kind.
Screen Shots
![image](https://cloud.githubusercontent.com/assets/20655031/19414148/a366240e-92f8-11e6-8661-67636db7a9bf.png)

**Comment by TomOwens5000** [comment]
It has always worked that way in my experience.
However, I would agree with Doug that it would be nice to have it work per his expectation as shown on his screen capture.

**Comment by josephr5000** [comment]
DUPLICATE of #141.

**Comment by drodruck** [comment]
Agreed is a duplicate of 141.  Still a good thing to do and will close.
