### ISSUE TITLE
CC - Users CAN edit or delete notes - not according to spec; Admins CAN edit or delete notes - in accordance with spec

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#274]
See attached file.
[The spec per Joseph is.docx](https://github.com/josephr5000/confdb-public/files/531984/The.spec.per.Joseph.is.docx)

**Comment by TomOwens5000** [comment]
Also, just discovered when trying to log off the site, the King County Call Center **Client File** is locked and cannot be shut down with the browser's back arrow (using Firefox). Had to close the browser to get out and that of course closed the browser entirely.

**Comment by josephr5000** [comment]
I read the attachment, but am not following what is the issue.  You showed that CC user SamT is able to create notes, and then to edit or delete their own notes.  That's expected behavior...

Your next comment "Also..." further confuses me.  Is it at all related to the item above?  How?  And not following what you mean by "locked"...could you clarify?  Thanks.

**Comment by TomOwens5000** [comment]
Read YOUR OWN SPEC (see #217). It was emailed to me. It CLEARLY says:
Conf users *can't* edit CC notes. They should just add an add'l note if they need to correct erroneous info. That is YOUR comment, not mine. It does **NOT** say users *can* edit their own notes! It literally does say "...users *can't* edit CC notes." Please look at #217 and read through the progression of comments there.

What I said is: IF this is literally correct there is a problem. On the other hand, IF CC users CAN edit their own notes there is not a problem. The later appears to be correct from what you say now, but not in the spec. And, yes, it is reasonable they should be able to edit their own stuff. I certainly agree with that. But I am supposed to test stuff against what the specs say.

Now if you actually do go into the Edit Access file as user samt (password samt) and make and edit notes yourself you will find that that does work as expected. If you delete a note that too will work as expected. BUT **after** you click on "Delete" on the Confirm Note Deletion screen the browser left arrow takes you back one step at a time BEFORE you eventually get back the the Browse Client Files screen.

Then, somewhere along that path, sometimes you get: **You do not have permission to view this directory or page.** If the error message does NOT appear, you are able to get back to the Browse Client Files screen eventually. But to my way of thinking requiring all the intervening back arrow pushes will waste Helpline peoples time. It would be nice to be able to go directly back with one push so to speak --- like maybe a Back button.

In any case, I have just confirmed what I experienced. Tried it in both Firefox, Chrome and Explorer.

**Comment by josephr5000** [comment]
It says (quoting you quoting me) "*Conf* users" cannot edit CC notes.  SamT isn't a conf user, he's a cc user.  His ability to edit this CC-authored note doesn't violate the rule that "Conf users cannot edit CC notes".

**Comment by TomOwens5000** [comment]
Yep! You're right.
After you click on "Delete" on the Confirm Note Deletion screen the browser left arrow takes you back one step at a time BEFORE you eventually get back the the Browse Client Files screen.

Then, somewhere along that path, sometimes you get: You do not have permission to view this directory or page. If the error message does NOT appear, you are able to get back to the Browse Client Files screen eventually. But to my way of thinking requiring all the intervening back arrow pushes will waste Helpline peoples time. It would be nice to be able to go directly back with one push so to speak --- like maybe a Back button.

Do you want this reported as a separate issue?

**Comment by josephr5000** [comment]
Not sure why you're pressing the BACK button at all, but if you do what you will get is exactly what you describe: it takes you back one step at a time.  That's what it's designed to do.

But again, why are you pressing BACK at all?  It seems a laborious way to get somewhere.  After deletion you'll be left looking at the Client's file, just where you were before pressing DELETE.  Isn't that where you want to be?  Where else would you expect to go?

And ps: if you're done with the client after deleting a note, just press DONE (for CC users).

**Comment by TomOwens5000** [comment]
Just tried all this again. Not sure what was happening before.
Now it DOES work just like you said.
Closing this issue now.
Tom
