### ISSUE TITLE
CC - site down? Can't create a new client and save the file - no processing taking place

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#275]
Wanted to test #274 after reading your last comments - using a brand new client.
Will have to wait until this is fixed.

**Comment by TomOwens5000** [comment]
Tried again with Firefox, Chrome and Internet Explorer. Windows 7 Home Edition.
Logged in as CCtomo (Administrator) and Karieo (user) on all three browsers.
Added New Client (see screen below used for all 6 attempts).
Clicked on Save & Continue button.

NO RESPONSE! No processing takes place and screen does not change.
So I cannot create a new client. Precludes further testing I was hoping to accomplish.
First time this has ever happened.

Since you cannot reproduce this, perhaps a Zoom session for us is in order to see what if anything I am doing wrong. I will be available most of the day Monday.

![capture](https://cloud.githubusercontent.com/assets/20777996/19427035/1a475676-93f6-11e6-85ad-85e3ea27ee61.PNG)

**Comment by josephr5000** [comment]
FIXED

The fix to #123  broke this.

**Comment by TomOwens5000** [comment]
Thank you!
Fixed and works as expected.
Closing now.
Tom
