### ISSUE TITLE
OLG Intake people receiving Intake Settings Changes and other messages on OUR gmail

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#276]
Our gmail address is: svdpolg12@gmail.com. Why are we getting the testing messages? What can be done to prevent this? This is where the Call Center sends cases that are for real and this has become an issue that is confusing our intake people.
 
![capture](https://cloud.githubusercontent.com/assets/20777996/19447074/b15e7864-9450-11e6-9ba7-1a2fbe21da42.PNG)

**Comment by josephr5000** [comment]
You set up an Intake2 admin account at the Call Center, and gave svdpolg12@gmail.com as its address.  You even went so far as to verify that address!

The system is being obliging and doing exactly as you requested.  As a CC admin it's informing you when conferences change their intake settings.

If you don't want these notifications, you can do any of the following:
- Demote Intake2 to being a regular CC user and they won't get admin notifications
- Remove or change the svdpolg12@gmail.com address, and admin notifications won't be sent there
- Delete the intake2 account altogether if you're not using it any more.

**Comment by TomOwens5000** [comment]
Closing.
Tom
