### ISSUE TITLE
Observation From David Haywood - can Joseph fix this?

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#277]
Tom: 

Thanks for sending me this. I have spent an hour or so or so playing with it and really like it. Why? Because you have kept the appearance and the structure of the thing very similar to the old one and VASTLY improved the appearance. I actually went through and dummied up a couple of calls. I did not save because I was not sure if that would be OK.

One of them was a Motel call and I discovered that there is a gremlin left over from the old system. If you fill out a client report for someone you're putting in a Motel all goes well until you try and save the report. You are then asked to enter a value in the Monthly Rent field. Well if you think about it, no client that you are putting in a Motel will be paying rent. In the past I got round this some number that satisfied the system. Can Joseph fix this?

Tom this is a fine job. I really like it and my comment is only intended to make it even better. Will continue to tinker with it and see if I Can find any other gremlins.

David
Sent from my iPad

**Comment by josephr5000** [comment]
The monthly equivalent cost (labelled Monthly Rent for lack of a better idea!) is used to calculate # bednights given, a measure commonly requested on grant reports, and which measures the *significance* of lodging help that we give.

See the Bednights report from the main page for a fuller explanation of what bednights are.

I agree, Motels don't charge by the month and don't call it rent, however the motel rate can be multiplied to extrapolate a monthly rate (eg: daily x 30, or weekly x 4).  What you find is eye-popping.  A nightly motel @ $100 works out to $3,000 per month!!!!!!!  For that rate, folks could get a *really nice apartment* and it quickly demonstrates how extended motel stays can consume a lot of money for limited benefit.

REQUEST: if you have a better term than Monthly Rent that you'd like me to use when you're doing motel help, let me know...I'm all ears.  Keep in mind it must be CLEAR to all, AND fit in the limited space available.

Thanks.

**Comment by TomOwens5000** [comment]
Fixed tag has been applied but I see not explanation or comments.

**Comment by josephr5000** [comment]
Umm, they're right above your comment Tom.

**Comment by TomOwens5000** [comment]
Sorry. Have reread everything above and still don't see what you did to warrant the FIX flag.

I did just go to Sleeping Beauty file and add a SERVICES - MOTEL entry.
Clicked on Close Request. Edit Response screen is displayed as expected.
Completed Response Date, Type of Contact, etc.
Will not accept $0 in Total monthly rent (if applicable) field.
Invokes Message: Please enter a value for the "Amount" field.
Again - Will not accept $0 in Total monthly rent (if applicable) field.

How about this as a solution?
Replace "Total monthly rent (if applicable)" label with "Amount paid to Motel".
Allow the $ Value field and the new "Amount paid to Motel" fields to both accept the same dollar amount (the amount that was actually paid to the motel for however many days that were involved).

**Comment by josephr5000** [comment]
Fixed in this case means you asked a question and I gave an answer.

Isn't "Amount paid to motel" that you suggest just identical to the $ Value at the very top of that screen?

And how would I use "Amount paid" to calculate bednights?

I'm saying I don't really see how your proposed solution would work given my explanation above of the purpose of requiring this information.

**Comment by TomOwens5000** [comment]
Fixed to me means the issue has been addressed and fixed.
Isn't "Amount paid to motel" that you suggest just identical to the $ Value at the very top of that screen? YES.
And how would I use "Amount paid" to calculate bednights? I have no idea. Your the can do guy with software, not me. This whole issue is a David Haywood thing. After rereading his comments just tell me it can't be fixed, or whatever, and I will relay that to David.
