### ISSUE TITLE
Browse Clients - include Other Adult in the response

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#279]
From MicheleF@St James.  Drop "Conference" column (for non-CC) if needed to pick up space.  Next up (or down!) would be Building since Address provides similar information.

**Comment by josephr5000** [comment]
FIXED.  Doug, could you do the honors while you're checking the related item #281?  Thanks!

**Comment by drodruck** [comment]
Yep, it works. Used it to limit the search criteria, too.  Fixed.
