### ISSUE TITLE
[SJBR] Browse Clients - restore Unit # to the response listing

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#281]
From MicheleF @ St James.  Previous site listed apt # in the address, whereas current one doesn't.  She relies on this to see if a particular unit appears multiple times (eg: at transitional housing with short-stay residents).

Easy to add.  Reversion from previous site.  Easy call:  FIX IT.

**Comment by josephr5000** [comment]
FIXED.  Doug: care to confirm?  Thx!

**Comment by drodruck** [comment]
Yes, confirmed apartment # shows in Address.  Fixed
