### ISSUE TITLE
Using a 4 Digit Year on a DOB, does not work, if making changes to it.  

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#284]
When  you are editing a client file, and you need to correct a DOB, if entering a new DOB, and you're using a 2 digit year, it works fine.  But If you enter in a 4 digit year, after another DOB has been entered, it will give you an error.  This seems to work fine if using a 4 digit year for a first time user, but if someone goofs on the year and it needs to be corrected, and  you enter using a 4 digit year,  you will get the error. 
![image](https://cloud.githubusercontent.com/assets/22033172/19490354/ac474c9c-9523-11e6-859f-4614dc96ee51.png)

**Comment by josephr5000** [comment]
FIXED
