### ISSUE TITLE
Change: default to NOT share with CC, must click to share

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#288]
From 10/20 DB meeting discussion:

Change default to NOT share.  Confs to be educated to make specific choices about things to share.

**Comment by TomOwens5000** [comment]
I think a better approach is to make it configurable in the Database Settings on the Edit Conference Settings screen.  That way each conference can do what they want to do. Just add one more question on the screen below.

![capture](https://cloud.githubusercontent.com/assets/20777996/19604621/ee9af6d6-976a-11e6-8f13-d2dcbcf7c358.JPG)

For two reasons. One, the purpose of having the default being to send all notes that are not marked private to the CC is to give them information that helps them deal with people who call in for clarification of something or why they haven't heard from anyone. That was sort of a prime directive in our design of that part of the software. Two, our conference members prefer not to have to take affirmative action on each note for it to go to the CC. MOST notes will NOT be private and it will be more efficient to only have to deal with the ones that are deemed to be private. My guess is there will be the same opinion in most other conferences as well. Curious to know if in your conference it was only 2 people or a consensus of the entire conference.

**Comment by TomOwens5000** [comment]
As mentioned on the phone I DID say that was my choice!

**Comment by josephr5000** [comment]
Did the conservative fix to change the default per the DB Committee consensus.

Opened separate issue re Tom's nice enhancement suggestion which would add flexibility but isn't a show-stopper at this point.

**Comment by josephr5000** [comment]
@drodruck would you mind testing this fix?  Many thanks.

**Comment by drodruck** [comment]
Confirmed the default is not to share in the Live site but not the Test site.  Not sure you want it on both since some of the committee members are not using the Live site.

**Comment by josephr5000** [comment]
Good catch, thanks.  I just pushed the fix to the TEST site as well.

**Comment by drodruck** [comment]
Confirmed fixed.
