### ISSUE TITLE
LIVE site - Document Library missing right-hand border

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#291]
Bottom border too. Would like to see this fixed.
![capture](https://cloud.githubusercontent.com/assets/20777996/19659387/8a476dc2-99e0-11e6-925f-9225ea6713df.JPG)

**Comment by josephr5000** [comment]
Fine to revisit later, but we have much higher priorities at the moment to make sure this system works as well as possible for all.
