### ISSUE TITLE
YTD treasurer's report - timezone issue

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#298]
Treasurer's report YTD run on 10/30/16 around 5pm.

ACTUAL 

![image](https://cloud.githubusercontent.com/assets/8585358/19842323/3eb60e32-9ed5-11e6-9f40-befaa8c68519.png)

EXPECTED

Report ending today - 10/30/16.  It appears to be taking the UTC datetime which is 10/31/16 and then running that date against PDT data.

**Comment by DaveSherwood** [comment]
I retested and the correct date is now used.

**Comment by josephr5000** [comment]
@DaveSherwood FYI to see the bug (and verify the fix) you'd need to test between 5pm and 11:59pm PDT when the UTC date is tomorrow.  Just mentioning in case you tried it this morning.
