### ISSUE TITLE
Upload doesn't upload

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#299]
Environment: LIVE

REPRO
- Open Doc Library
- Upload a file

RESULT
- Upload gives no error
- No actual file uploaded

NOTE
- I suspect the upload page is redirecting to confdb-library.azurewebsites.net which applies updates to the TEST environment.

**Comment by josephr5000** [comment]
FIXED.  

### BACKGROUND
The problem was that the LIVE site was attempting to upload/download files from the same Azure Storage location as the TEST site, and things were getting very confused.

LIVE now has its own Azure Storage location where files live, distinct from the location used by the TEST site.

### TESTING NOTES:
To test this out would you please confirm:

- Download existing files that were migrated from the old site.
- Delete existing files.
- Upload new files.
- Download newly uploaded files.
- Delete newly uploaded files.

Thanks.

**Comment by josephr5000** [comment]
FYI @drodruck and @DaveSherwood .  Would appreciate if you could also try this out with your files.

**Comment by TomOwens5000** [comment]
Thank you!
Yes, I was able to upload a couple of files.
Also was able to delete one.
Can close as far as I am concerned but am leaving open for the other to test it too.

**Comment by drodruck** [comment]
Works for me, too.

**Comment by josephr5000** [comment]
Thanks @TomOwens5000 and @drodruck .  Assigning to @DaveSherwood for him to wrap this up.

**Comment by DaveSherwood** [comment]
I tried it and now can open our files. 

Dave 

----- Original Message -----

**Comment by DaveSherwood** [comment]
I was able to upload, delete, move, and open all our files. Fixed.
