### ISSUE TITLE
When logging in on  the Live site get a server error if the Conference field is blank

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#301]
When logging in on the Live site, if the conference field is blank I get a server error instead of the "Please select a conference" message box:
![image](https://cloud.githubusercontent.com/assets/20655031/19863624/1fea13f4-9f52-11e6-8676-07b9d6bb44d2.png)

**Comment by josephr5000** [comment]
FIXED

**Comment by drodruck** [comment]
Not yet.  Agreed, the drop down for the conference field doesn't include blank anymore but the default value is blank so if you don't chose a conference you get the above message.  In the old confdb you get the error message to chose one if the field is blank.

**Comment by josephr5000** [comment]
Ok, FIXED again!  The default option should read "Choose one..." rather than blank, and if you fail to make a choice it should give a popup telling you a choice is required.

**Comment by drodruck** [comment]
Agreed, finally fixed.
