### ISSUE TITLE
LIVE SITE - Document Library will not upload files

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#305]
We had our monthly meeting last night.
It is my responsibility to upload the Treasurer's Report and meeting minutes to the Doc Lib.
Everything looks like it is working but files do NOT get uploaded.
No error message.

**Comment by josephr5000** [comment]
duplicate of #299

**Comment by TomOwens5000** [comment]
Working now.
Closing.
Tom
