### ISSUE TITLE
OLG old site - during the transition one case got done there somehow by mistake

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#306]
Can you please migrate it to the new site?
![capture](https://cloud.githubusercontent.com/assets/20777996/19992773/e8dc001c-a1fd-11e6-932e-d464b8e6da92.JPG)

**Comment by josephr5000** [comment]
Not easily, sorry.  It would take you much less time to copy the new information by hand.
Joseph

**Comment by TomOwens5000** [comment]
OK. I will do it that way.
Closed
