### ISSUE TITLE
Add per-conference setting to control default note sharing / privacy

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#308]
Opinions vary about whether notes should be shared by default or private by default.

It's pretty clear we don't have consensus now on a one-size-fits-all-conferences choice here.

DB Committee meeting agreed on 11/3/16 to add a per-conference setting so each conference can discuss this among themselves and make their own choice.

This was announced at the VFG training at Seattle U on 11/5/16 so conferences that migrate are expecting this.

**Comment by josephr5000** [comment]
FIXED on TEST.  Would you please check it, and let me know if you approve?  If/when you do, I'll push it to LIVE and let you test it there too.  I'm doing this two-step process to make sure it really works before pushing it to LIVE.  Right now only 4 confs using it, but soon to be many!  Thanks!

**Comment by josephr5000** [comment]
TESTING NOTE:
- Setting is located in Admin Pages / Edit Conference Settings
- Default (the first time you look at this setting should be Private).  Is it?
- If you add a note (without changing the setting) it should default to private.
- If you change the default setting to shared, NOTE: you need to LOG OFF / LOG IN for it to notice your new setting.  At that point, if you add a note it should default to shared.
- In any case, you should be able to override the default on a note-by-note basis.

**Comment by TomOwens5000** [comment]
Setting is located in Admin Pages / Edit Conference Settings
    Default (the first time you look at this setting should be Private). Is it? YES!
    If you add a note (without changing the setting) it should default to private. YES!
    If you change the default setting PLEASE NOTE: you need to LOG OFF / LOG IN for it to notice your new setting. YES, working as you just as you say.
    If you change the conference setting to shared, if you add a note it should default to shared. Does it?  YES!
    In any case, any conference member should be able to override the default on a note-by-note basis. Can you? YES, work just as you say.

Thanks Joseph.
All works as you say and should be okay to implement on the LIVE site.
Waiting to close until you add it to the LIVE site.
Left me know when that is implemented and I will test it there.

**Comment by drodruck** [comment]
I find that it doesn't work for Mary Queen of Peace.  No matter which setting I select, Shared or not, the note is by default private.

**Comment by josephr5000** [comment]
@TomOwens5000 thanks.  I just pushed it to the LIVE site.

@drodruck did you logoff/login after changing settings?  You need to do that for it to notice the change.

**Comment by drodruck** [comment]
Yes, I did.  Just now got out of the browser, got back in and with the setting "Shared":
![image](https://cloud.githubusercontent.com/assets/20655031/20167723/27665282-a6d2-11e6-927a-9abee2a5e910.png)
 the notes are not automatically set to "Share with call center".  Confusing. I did this on the live site, too:
![image](https://cloud.githubusercontent.com/assets/20655031/20167683/e40efe1c-a6d1-11e6-8a5d-fb85aabf0980.png)

**Comment by josephr5000** [comment]
@drodruck, 2nd screenshot was very helpful. Nice catch! Your conference doesn't use the Active File so its results page (pictured above) uses a different template from the page used to close active calls.  I hadn't included the new feature in your version of the page.

Should now be fixed.

**Comment by drodruck** [comment]
Agreed, it works now on the LIVE site.

**Comment by TomOwens5000** [comment]
Just tested it on the LIVE site and it works there for OLG, just as it did on the beta site. Not sure if you are going to have anyone besides Doug verify that it works so I don't want me to close. I prefer to have YOU close it when you are satisfied that all necessary tests have been completed but as far as I am concerned it can be closed --- but I will let you do that when your are ready. 
Tom
