### ISSUE TITLE
LIVE SITE - Default notes when 1st entering a new request (not working right now)

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#309]
OLG Conference IS configured to share notes by default in the Edit Conference Settings.
When Karie entered a new request today for an old client the share note with call center box was NOT checked as it should have been.  Not sure what is going on here.

![capture](https://cloud.githubusercontent.com/assets/20777996/20227593/c89addaa-a801-11e6-9c93-5ad3705c3915.JPG)

**Comment by josephr5000** [comment]
Can you reproduce this?

**Comment by josephr5000** [comment]
@TomOwens5000 thanks, but please don't edit my item.  Add you own new item.  It makes the conversation *much* easier to read.  If you look above, the result is really puzzling.  "josephr5000 commented", the banner says, and I lead with a question and then appear to answer my own question.

I suspect some folks in your conference may do something similar with case notes, which explains some of the permissions issues your folks encounter that others (thus far) do not.

Thanks for the update.  I'll investigate.

**Comment by josephr5000** [comment]
FIXED :-)

Particular thanks for your hint in all-caps above that it only occurs for the first note.  That helped me zero in on my omission really quickly!  Much appreciated.

**Comment by TomOwens5000** [comment]
Fixed!
Thanks.
Tom
