### ISSUE TITLE
CC new notes marked (private), should be shared

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#314]
TO REPRO
- Log in as CC admin
- Create fresh request including note
- Log in as conf user
- Look at newly added client request

NOTICE
- New note created by CC is marked "(private)"

EXPECT
- CC notes should definitely be shared with the CC, ie: **not** private!

ALSO NOTE
- When CC admin looks at this file they can't see notes they just created!  They see the client, the request, and "no notes found" (assuming conf hasn't added any, of course).

**Comment by josephr5000** [comment]
adsf

**Comment by josephr5000** [comment]
adsf

**Comment by josephr5000** [comment]
FIXED.  Over to you, @lisabarrientes, to confirm and close.

**Comment by lisabarrientes** [comment]
Fixed!
