### ISSUE TITLE
New Intake email should list client name in subject line

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#316]
### PROBLEM:
The old system listed the client's name in the subject line.  That was very useful for inbox management.  The new system's messages all look identical until you open them, which is unhelpful.  See the screenshot below.

![image](https://cloud.githubusercontent.com/assets/8585358/20405042/5b1a5048-acbc-11e6-87b9-2ea33b3814be.png)

### REQUEST
Have the new system include the client's name in the subject line.

**Comment by josephr5000** [comment]
FIXED.  @TomOwens5000 , assigning to you to verify since OLG will be doing direct intake this week.

**Comment by TomOwens5000** [comment]
Yes, we are to be live with the Call Center today.
I check out intake a little earlier.
So far nothing from Lisa or Chris (at least I assume because everything so far is via gmail with the data having to be entered into the Client File at our end).
Tom

**Comment by TomOwens5000** [comment]
After email Lisa and actually talking to her she resent the ones in the screen shot below.
They do, in fact, show the client name in the New Intake from Call Center line.  I assume
this is what you are looking for.
![capture](https://cloud.githubusercontent.com/assets/20777996/20545156/75162404-b0c2-11e6-8a43-51c91a904865.JPG)

If this is what you are looking for (I think it is) then we are in business.
Pretty sure this is what you want so I am closing this one.
Please reopen if I am mistaken.
Tom
