### ISSUE TITLE
Users can edit existing notes (including sharing level) for grace period after note creation. Admins can edit any time.

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#32]
We need to be able to change the notes availability to be seen by the help line.

**Comment by josephr5000** [comment]
@drodruck Could you give a bit more details to help me respond.  What did you try?  What happened?  What did you expect?  Thanks.

**Comment by josephr5000** [comment]
Phone call from Doug: he's looking to change sharing level of an *existing* note.

**Comment by josephr5000** [comment]
Changed the title to connect ability to change sharing level with broader ability to edit the note.

DESIGN: you can edit a note (including changing its sharing level) if:
- You're the note's author, and you created the note within the past 14 days
- You're an administrator

**Comment by drodruck** [comment]
I added two notes on Suzanne Martin (Etahiri)'s 8/12/16 assistance entry, went back to the Client File page and can not see the grey "Edit" link next to the date stamp.  I tried this on the Edit Response page also and can see no "Edit" link to click.  Not yet implemented?
