### ISSUE TITLE
The Memo field in the Client File should not be visible to the Call Center

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#320]
Per our discussion, the Memo Field in the Client File should not be visible to the CC due to privacy issues:
![image](https://cloud.githubusercontent.com/assets/20655031/20574520/b2e9aeca-b169-11e6-8c9b-973973278940.png)

**Comment by josephr5000** [comment]
FIXED

@drodruck would you please confirm that from the conference end you CAN still see and edit client memos?

@lisabarrientes would you please confirm that from the CC end you now CANNOT see and CANNOT edit client memos?

Whoever confirms last, please close this issue.  Thx.

**Comment by TomOwens5000** [comment]
Not mine to close.
Did just check this out.
The entire memo line is missing on the CC site.
It is present on the Conference site.
Assume this is what we are after.
But I am NOT closing because you asked Doug and Lisa to confirm and close.

**Comment by lisabarrientes** [comment]
Confirmed.

**Comment by drodruck** [comment]
I checked a number of files and saw no memos on the Client File screen but did see a notes on the Record Assistance screen as Lisa notes above.

**Comment by josephr5000** [comment]
@drodruck and @lisabarrientes : thanks for the catch.  Would you please check again?  Memos now be gone from the Edit Client page that you noted above.

**Comment by drodruck** [comment]
The notes in the memo field are still visible in the "Record Assistance" screen as shown below:
![image](https://cloud.githubusercontent.com/assets/20655031/21298586/c98849c4-c547-11e6-8aa9-33737467a727.png)

**Comment by josephr5000** [comment]
@drodruck FIXED

**Comment by drodruck** [comment]
Yes, fixed (again!)
