### ISSUE TITLE
The CC admins should be able to see if an email is verified

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#322]
In order to improve administration effectiveness, the CC admins should be able to see if an Intake email has been verified or not.

**Comment by josephr5000** [comment]
Related but not 100% on-point: I improved the error notification sent to CC admins to **name** the offending party so their "fix-this" communication to conferences can be more precise and constructive.  Here's an example:

![image](https://cloud.githubusercontent.com/assets/8585358/21076244/5e13ae8a-bedb-11e6-9984-e9f31eee3a2a.png)

**Comment by josephr5000** [comment]
FIXED.  If you drill down into details on CC intake settings report you see this:

![image](https://cloud.githubusercontent.com/assets/8585358/21754599/49afbf8a-d5b8-11e6-8dfc-4faac73e25f6.png)

**Comment by josephr5000** [comment]
@drodruck FYI.  @lisabarrientes : for you to verify & close since you're the main customer for this.  The idea is so you can get more detail on conference email settings...hope this helps.

**Comment by lisabarrientes** [comment]
I will verify, but I first need to know how I can find out if there is an email address associated to this, if it says not verified, but all i see is INTAKE (INTAKE INTAKE)...and no email address shows; How do I know what the email address is? Or, if there is no email in there, then should there be a way to not let this be an error, if there are emails on the Copy new intake to:?
![image](https://cloud.githubusercontent.com/assets/22033172/21783128/ee99d64a-d66a-11e6-9880-3cd4e71930b2.png)

**Comment by josephr5000** [comment]
If no email is listed, then it means there is no email address given.
