### ISSUE TITLE
Identity of Call Center intake person unknow if they do not create a note

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#328]
Most of the stuff we have seen come in LIVE from the Call Center has an note providing some detail about the request. That enables the Conference to know who made the note and give the Conference a little heads-up on the request.  The ones Lisa has forwarded are great because they provide some information besides just the category of help requested and identify her as the person creating the note.

I just received one where it just said GOODS- FOOD (with no note). 

Question.
Is it important for the Conference to have an "audit trail" as to who created the Client File?

**Comment by josephr5000** [comment]
Which request was that?  Trying to understand what you mean by "just said GOODS-FOOD with no note".  Surely it noted the user who created it, eg: "by LisaB", right?

**Comment by TomOwens5000** [comment]
Not it did NOT identify the person who made the entry. That is the point 
I am making.
If I am correct, the reason it did not identify someone is because they 
did NOT make a note.
Instead, they just selected a category of help. With no notes created 
the software does NOT identify the person at the Call Center who created 
the Client File that is being forwarded to the Conference under the new 
LIVE format we are now using.

The Client File comes to the Conference and is placed in the Active File 
just as it should ... but who created the file is unknown.
