### ISSUE TITLE
Unusual Character in SQL Fields

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#33]
In the migration from Access several fields picked up an unusual character (Â ).  I have seen it in the Edit Client Info screen in the fields Apartment, Building, Other Adults, Phone2, Utility Acct Num, the beginning and middle of Notes, the beginning of Phone1, Girls, Boys, Address, City, and Zip so far.  It does not show in the Client File screen.

**Comment by josephr5000** [comment]
Can you give me a specific user where you see this, so I don't have to hunt around?  Thanks.

**Comment by drodruck** [comment]
Charlotte Markee is a good example.  If you can't see her, pick someone with no address (little information in their file) and click the Edit Details button.

**Comment by drodruck** [comment]
In looking at the original database (the MDB) the "empty" fields in Charlotte's file are not really empty but have a character that SQL evidently translates to "Â ".
