### ISSUE TITLE
Test Site Login no longer works

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#333]
For one, I would like to have access to it for testing and other purposes!
Tom Owens

**Comment by josephr5000** [comment]
DONE :-)

**Comment by TomOwens5000** [comment]
Thanks.
Just tried it but there is an issue.
The page cannot be displayed because an internal server error has occurred.

**Comment by josephr5000** [comment]
Oops, forgot to apply a query update on the database.  Try again.

**Comment by TomOwens5000** [comment]
Thanks again.
Works fine now.
Tom
