### ISSUE TITLE
Choose up to 4 users to be notified of new intake

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#334]
CURRENT DESIGN
You can choose Assign New Intake To, and that one person gets notified.

THE NEED
Some conferences have teams who collaborate (sometimes simultaneously) on intake, or want a backup contact, and would like to be able to designate *multiple* people to receive intake.  To date the highest # I've heard is 4 people.

THE SOLUTION
This design change will separate the concept of **Assign New Intake To** from **Notify These Users About New Intake**.  Admins will be able to choose up to 4 users to receive notification.

BONUS POINTS
For extra credit (if time permits) have this provide a warning if a selected recipient doesn't have a verified email address.

**Comment by josephr5000** [comment]
@drodruck : Now on confdb-test.azurewebsites.net/confdb in case you'd like to try it out.  Let me know what you think.

[FYI if you have gmail (eg: josephr5000@gmail.com) you can use distinct throwaway aliases josephr5000+whatever@gmail.com (the plus sign is required) that all deliver mail to josephr5000@gmail.com but you can tell which alias was used.  It's very convenient for playing with this as you don't really need to create multiple mailboxes.]

**Comment by josephr5000** [comment]
FIXED.  Please note: this fix should apply to ALL conferences, whether intake-only or full users.  Would you please check both cases?  Thanks.

**Comment by drodruck** [comment]
Applies to intake and full as far as I can test.
