### ISSUE TITLE
Active File. Extra space being inserted between street address and the comma before the city.

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#336]
See screenshot below. Should be "12 Quacker Blvd, Seattle" not "12 Quacker Blvd , Seattle".
![capture](https://cloud.githubusercontent.com/assets/20777996/21074275/98c5c5f4-bea9-11e6-94e0-1dc40b2ff4de.JPG)

**Comment by josephr5000** [comment]
What platform is this on?  Hard to believe your LIVE OLG has only 1 active.  If not LIVE, please check LIVE to see if the issue exists there too.  Would you please also check the Apt field?  If you have a space there, that will produce the result you see here.

**Comment by TomOwens5000** [comment]
On the Beta Site. Not an issue of only one Active File on the LIVE site.
I checked the Apt field and there is NO space in it.  So that is not the reason for the extra space in the Address field on the Active File.
