### ISSUE TITLE
Intake-Only: allow editing of client profiles to correct errors, etc

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#337]
Request at recent 12/5 training session for Intake-Only conferences: to be able to edit the Client Profile to correct errors, etc, so that future referrals for the client don't repeat erroneous information.

Today users do this by emailing Lisa who updates the client's profile in the helpline database.  Not having this ability is a regression from current functionality.

SOLUTION: enable the "Edit Client" button on the Client File page for intake-only users.

**Comment by josephr5000** [comment]
FIXED.  Please check it out before 12/12 training :-)

**Comment by drodruck** [comment]
Confirm is fixed.
