### ISSUE TITLE
test for jim - no action required

### ISSUE THREAD

**Issue by jln522** [josephr5000/confdb-public#34]
ISSUE
Clicking on Last Name brings up wrong client on Client File page

WHAT PAGE
Active File

 
WHAT STEPS WHERE TAKEN
Opened Active File Page
Clicked on Last Name “Hill”

WHAT I EXPECTED
Client File page would be for Jane Hill

WHAT HAPPENED
Client File page opened to client Luana-Talltree Marshall

Screen Shots
![image](https://cloud.githubusercontent.com/assets/15675689/17217612/cc74d086-5499-11e6-88b8-92baf0a650cb.png)

 

Shoud open

 
![image](https://cloud.githubusercontent.com/assets/15675689/17217660/f874869a-5499-11e6-8aaf-7ef7134bfb5c.png)

It opened

**Comment by josephr5000** [comment]
Closing as title says "no action required".  Reopen with clarification if action is actually expected.
