### ISSUE TITLE
Cannot use the same email address for volunteers

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#342]
I have tried to use my email address for a few volunteers in the Helpline Center.  When I try to verify the email address I keep getting this error message.  Is there a way to add volunteers in the DB, without having to add or make new emails on their behalf to let them access  the database?
![image](https://cloud.githubusercontent.com/assets/22033172/21153487/840e4d7a-c11f-11e6-8ba2-1488cfe3cdec.png)

**Comment by josephr5000** [comment]
You probably get this for one of the three reasons clearly explained in the message.

I doubt reason #1 applies.

I doubt reason #2 applies.

I'll bet you're bumping into reason #3.  If you're logged into the DB as LisaB you won't be able to verify for JudyH.  You need to logoff the DB first, then click the link in email and when prompted you'd log in as JudyH.

Please try this and let me know if it works.

**Comment by josephr5000** [comment]
PS: I can change the design, but what I mentioned above is -- hopefully -- the fastest way for you to work around this and move forward.

**Comment by lisabarrientes** [comment]
Yes, it was reason #3.  Fixed!  Thanks!
