### ISSUE TITLE
LIVE site - Edit Client Info screen somewhat trashed - IMMEDIATE FIX REQUESTED

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#345]
Cannot edit monthly income. Occurs AFTER hitting Edit Details on Client File.
![capture](https://cloud.githubusercontent.com/assets/20777996/21239679/cfc4ae3c-c2bc-11e6-8ef1-e58fd2280d5f.JPG)

**Comment by TomOwens5000** [comment]
My mistake. For some reason the screen looks different to me but it DOES permit making the required entries.

**Comment by josephr5000** [comment]
Hmmm, that screenshot you pasted above looks pretty familiar...not seeing anything obvious that changed.  Glad you resolved the issue okay.
