### ISSUE TITLE
Intake -- temporarily closing conference -- admin training required?

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#347]
For Christmas, our Conference temporarily closed – no new intake to be received from the Call Center from 12/22/16 through 12/26/16. 

**How did we do this?**
After the Call Center closed on the 21st we changed our Conference Status to “Temporarily Closed” and set the “Expected (re)opening date” to 12/27/16.

On December 26th (with the Call Center closed) we reset our Conference Status to “Open” and erased 12/27/16 from the “Expected (re)opening date” field, leaving is completely cleared.

Worked as expected with no problems – due to having put reminders in our calendar for the trigger dates in question.

**QUESTION**
Assume a Conference knows it is going to be temporarily closed 2 weeks from the current date and reopen 2 weeks later.  Their Administrator will need to make a reminder to trigger the change in Conference Status one evening before closing – and another reminder to trigger the change back to Open status one evening before reopening.

I can see this falling through the cracks and not being implemented for closing, reopening, or both.
***Do we need to address this potential problem in some form of training?***

**Comment by josephr5000** [comment]
I did in the trainings I gave.

**Comment by TomOwens5000** [comment]
My thought is that maybe something needs to be in writing. Pretty sure a lot of people are not going to remember everything that was said at the training sessions. Especially after a fair amount of time has elapsed.

**Comment by josephr5000** [comment]
I'm assigning this to Lisa, since I doubt people will read anything in writing either.  I suspect if they're uncertain they'll contact Lisa, so I'd like her to know to remind folks about how to do it.  She can use your example at the top to explain how OLG did it successfully.

Also pinging @drodruck in case he has thoughts on the question.

**Comment by josephr5000** [comment]
Changed the title to be more specific and remove ALL-CAPS which isn't needed.

**Comment by josephr5000** [comment]
Question above was asked and answered.  Can we close this?

**Comment by TomOwens5000** [comment]
OK. Guess you put this in Lisa's court but I didn't get the impression she knew that at our last meeting.

**Comment by lisabarrientes** [comment]
I did.
