### ISSUE TITLE
Should DOB be a required * Field?  - It can be overlooked. 

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#348]
![image](https://cloud.githubusercontent.com/assets/22033172/21525425/0cc2734a-ccd2-11e6-9278-f0ee2e563305.png)

**Comment by josephr5000** [comment]
@lisabarrientes I'm sure conferences would LOVE to have this information available.  Are you saying that you are willing to have this be a REQUIRED question for helpline staff to fill in?  Please confirm.

**Comment by josephr5000** [comment]
FIXED
