### ISSUE TITLE
Call Center - bug end of Expected Wait line

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#350]
As Lisa reported today ... this is different error (she reported "days" error). Also picking up 5361. I think this is a combination of the Intake Settings for St. Peter Conference.  Should be fixed before Jan 3rd.  The 6 and 1 may be coming from the Intake Quota screen (not sure though). No idea of where the 3 is coming from.

![capture](https://cloud.githubusercontent.com/assets/20777996/21557770/ecfe15e0-cde5-11e6-8fbf-ec7353c559e5.JPG)

[ REMOVED UNRELATED ISSUE ]

**Comment by TomOwens5000** [comment]
Just occurred to me. This will also be a problem for conferences that impose a quota. The test requests, unless deleted, will likely count against the quota when they go live. In the case above, they already have 2 test cases so only 4 spaces are left. That will preclude them from getting 2 cases if they come up during the current month.  Guess Override could be used but is that a good solution?

**Comment by josephr5000** [comment]
@TomOwens5000 In keeping with the single subject rule, I'm going to work on the title issue.  Please take the unrelated item into a separate issue.  Thanks.

**Comment by josephr5000** [comment]
FIXED

**Comment by josephr5000** [comment]
FYI @lisabarrientes please also confirm that you see this fix.  Thanks!

**Comment by lisabarrientes** [comment]
Fixed!  Thank you!
