### ISSUE TITLE
Intake Only Conferences - test cases sent to them may cause a quota issue

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#351]
Question posed to me today when meeting with St. Francis and the other day when working with OL Fatima. Is there a way to delete the test requests so only "for real" requests will be retained in the Recent Activity list?

This may present a problem for conferences that impose a quota. The test requests, unless deleted, will likely count against any quotas they have set when they go live on January 3rd. For example, St.  Peter already has at 2 test cases in the Recent Activity list so only 4 spaces are left with respect to their quota of 6 cases per month. That may preclude them from getting 2 cases should be accepted if they happen to come up during the current month.

Guess Override could be used but is that a good solution?

**Comment by josephr5000** [comment]
It won't hurt anything unless they create dummy requests in the same time period as the quota.

Eg: for a monthly quota, stuff entered in Dec won't matter in Jan.  For a weekly quota, stuff entered last week won't affect next week.

So long as people stop entering dummy requests on 12/31, they should be just fine.  If they have dummy requests they can always bump up their quota count to open more spaces.

IntakeOnly isn't intended to be a space where we load up all capabilities of the full system, and being able to go and remove things sent in by Lisa wasn't on the requirements list.  If you'd like to add it to the 2017 wish list, of course please do so.

**Comment by TomOwens5000** [comment]
Thanks. Will pass along that information to those who asked.
