### ISSUE TITLE
Intake Only Conferences - who plan to go to the full system in January

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#353]
Two questions posed to me.
Will they have to reenter everything from scratch or will it be migrated over automatically? They are referring here to member list data here.

Will members who have verified their email under the Intake Only scenario have to verify their email addresses again or will that get migrated over automatically?

**Comment by josephr5000** [comment]
It's the same system.  You'll have all the same data.

**Comment by TomOwens5000** [comment]
Thanks. Answers questions. Will pass along answer to those who asked.
