### ISSUE TITLE
Intake Only Conferences - is there a way to delete dummy members

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#354]
During training sessions (or at a later date) some people apparently created dummy members.  Question posed is how to delete them.  Obviously, no cases have been assigned to them so removing them should not destroy links to existing data.

Not talking about making them inactive. Talking about REALLY deleting them.

**Comment by josephr5000** [comment]
This is a duplicate of #352.  If you want to continue that conversation, please do so there.

PS: you asked how to delete, and I answered.  If you're suggesting an improvement, say so and tag it 2017 so we look at it later.  Thanks!

**Comment by TomOwens5000** [comment]
Guess we are not on the same page, so to speak. The question was about DELETING entries.  To me than means REMOVING THEM FROM THE DATABASE, not hiding them from view by changing the Member Status.

I'll pass along your answer to those who posed the question.
