### ISSUE TITLE
Call Center bug - Turn-Away Aggregate Statistics broken

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#355]
Selecting Turn-Away Aggregate Statics returns the following error message.
![capture1](https://cloud.githubusercontent.com/assets/20777996/21569884/b84fe7b6-ce75-11e6-8cba-01b739eeb193.JPG)
![capture](https://cloud.githubusercontent.com/assets/20777996/21569891/c65f87b2-ce75-11e6-8581-1f9d992f9e35.JPG)

**Comment by josephr5000** [comment]
Ooooops!   I guess Lisa doesn't (yet) use that report much since no-one noticed yet.  Thanks for the good catch, Tom.

FIXED.

**Comment by TomOwens5000** [comment]
Just retested it. It is fixed. Thanks.
