### ISSUE TITLE
Missing data - Cannot view Conference Status Notes

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#356]
I looked at this file and on Blessed Sacrament File.  Cannot view the stats for the conference.  I put in the stats with Mirya and was not able to view the stats. And if you look under the Homeless tab, **"No Such Conference"** displayed.
![image](https://cloud.githubusercontent.com/assets/22033172/21573205/9cb34e78-ce96-11e6-8306-c6805f403021.png)

**Comment by josephr5000** [comment]
@lisabarrientes  Not following what you mean above when you say "cannot see the stats" or what the "homeless tab" is.  Neither of those seem to be shown in the picture you attached, or perhaps I'm missing something obvious!  Help?!  Thanks.

**Comment by josephr5000** [comment]
Closing for lack of response in over a year.

**Comment by lisabarrientes** [comment]
Issue seems resolved.
