### ISSUE TITLE
Loading Client Files from Active File - taking LONG time again

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#358]
Others have mentioned this too. Seems to have slowed down a lot since I last tried it.

**Comment by josephr5000** [comment]
Can you provide specific examples of clients that take a particularly "long time"?  I'm curious if there's anything in particular about their data.
Thanks

**Comment by TomOwens5000** [comment]
Not sure about the other conference members, whether or not they 
remember which clients.

I DO remember the two I just tried (assigned to me).  Domekia Dawkins 
and Latista King.  If you want me to go in any try to load others for 
you, let me know and I will do it.

**Comment by TomOwens5000** [comment]
Just went in and tried several client in the Active List.

It looks to me like the issue may only be with those with long 
histories. Others responded in an acceptable time.
