### ISSUE TITLE
Call Center - Report: Client-with-Requests By City

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#359]
One, why is Seattle listed 3 times instead of just one - like the other entries?
Two, one of the Seattle entries is "seatte".  How can that be edited to correct the spelling?

**Comment by TomOwens5000** [comment]
Sorry. Got interrupted and forgot to attach this initially.
![capture](https://cloud.githubusercontent.com/assets/20777996/21583803/1a3ce804-d045-11e6-9957-c61990066d20.JPG)

**Comment by josephr5000** [comment]
It groups by what people enter for addresses.  If you misspell addresses (Seattle is misspelled two different ways above) you'll get duplicates.

**Comment by TomOwens5000** [comment]
Thanks Joseph.
Was able to search and find the culprits --- and fix them. Report in Call Center now looks like it should.
