### ISSUE TITLE
Show quota for temporarily closed conferences

### ISSUE THREAD

**Issue by josephr5000** [josephr5000/confdb-public#360]
From LisaB:

Hi Joseph,
 
When a conference is Temporarily Closed and has a quota limit we should be able to see the Quota limit viewing the day and time to call, so we can let the client know.  I can view it only under the Admin side.

![image](https://cloud.githubusercontent.com/assets/8585358/21620344/aee607e2-d1a8-11e6-88a2-b7cbaca82e48.png)

**Comment by josephr5000** [comment]
This is BY DESIGN, but I'm taking Lisa's question as a request to CHANGE the design.

The value of having this info would be to more clearly communicate *when* after reopening clients should call.  Eg: if a quota opens at 11:00am it will do no good for clients to call at 8:00am.

**Comment by josephr5000** [comment]
FIXED

![image](https://cloud.githubusercontent.com/assets/8585358/21620475/5cdb7170-d1a9-11e6-8007-80af62fa35fe.png)

- Added weekday to the reopen date, so it's more clear (eg: when is 1/9/17?  much clearer if it includes the weekday)
- Added sentence with "AFTER it reopens..." to explain what the quota WILL BE.  This is in the future, of course.  That isn't the quota TODAY because the conference is closed.

**Comment by lisabarrientes** [comment]
Thank you for fixing this!
