### ISSUE TITLE
Admin - Billing Question Option

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#365]
Is there a way to make this not an option?  So we can put in notes for questions regarding payment on requests that have turned blue.

**Comment by josephr5000** [comment]
Conferences can turn it on (or off) under INTAKE: TYPES OF HELP OFFERED.
Not following why you would want this to NOT be an option.  Isn't it helpful?

**Comment by josephr5000** [comment]
@lisabarrientes haven't heard an answer to my question above... can you please answer?  Thanks.

**Comment by lisabarrientes** [comment]
I mean not an option to turn off.  Some conferences have this, but others do not.  So, it looks as thought we are inputting another request, rather than a billing question.

**Comment by lisabarrientes** [comment]
What does resolved-postponed mean?
