### ISSUE TITLE
Can the list of services be shown on the side, where it can be viewed as shown below?  

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#368]
#1 Complaint ...It is hard to see what a conference helps with especially one that has a quota that limits us (Call Center) to  override. It is impossible to view such services. 
![image](https://cloud.githubusercontent.com/assets/22033172/21818094/5b964b6a-d71b-11e6-9b15-b392d58399da.png)

**Comment by josephr5000** [comment]
As the CC now tries to push everything to conferences for them to sort out, knowing what is/isn't on the conference list seems much less important.  As such, this doesn't seem worth fixing so I'm closing as WON'T FIX.

**Comment by lisabarrientes** [comment]
Some Conferences do still use quotas, or limit their pull-down menus, to only a specific few.  We do still need this feature.
