### ISSUE TITLE
The City and Zip field should NOT be a free style form.  

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#369]
I mentioned this before, and have come accross this as  being an issue in the new ConferenceDB.  This WILL lead to ERRORS, and possibly being sent to the wrong conference. Cities and Zip Codes should be pre filled in database.  
![image](https://cloud.githubusercontent.com/assets/22033172/21819250/c7c60466-d71f-11e6-9184-e2022a08222c.png)

**Comment by josephr5000** [comment]
City issue is a duplicate of #338 .

I don't understand what's being requested regarding ZIP codes.  Automatic ZIP code lookup is a significant extra feature as it would require -- most likely -- a paid external service to look up and correct addresses entered by users.  Did the previous HL database do this??????

**Comment by lisabarrientes** [comment]
Yes it did.

**Comment by lisabarrientes** [comment]
I did not mean to close this...

**Comment by josephr5000** [comment]
Now we resolved the ZIP thing, time to close?  City is already covered on the other issue.

**Comment by lisabarrientes** [comment]
Yes, resolved....bummer I thought it was the City thing and was excited, until I figured it wasn't.   Oh, well....
