### ISSUE TITLE
Enhance report date range picker to allow changing custom dates

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#37]
I was reminded that when entering a custom date, if you want to change the date, you have to enter a different search type first before you can enter a different custom date.

**Comment by josephr5000** [comment]
Not following you.  Could you describe more clearly?  Eg: "when entering a custom date" - where are you entering one?

**Comment by DaveSherwood** [comment]
It is in the Volunteer Hours and Miles Summary screen using the Custom Date selection.

**Comment by josephr5000** [comment]
@DaveSherwood Got you!  It's a great suggestion and even more generic than you suggest -- it applies to many report date pickers that all share common code -- so I edited the title to make it more generic.

Filed in BlueSky, items that are great ideas that we can revisit when the current project is done.
