### ISSUE TITLE
Check Mark Status for Homeless, Veteran, etc., disappears after entering a Turn Away. 

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#371]
This is just a sample, but  after entering data check mark(s), (this one had Homeless, Disabled & Veteran checked on it), when you enter a Turn-away, and go back to the file the check mark disappears.
Before
![image](https://cloud.githubusercontent.com/assets/22033172/21826563/d342c604-d73c-11e6-8a31-2adeea8b0dc3.png)
After
![image](https://cloud.githubusercontent.com/assets/22033172/21826350/f81c6f76-d73b-11e6-9be8-59a9179934d5.png)

**Comment by josephr5000** [comment]
As far as I know, turn-aways are no longer being used by the CC.  I haven't yet tried to repro this, but if turnaways aren't being used it doesn't seem worth the time to investigate further.

**Comment by lisabarrientes** [comment]
WRONG: Yes we still use turn-aways for conferences who are Closed; permanent or not, or have a quota, for Quota full.  St. Peter, St. John the Baptist, still use quotas (perhaps more, but not sure).
