### ISSUE TITLE
Is there a way to search for other adults in the Last name or First name field? 

### ISSUE THREAD

**Issue by lisabarrientes** [josephr5000/confdb-public#377]
It was discovered that a household member (girlfriend), called to put in a request for assistance. But when called she did not mention that her boyfriend called prior although, her name was put in as the "Other Adult" in the original file. Then when she called in today, her name did not populate, which created a duplicate request for the same household. Which brings me to this question:  Could the "Other Adults" be searched on the Last name or First name, in the search field? Or, prevent this from happening again, by creating a duplicate name search?
![image](https://cloud.githubusercontent.com/assets/22033172/22126069/01f1fc62-de4b-11e6-9534-eecded8c45b1.png)

**Comment by josephr5000** [comment]
Not a quick/easy request, so I'm closing this and tagging it for reconsideration later in 2017 if the Council wants to do a project revision this year.
