### ISSUE TITLE
Confusion by Some INTAKE Conferences on how to use the database

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#378]
[Intake Conferences.docx](https://github.com/josephr5000/confdb-public/files/724645/Intake.Conferences.docx)

**Comment by josephr5000** [comment]
Here's what Tom put in the attached DOCX, to save others the trouble of downloading an attachment:

Intake Conferences (as of Monday 1/23/17)

OL Fatima

•	5 clients in Active File 
•	Maureen has NOT clicked RECEIVE for any of them
•	No way of knowing if she has contacted them or not
•	Only 2 conference members – she is only one with verified email
•	Clients With Recent Activity – NONE
•	RECEIVED button is not present so I’m not sure why the clients are still in the Active File 

St. Anne

•	4 clients in Active File 
•	Monica has NOT clicked RECEIVE for any of them
•	RECEIVED button is not present so I’m not sure why the clients are still in the Active File 
•	No way of knowing if she has contacted them or not
•	Only 3 conference members – she is only one with verified email
•	Clients With Recent Activity – 10

St. Peter

•	0 clients in Active File 
•	Only 7 conference members – 4 member have NOT verified their email – and no password has been assigned to them
•	Clients With Recent Activity – 8
Full Database Conference – St. Francis of Assisi (as of Monday 1/23/17)
•	11 clients in Active File
•	No INCOME SOURCES are being provided
•	No notes are being provided by the majority of members
•	19 Conference members – only 9 have confirmed their email
•	My comments about converting too slowly – allowing members to work in OLD way
