### ISSUE TITLE
Historical notes shared with the Call Center

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#39]
When the final data is migrated to the new database program I believe we should allow the Conferences to go back in historical notes and check those notes they want the Call Center to see when they look up the client.

**Comment by josephr5000** [comment]
Related to #32.  Will need to fix that before we can address this.

@drodruck  : at present historical notes will be brought forward as a single note -- too hard to reliably break them up into subnotes for each day -- which would mean users could share all-or-nothing of a past note.  Do you think that's useful?  I know for ours, the eventual conclusion might be nice to share, but all the sausage-making that led up to it is best to hide.

**Comment by drodruck** [comment]
I agree, if all of the notes will be brought forward as one note, the "sausage" would be difficult for both sides.  I guess if a Conference wanted to share a part of the historical note with the CC they could copy that portion and paste it into a new note marked to share.
