### ISSUE TITLE
Tabbing between fields in Client Browse produces slight movement of the input boxes

### ISSUE THREAD

**Issue by ghost** [josephr5000/confdb-public#41]
**ENVIRONMENT**
System ID: Windows 7 Home Edition
Browser: Firefox version 47.0.1

**ISSUE**
Instability of Search Filter screen

**REPRODUCE**
Move the cursor from the Last name, First name, Phone number or Other Adult field

**NOTICE**
Result: movement of both the _Locate Client's Address box_ and _Search Filter box_ shift left or right - depending on which field within the boxes is made the current field. Moving between the Address, SSN, Age from and Age to field do NOT create this issue. Everything is stable in this scenario.

**EXPECTED**
Moving from one field to another should not change anything - everything on both screens should remain motionless (with the exception of what is entered in the respective fields themselves).

**Comment by drodruck** [comment]
ENVIRONMENT
Windows 10 and Chrome 51.0.2704.103 m

RESULT
This shows up in Chrome also when the zoom setting is 175% or higher. When leaving the Last Name field, all the other fields and labels inside of that box move slightly to the right. Perhaps a sizing issue with the Last Name box?

**Comment by josephr5000** [comment]
I do see this, and although it's annoying and the perfectionist in me would like to fix it, I'm having a hard time seeing how it's serious enough to spend time on *instead of* something else of higher importance.

I would propose either (a) saying we'll never fix this, or (b) putting it on the Blue Sky list for future consideration.

What say you?  @tomowens5000

**Comment by drodruck** [comment]
For my two bits, I would suggest we make this a Blue Sky. I'm guessing it's a matter of the length allocated to the Last name field slightly impinging on the left side of the other fields.

**Comment by TomOwens5000** [comment]
Suggest a LIKE (or SHOULD if you can be talked into it) prioritization.

**Comment by josephr5000** [comment]
I asked your opinion above in mid-August and you had nothing to say until now.  That tells me this isn't burning priority.  Doug doesn't think so either.  There are clearly better things to spend time on now.  Easy decision here: POSTPONE.

**Comment by TomOwens5000** [comment]
Okay. Postpone it.
But I would like it fixed at some point.
Closing issue for now.
