### ISSUE TITLE
(11.3) Track change history for Client Profile. Let admins browse change history. Doesn't work

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#449]
Related to #406 
**ENVIRONMENT**
Windows 10 Pro, Firefox and Chrome
**ISSUE**
Track change history for Client Profile. Let admins browse change history. Doesn't work
**WHAT PAGE**
Client File 
**WHAT STEPS WHERE TAKEN**
Clicked on the new “(revision history)” link after making several changes to the client screen at different times. 
**WHAT I EXPECTED**
To be able to see the various changes that I had made today, 1/20/2018 in the afternoon from approximately 1 to 3 PM.
**WHAT HAPPENED**
Got the screen below which showed the current information, not the old, and listed “Unknown” as having made the changes on 12/13/2017.
Screen Shots
 
![image](https://user-images.githubusercontent.com/20655031/35188912-90048a5a-fdf4-11e7-9452-a0fd3947831b.png)

**Comment by josephr5000** [comment]
Theory: I suspect this is a deployment issue where I have a feature switch limiting this to confid=2 or memberid=37 that I created in anticipation of trying this on the LIVE site without disturbing other users.  I suspect I left this feature switch in the TEST version.   Will investigate.

**Comment by josephr5000** [comment]
FIXED.  Yup, theory above was correct.  The feature switch was enabled for memberid=37 (me) only.  Should now be enabled for all.  Please test & confirm.

**Comment by drodruck** [comment]
I tested the history and it shows prior changes.  To test some more, I went back into the Edit Client screen, made a couple of changes, clicked the Save Changes button and nothing happens.  I can get back to the Main Page and getting into the Client File none of the changes were recorded.  Screen shot after clicking the Save Changes button:
![image](https://user-images.githubusercontent.com/20655031/35467863-00f51fb2-02c9-11e8-9ef7-016adaaa7414.png)

**Comment by josephr5000** [comment]
FIXED.  The issue immediately above turned out to be unrelated to change tracking.  I forgot to remove the fields from #415 from the client-side javascript.  The client-side onsubmit script was failing, so the modified client data was never getting to the server.

**Comment by drodruck** [comment]
Yes, the edits work, now and the history works.  I changed the Notes and a history was made but the Notes field in the history record doesn't show a change, it is blank.  I'm not sure you wanted to have that recorded or not?

**Comment by josephr5000** [comment]
*Every* field that you can see on that page (including the checkboxes) should have changes tracked, so please try each one and let me know which ones (if any) don't.  Thanks!

**Comment by drodruck** [comment]
The fields that don't show a change are SSN, age, and Notes.  The value of Notes field does not show at all in the history screen.

**Comment by drodruck** [comment]
I am closing this issue and opening one for the SSN and notes.
