### ISSUE TITLE
Enhancement: allow Conferences to map client addresses

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#45]
Conference website - allow mapping the address like in the CC website. No need to identify the Conference but would generate the map (with back button going to the currently Active File). Faster way for Vinnies assigned to cases to locate destinations than either Google Earth or Bing Maps.

**Comment by josephr5000** [comment]
Changed to more descriptive title.  Filed under BlueSky along with other useful enhancements that can be revisited when the current project is done.

**Comment by TomOwens5000** [comment]
LIVE SITE. Just discovered you have added a **Show Map** button to the **Edit Client Info** screen. It works great! Thanks. Not sure why is still has the Blue Sky - enhancement label rather than FIXED label.  Hope this was an implemented fix by you rather than something just happened by chance!

**Comment by josephr5000** [comment]
@TomOwens5000 I added a few more map links, currently on LIVE *but* only for my conf and OLG so we can preview/test it.

ACTIVE FILE, like this:

![image](https://cloud.githubusercontent.com/assets/8585358/20997423/2d9ce474-bcba-11e6-9d52-e7d0886a44ad.png)

CLIENT FILE, like this:

![image](https://cloud.githubusercontent.com/assets/8585358/20997464/9ff4d932-bcba-11e6-95d7-3fd9d08fb12e.png)

Let me know what you think.

**Comment by TomOwens5000** [comment]
Works fine. I think it is GREAT enhancement. Easier to use that the original Show Map button.
QUESTION. Do you plan to keep the Show Map button or do away with it?

**Comment by josephr5000** [comment]
I'll probably limit the Show Map button to CC users.  I added it at Lisa's request.  She wanted it for the case where CC users want to look up a *different* address if the client whose file they're looking at (and talking to on the phone) says they moved.

For conferences, in my experience folks just want to map the *current* address of the client whose file they're looking at, since that's the location they need to visit.  That's where this map link fits really nicely next to the current address, and pre-configured to send Google maps right to that address.

**Comment by TomOwens5000** [comment]
I agree whole completely. That was my intent when I open #45 in the 
first place.
I agree to removing "Show Map" from the Client File (visible when 
clicking on Edit Details).

**Comment by TomOwens5000** [comment]
Tried it again this morning.
I would suggest a "back" button or something similar to the yellow bar the CC screen uses.

**Comment by josephr5000** [comment]
That's significantly more expensive to do.  Can we just teach people how to use their browser instead?  It opens in a separate tab so as not to disturb what you were in the middle of doing.  Lots of things in browsers use multiple tabs...this isn't new.

Particularly if you're in the Active File you could click multiple ones and open multiple tabs, for example to check if addresses are anywhere close to one another.  Later on I may look at ways to select multiple entries and have them drop pins on the same map so you can plan a home-visit tour, but that's a future item at the moment.  This was low-hanging fruit.  Not too expensive, and incredibly useful.

**Comment by TomOwens5000** [comment]
My guess is a lot of people who will use the system will not necessarily be comfortable with jumping back and forth from their browser (if the even know what that is) and the program. That is why I usually lobby for back buttons that are part of the database program itself.  Who is going to teach people to use their browser(s). I think a lot of them behave a little differently.  Just food for thought.

I really like your idea about drop pins to more efficiently plan multiple visits on the same day.  In our conference our members DO make multiple visits in the same day.
Tom
