### ISSUE TITLE
While trying to add a client in the Call Center the program hangs

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#451]
RELATED TO: ?

ENVIRONMENT
Windows 10 Pro, Firefox and Chrome

ISSUE
While adding a client in the Call Center to check to see if I could change the state, the program hangs

WHAT PAGE
Add New Client

WHAT STEPS WHERE TAKEN
Added a new client, filling in the required fields, clicked the “Create Client File” button.  I waited for several minutes.

WHAT I EXPECTED
The file would be saved.

WHAT HAPPENED
Nothing happens.  There is no indication at the top of the tab that it is trying to save.  I was able to log off and checked in the conference site to see if the file had been saved but the file was not there.  I tried this for the St. Monica conference with the same result.

Screen Shots
![image](https://user-images.githubusercontent.com/20655031/35547673-45363856-052f-11e8-9e42-074359a24771.png)

**Comment by josephr5000** [comment]
**FIXED**

It was attempting (and failing) to validate the rent field, which isn't available to call center users (as you can see above).  Javascript on the client has a nasty habit of failing rather silently, but if you right-click your mouse and choose Inspect (on Chrome, different wording on other browsers) you can select the Console tab and view Javascript error messages as they happen.

**Comment by drodruck** [comment]
Agreed, fixed.
