### ISSUE TITLE
 Can't Export Reports Data to Excel R.1 432, R.2 433, R.6 436 

### ISSUE THREAD

**Issue by SandraMcGowan** [josephr5000/confdb-public#458]
Related items: #432 #433 #436 

Environment:
Windows 10 Pro and Chrome

Issue:
Export report data to excel doesn't work
What Page:
Trying to export report results to Excel

What Steps were taken:
Selected: This quarter date range ran the report got results clicked on Export to Excel

What I Expected:
I expected and Excel spreadsheet to open with the data 

What Happened:
I got this Screen

Screen Shots
Here's the URL;
https://confdb-test.azurewebsites.net/confdb/flexreports/reportrun.asp?TimeWidget_Select=thisQtr&B1=Refresh&id=6&csv=1

![image](https://user-images.githubusercontent.com/34012501/36346710-55e703ce-13f8-11e8-97e0-447bbcb6fc93.png)

**Comment by josephr5000** [comment]
**FIXED**

**Comment by SandraMcGowan** [comment]
I agree this issue is fixed.
