### ISSUE TITLE
(6.1) Client sharing. Now the Call Center can not click on the client file.

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#459]
RELATED TO: #444

ENVIRONMENT
Windows 10 Pro, Firefox, Chrome, Edge, IE

ISSUE
While testing (6.1) Client sharing for Call Center issues found there is no link to the client file.

WHAT PAGE
Browse Client Files

WHAT STEPS WHERE TAKEN
Looking for any client

WHAT I EXPECTED
Should be able to click on a link to the client’s file.

WHAT HAPPENED
There is no link on this page to get to the client’s file.

Screen Shots
![image](https://user-images.githubusercontent.com/20655031/36347562-c6eeb524-140e-11e8-94a9-5a213bae7fa9.png)

**Comment by josephr5000** [comment]
Separate?  Yes please.  Thanks.

**Comment by josephr5000** [comment]
**FIXED**

I didn't see a separate issue about the lack of President.  Did you file it?

**Comment by drodruck** [comment]
The issue for the President is 461.

**Comment by drodruck** [comment]
Now fixed with the latest build.
