### ISSUE TITLE
(12.6) Show/Hide Memos for OPEN and HISTORY items does not work in Chrome

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#460]
RELATED TO: # 422

ENVIRONMENT
Windows 10 Pro, Chrome

ISSUE
(12.6) Show/Hide Memos for OPEN and HISTORY items doesn’t work in Chrome only

WHAT PAGE
Client File

WHAT STEPS WHERE TAKEN
Turned “Show/Hide Notes” on and off for both Open and Assistance

WHAT I EXPECTED
The notes should appear and disappear.

WHAT HAPPENED
No change. This feature works in Edge, IE and Firefox.

Screen Shots
![image](https://user-images.githubusercontent.com/20655031/36347963-a8cdffda-141a-11e8-9260-c7de371d2d86.png)

**Comment by josephr5000** [comment]
@drodruck What version of Chrome are you using?

**Comment by drodruck** [comment]
I just tried it in Android and it works there.

**Comment by drodruck** [comment]
64.0.3282.167

**Comment by drodruck** [comment]
Just tried it in Chrome 64.0.3282.167 and it works now.  Did you do something?

**Comment by josephr5000** [comment]
@drodruck I slave over it all night long :-)    No....didn't do a thing.  Odd.  Keep an eye on it.

**Comment by drodruck** [comment]
That's not good.  It would have been nice to find something wrong and get it fixed.

**Comment by josephr5000** [comment]
@drodruck FYI please add a green resolution tag before you close an item so we know later what happened.  In this I added RESOLVED-NOT REPRO as that seemed the best fit for what you've described above.

**Comment by drodruck** [comment]
I've shared an item with you:

12-6 Test Case.docx
https://docs.google.com/document/d/1utN4bIPFW0OvPxVoAbbEB62BvkVbMwKJ45ElZmEcyWY/edit?usp=sharing&ts=5a989bf6

It's not an attachment -- it's stored online. To open this item, just click  
the link above.
