### ISSUE TITLE
While testing (6.1) Client sharing if there is no president get server error.

### ISSUE THREAD

**Issue by drodruck** [josephr5000/confdb-public#461]
RELATED TO: #444

ENVIRONMENT
Windows 10 Pro, Firefox, Chrome, Edge, IE

ISSUE
While testing (6.1) Client sharing if there is no president I get server error if you click "(contact)"

WHAT PAGE
Browse Client Files

WHAT STEPS WHERE TAKEN
Looked for any client while "Search other conferences" is selected. Clicked "(contact)" to see the conference president's information.

WHAT I EXPECTED
When selecting "(contact)" we should get the president's information or a reasonable response if there is no president identified.

WHAT HAPPENED
If there is no president got a server error.

Screen Shots
![image](https://user-images.githubusercontent.com/20655031/36348594-fe44b604-1427-11e8-8ff3-fb6bf02f08e1.png)

**Comment by josephr5000** [comment]
FIXED.

You'll now get an error like this if the conference didn't say who their president is:

![image](https://user-images.githubusercontent.com/8585358/37238242-eb24558e-23d6-11e8-8e2b-34ad859ff951.png)

**Comment by drodruck** [comment]
Agreed, it works well.  And the "Close" button works, too.
