### ISSUE TITLE
SVDP Report does not work

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#49]
Under Reports/Summary when you click on SVDP Report all the values are zero. I chose several range selections and got the same values.

**Comment by josephr5000** [comment]
NOT REPRO.  Please see note about date ranges in bug #47.  I ran the SVDP report on St James-Blessed Rosalie for FY2016 "This Fiscal Year" and got results as expected.  Please re-test and re-open with further specifics if you disagree.
