### ISSUE TITLE
Call Center Record New Request function

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#52]
Scenario. Everything required to get to this screen has been completed. However, the Conference has NOT submitted any information on the Intake: Services Offered screen.  Instead of having the blue field appear below the drop down arrow would it make sense to have a message indicating that Conference has not submitted the required information? Not sure of what to say but a text message might be better than a blue field - especially for those new to the software. Note that the blue field goes away when doing a screen capture so it is not shown here.
![screen-yyy 08 08 2016](https://cloud.githubusercontent.com/assets/20777996/17492792/4d7f7502-5d62-11e6-9c7a-e50bb3e83241.png)

**Comment by josephr5000** [comment]
I would guess that's just a one-time problem.  The first time the call center encounters that they can't actually enter any requests, Lisa will be on the phone right quick to the conference to get them to fix it.  Once it's fixed, the issue won't occur again.

I don't disagree that a nice message would be nice, but I'm doubtful it's a good use of development and testing time to do this considering how infrequently this error will occur.

Am closing for now, but please reopen with comments if you disagree.
