### ISSUE TITLE
Edit Conference Settings does not work.

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#56]
ENVIRONMENT
Computer System:	Windows 7 Home Edition
Browser:	 Firefox - version 47.0.1

ISSUE
Edit Conference Settings.

WHAT STEPS WHERE TAKEN
When trying to edit any of the fields … 
Save Changes does not work.

WHAT I EXPECTED TO SEE
Administrative Pages to re-occur.

WHAT HAPPENED
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
Therefore, I was unable to determine if the changes I made took effect.

SCREEN SHOT
![screen-12 57 44 20 08 2016](https://cloud.githubusercontent.com/assets/20777996/17833646/7ebc00e4-66d7-11e6-8b83-8047fe96cb09.png)

Intake: Status & Caller Messages and Intake: Types of Help Offered accepts changes and saves them as I expected.

Intake: Quantity of Requests Accepted (Quota) Accepts changes and saves them as expected but …
I expected to see other than selected field to revert back to default values when changing fields.
But whatever was put in those fields when testing them became the new defaults. The Messages box that pops up to prompt for invalid values appears to work fine.

Reports - none of them appear to work. Displays ...
The page cannot be displayed because an internal server error has occurred.

**Comment by josephr5000** [comment]
Oops, broke some links, including the "Administration", "Main Page" and "Logoff" on the screenshot you showed above.  They're all fixed now.

If reports are an issue, would you please open a separate issue with particulars?  Thanks.
