### ISSUE TITLE
Administative Pages - Reports link broken

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#65]
When selecting ANY of the 3 listed reports error message occurs. The links must be broken. This is what I see: The page cannot be displayed because an internal server error has occurred.

**Comment by josephr5000** [comment]
Which listed reports?  Thanks.

**Comment by josephr5000** [comment]
FIXED for 2.  Dropped the response time histogram report as the underlying SQL wasn't available to be migrated.
