### ISSUE TITLE
Active File fails when you turn on Track Migration in Conference Settings

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#68]
When clicking on Active File the program won't comply.  The following message appears.
The page cannot be displayed because an internal server error has occurred.
_**Thought we had this fixed last night - and it did work then - but not working all day today.**_
![screen-1](https://cloud.githubusercontent.com/assets/20777996/17913856/11f67516-6952-11e6-8902-039cee27e1a1.png)
![screen-2](https://cloud.githubusercontent.com/assets/20777996/17913865/288af70c-6952-11e6-9478-aa02a9345f17.png)

**Comment by josephr5000** [comment]
What a wonderful find!  NOW FIXED.

What happened is that at some point you turned on the item in Conference Settings shown below:
![image](https://cloud.githubusercontent.com/assets/8585358/17919081/5bf0d63e-697f-11e6-8154-54cf49d8c312.png)

This setting depends on a column in the Clients table in the database that hadn't been brought over when I migrated data in April.  What's amazing is that no-one noticed until now, until you found this!  So thank you for finding it before real users did!

This is a GREAT example of why a more methodical test approach would be wonderful.
