### ISSUE TITLE
Database Settings - Sort Active File with newest case on top?

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#69]
Does not crash program but also does not update information correctly. Should permit toggling between having the oldest or newest Active Files displayed on the Main Page. Selecting Yes should place the most recent Active File at the TOP of the list. Selecting No should place the oldest Active File at the TOP of the list. Selecting either Yes or No has no effect - the oldest case is always displayed at the top of the list.
![database settings](https://cloud.githubusercontent.com/assets/20777996/17943280/9e40d50a-69ef-11e6-889a-d7d71d8d9294.png)

**Comment by josephr5000** [comment]
FIXED.

FYI this bug also exists in the LIVE site.  Generally these settings are cached for the duration of your login session so changing them doesn't have immediate effect unless I take special steps to make it so.  I didn't when I first implemented this feature, so it worked fine as long as you log out then back in again.  Check out the production site to see what I mean.

Now fixed.  Changes should have immediate effect once you save them.
