### ISSUE TITLE
3 Intake screens on administrative pages

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#78]
One, remove duplicate Save & Cancel buttons. Only a set at the top or bottom of each screen but keep the same convention for ALL screen through the entire software package.
Two, for the 3 Intake: screens ... add a Clear or Refresh button that when clicked on will clear all fields, except those that have default values (i.e., time and day fields - could be set to 8am and Monday by default.) Only have Save & Cancel buttons on top for example. Add Clear or Refresh button to right of Cancel button or whatever placement makes best sense.

![screen-16 43 13 25 08 2016](https://cloud.githubusercontent.com/assets/20777996/17989552/0a44d226-6ae3-11e6-8a71-32ff7c9f4e78.png)

**Comment by josephr5000** [comment]
PARTIALLY FIXED.

1) I agree, Intake:Quota is short and doesn't require duplicate buttons.  I removed the top pair, leaving the bottom pair, and matching the short Intake:Status page.

2) Intake:Types is a pretty long list, taller than you can see on-screen at one time.  Having Save/Cancel available both top and bottom seems helpful enough to outweigh the inconsistency of having the buttons duplicated.

3) What would be the benefit of a clear/refresh button?  What default settings should it clear/refresh to in each of these three screens?  I don't see enough benefit to justify a third button, but feel free to rally others to your cause if you feel strongly about it.
