### ISSUE TITLE
Can't log into CC site as administrator

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#79]
Originally could do this. Has the password changed or those of us testing it been restricted to only being able to log in as Users? Can't try to understand or break anything we can't see!

**Comment by josephr5000** [comment]
FIXED.

I agree, hard to test if you can't log in.  Appears that another user renamed the admin acct for their personal use, so I re-created an admin account with the password previously publicized so others don't hit this.

FYI as mentioned in email to you, I created you a CCTomO admin account for your personal use so you don't have to rely on the shared "admin" account.  Hopefully that helps better isolate you from changes others may make in future.
