### ISSUE TITLE
Which clients did Conference Member Assist report always shows count of -1

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#81]
In the Administrative Pages, when I do a valid search of Conference members daves assisted for Holy Rosary, the research returns a correct number of clients but the value reads: -1 visit record(s) found.

**Comment by josephr5000** [comment]
FIXED.

Tried a couple of workarounds to get a record count, but without success, so I decided that feature is really not essential to the success of this report and doesn't justify investment of a lot more time, so I cut it.

It now no longer says -1 because it no longer gives _any_ record count!
