### ISSUE TITLE
Record Website Feedback

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#84]
Not sure if this is working or not. Either it is broken or Joseph has not had an opportunity to see and respond to it.

![screen-10 30 50 27 08 2016](https://cloud.githubusercontent.com/assets/20777996/18029027/a66c61be-6c41-11e6-89ab-9e8c588c9d4b.png)

**Comment by josephr5000** [comment]
Duplicate of #83, I think.  Closing.
