### ISSUE TITLE
When adding new client request from CC, notice sent but not assign to anyone in Active list

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#86]
When I add a new request to a client, the notice shows up in the Active clients and an email notice was sent to me but the request was not assigned to me (Daves) which is the name unassigned clients should be assigned to.

**Comment by josephr5000** [comment]
FIXED

1) If case is NOT already assigned to anyone, then assigns to the conference's designated intaker.

2) If case IS already assigned to someone then leaves it assigned to them, but copies them on the emailed notification that something happened.

Related to #108
