### ISSUE TITLE
When adding a new request, at times only 15 request types are in the drop down list

### ISSUE THREAD

**Issue by DaveSherwood** [josephr5000/confdb-public#87]
I have duplicated this several times. When in the call center and adding a new request to an existing client, there are only 15 choices on the drop down list of request types. Only four Goods types and seven Service types. But some times the full list is presented. I don't see a reason for this.

**Comment by josephr5000** [comment]
@DaveSherwood it should follow the list of things you've established under Administrative Pages / Intake:Type of Help Offered.  Does it?

**Comment by DaveSherwood** [comment]
Yes, you are correct, that is the list of services I have selected. I forgot I had done that. Now I will have to see if I was actually seeing the full list at times of that was when creating in the Conference setting. I have found that when I have the Call Center open and I have another instance running with the Conference log, when I add the new request, I end up in the Conference setting for both instances. This happened several times so I might have actually been in the Conference setting when I created a new request, and it does bring up the full list of services. I wasn't worried about it since that shouldn't happen in real life scenario. 

Dave 

----- Original Message -----

**Comment by josephr5000** [comment]
Yep, I know what you mean.  Doesn't work well if you attempt to have two separate tabs open in the SAME brand of browser but logged into separate accounts (eg: conf and cc) as it cannot keep the cookies straight.  Recommendation: use two different BRANDS of browser, eg: Chrome and Firefox, which lets you be logged into separate accounts on each one.

**Comment by josephr5000** [comment]
Question seems to be answered.  Not sure why this remains open, so I'm closing it.
