### ISSUE TITLE
Administrative Pages - Edit Conference Screen

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#90]
Clicking on Main Page gives the following error message.  The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.  Clicking on either Administration or Logoff work as expected.

**Comment by josephr5000** [comment]
NOT REPRO.

Here's what I tried:
- Log in
- Click "Administrative Pages"
- Click "Main Page" (I don't think that's what you meant, but wanted to try just to be sure)
WORKED FINE

- Click "Administrative Pages"
- Click "Edit Conference Settings"
- Click "Main Page"
WORKED FINE TOO

Could you reopen with further detail if you still see the problem?  Perhaps I misinterpreted your report and did the wrong thing.

**Comment by TomOwens5000** [comment]
Tested again today 8/30 and it works as expected.
