### ISSUE TITLE
Reports - Assistance Given - column searches issue

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#91]
Appears broken.  Does NOT allow resorting the list vertically with up and down arrows. Bug?
Clicking Refresh will resort list as expected.

**Comment by josephr5000** [comment]
NOT REPRO.

Seems to sort fine for me.  See screenshot below showing results for "This Fiscal Year" after I clicked the "Date" column header.  Am I missing something?

![image](https://cloud.githubusercontent.com/assets/8585358/18075558/b13c3700-6e2a-11e6-9e57-8546bed6f92b.png)
