### ISSUE TITLE
Our Lady of Guadalupe Conference label

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#92]
On the current database we are OL Guadalupe.
On the development site we are OLGuadalulpe.
Need to pick on convention and stick with it.

Read your reply. I originally thought you had hardwired OLGuadalupe. Understand now and changed it to be OL Guadalupe. Closed as far as I am concerned.

**Comment by josephr5000** [comment]
Closing.  NOT A SOFTWARE BUG.

You can edit the name in Edit Conference Settings and call yourselves whatever you'd like.

Please feel free to pick a naming convention that you like (personally I'd suggest including the space so you match other conferences of similar OL name) and run with it.
