### ISSUE TITLE
Intake: Quantity of Requests Accepted (Quota) - Unexpected Behavior

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#94]
Made a few miscellaneous edits. Clicked on Save and got the following error message: The page cannot be displayed because an internal server error has occurred.
My expectation was that the screen would simply stay there with the changes displayed - not go off in the weeds so to speak.
 

![screensss-11 39 59 30 08 2016](https://cloud.githubusercontent.com/assets/20777996/18102239/b6d1dca2-6ea6-11e6-9279-0c41cc35c93f.png)

**Comment by josephr5000** [comment]
@TomOwens5000: can you try to see if you can pin down how to reproduce this?  I understand you stumbled on it unexpectedly, but knowing reliable ways to make it fail greatly helps me find a fix.  Thanks!

**Comment by josephr5000** [comment]
FIXED.

I suspect that what you did was to enter *invalid* data, and *that* is what caused the problem.

The form *was* checking fields directly related to your quota choice, eg: for weekly it would validate # clients, day of week, and time of day settings next to the weekly choice.  That is good.

What it *failed* to do was to validate other entries *unrelated* to your quota choice, but which get sent to the server anyway.

Specific example: if you had chosen weekly, it would ignore any invalid entry you may have made under Tuesday's daily quota number.  It would submit that invalid Tuesday value to the server, which would then promptly choke.

TESTING NOTES:
Please thoroughly test invalid data entries on this page (and other Intake settings).
Be sure to test entering punctuation and letters and symbols in fields that should just have numbers.
Be sure to test unnecessary leading and trailing spaces even if you enter numbers, eg: "    9"
Be sure to test invalid data in fields on-screen that appear unrelated to your intended choice, eg: invalid daily quota data even though you chose Monthly.

Hope this helps.

FYI @drodruck
