### ISSUE TITLE
Browse/Find/Add Clients - Searches Take Too Long With Not Indication A Search Is Taking Place

### ISSUE THREAD

**Issue by TomOwens5000** [josephr5000/confdb-public#99]
Biggest issue here is the inordinate time it takes to make searches - and, even worse, that there is no indication the a search is taking place. These LONG searches give the impression that the computer is hung and nothing is happening. WE NEED AN "HOURGLASS" or some visible indication that a search is taking place - and it should stay visible until the search has been completed. Not sure if this is a bug and not working or was just never installed yet. There is an indicator in the current operational version of the program. Using the same one would work well here as well.

Title should say ... No Indication ... (sorry about typo)

**Comment by josephr5000** [comment]
DUPLICATE.  Isn't this the same complaint as #93?  Please reopen and clarify if it's a different issue.  If you just want to add commentary, better to add such on #93 instead of opening a fresh issue about the same thing.
